### PR TITLE
fix: abort handshake if the torrent is stopped

### LINKED ISSUE #6935: handshake should terminate if torrent is not running (stopped)
### What is the issue?

Currently, Transmission will finish a complete handshake (which includes explicit acknowledgement (`send_handshake`) that client has a torrent) even when the client is not running.  The current codebase with HandshakeMediator hides torrent state like is_running so it's not trivial to check. After the handshake is complete, the connection is dropped in `on_handshake_done`

The optimal solution is to check torrent state during `build_handshake_message`, since it covers all incoming & outgoing, MSE and plaintext scenarios.

This behavior goes back to Tr3 and earlier.

An unexpected complication of this behavior is that it triggers a second (and further) reconnect from peers thinking that we dropped the connection inadvertently. For example, it triggers a retry using UTP or plaintext handshake by a peer.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

2.94+, including Tr4 mainline

### PR DESCRIPTION
**Pull request by tearfur**
Fixes #6935.

### CODE REVIEW

File: libtransmission/peer-mgr.cc [hunk 1]
```diff
@@ -76,12 +76,13 @@ class HandshakeMediator final : public tr_handshake::Mediator
...
         }
 
-        auto info = TorrentInfo{};
-        info.info_hash = tor->info_hash();
-        info.client_peer_id = tor->peer_id();
-        info.id = tor->id();
-        info.is_done = tor->is_done();
-        return info;
+        return TorrentInfo{
+            tor->info_hash(), // info_hash
```
Comment (mikedld) [inline libtransmission/peer-mgr.cc:80]: I wonder if we could bump to C++20, not requiring full compliance but at least allowing for use of designated initializers… Different (and non-blocking) topic though.

File: libtransmission/handshake.cc [hunk 2]
```diff
@@ -437,7 +437,7 @@ ReadState tr_handshake::read_crypto_provide(tr_peerIo* peer_io)
         obfuscated_hash[i] = x_or[i] ^ req3[i];
     }
 
-    if (auto const info = mediator_->torrent_from_obfuscated(obfuscated_hash); info)
+    if (auto const info = mediator_->torrent_from_obfuscated(obfuscated_hash); info && info->is_running)
```
Comment (mikedld) [inline libtransmission/handshake.cc:440]: Slightly misleading log message in the `else` branch now.

File: libtransmission/peer-mgr.cc (hunk 1 above)
Comment (tearfur) [reply libtransmission/peer-mgr.cc:80]: I support that, In fact, I raised #5854 some time ago to track this.

File: libtransmission/handshake.cc (hunk 2 above)
Comment (tearfur) [reply libtransmission/handshake.cc:440]: fa2d688d16855c5144c3154cd9f1a506636fa3a1

**Comment by tearfur** [comment]
Rebased to `main` with autosquash.

**Comment by reardonia** [comment]
Perhaps change commit desc to be more general: this fixes the problem of incorrectly performing a handshake in the common case of a stopped torrent (not is_running).  It's not so much about the very rare case of a torrent stopping mid-handshake.

**Comment by reardonia** [comment]
@ckerr I believe this is the last outstanding handshake bugs to be fixed and would prioritize for 4.1

There are a few other handshake updates but those are optimizations (#6966, #6973, #6987), would still like to see them merged but not as high pri as this one.

**Comment by Pentaphon** [comment]
> I believe this is the last outstanding handshake bugs to be fixed and would prioritize for 4.1

I agree. This should have made 4.1.0 beta 1

**Comment by reardonia** [comment]
@ckerr this is one of the last two I have in my "fully tested" queue, along with #6973.  still hope to have this for 4.1

**Review by ckerr — APPROVED** [review]
