### PR TITLE
fix: add 'years' and 'Infinity' to ETA in transmission-remote

### LINKED ISSUE #5583: Torrent list with ETAs greater than 999 days gets misaligned
### What is the issue?

The torrents with ETA that is greater than 999 days have misaligned columns in the output of `transmission-remote -t`.

### Which application of Transmission?

transmission-remote

### Which version of Transmission?

Any, up to 61679e1

### PR DESCRIPTION
**Pull request by lvd2**
Fixes #5583

### CODE REVIEW

File: utils/remote.cc [hunk 1]
```diff
@@ -118,7 +118,17 @@ static std::string etaToString(int64_t eta)
...
+    {
+        return fmt::format(FMT_STRING("{:d} days"), eta / (60 * 60 * 24));
+    }
+   
+    if (eta < (60 * 60 * 24 * 365 * 100LL))
+    {
+        return fmt::format(FMT_STRING("{:d} years"), eta / (60 * 60 * 24 * 365));
+    }
+
+    return "Infinity";
```
Comment (killemov) [inline utils/remote.cc:131]: Maybe use ∞ (Unicode infinity symbol) instead?

Comment (lvd2) [reply utils/remote.cc]: So it be

**Comment by lvd2** [comment]
What's wrong with the CodeQL status which is not yet reported?

**Comment by tearfur** [comment]
> What's wrong with the CodeQL status which is not yet reported?

Probably because your branch is not up-to-date with `main`. Just merge `main` into your branch or something.

**Comment by nevack** [comment]
> 3 workflows awaiting approval

Not that. First time contributors need approval for running some workflows, like CodeQL

**Comment by lvd2** [comment]
> Not that. First time contributors need approval for running some workflows, like CodeQL

This is what my question about: how much time to wait until CodeQL gets out of 'Expected -- Waiting for the status to be reported' state?

File: utils/remote.cc [hunk 2]
```diff
@@ -118,7 +118,17 @@ static std::string etaToString(int64_t eta)
...
+    {
+        return fmt::format(FMT_STRING("{:d} days"), eta / (60 * 60 * 24));
+    }
+
+    if (eta < (60 * 60 * 24 * 365 * 100LL))
+    {
+        return fmt::format(FMT_STRING("{:d} years"), eta / (60 * 60 * 24 * 365));
+    }
+
+    return "∞";
```
Comment (ckerr) [inline utils/remote.cc:131]: I'd remove the `if` and the inf symbol, and just always return years if months isn't enough

Comment (ckerr) [reply utils/remote.cc:131]: > Completely different approach might be implementing new formatting with column sizes determined 'on-the-fly'.

I think there are some user scripts that depend on the width. It might be better for a one-time change that widens the eta_str width by a character or two so that user scripts can get updated and move on? (Simpler code change for us, too :smile_cat:)

**Review by ckerr — APPROVED** [review]

**Comment by ckerr** [comment]
Thanks @lvd2 !

**Comment by ckerr** [comment]
Notes: Added 'months' and 'years' to ETA display for extremely slow torrents
