### PR TITLE
fix: use process umask for new files.

### LINKED ISSUE #7006: make files in .config/transmission-daemon/ group readable
### What is the issue?

In `/var/lib/transmission-daemon/.config/transmission-daemon/`, all files (`dht.dat`, `stats.json`, `resume/*.resume` and `torrents/*.torrent`) are created `-rw-------` (`umask 077`).

This is ["just an unintended side effect"](https://github.com/transmission/transmission/issues/7006), because they are [created with `mkstemp()`](https://github.com/transmission/transmission/blob/3e9f5f614a875aae987235d3836d0ca555a80d80/libtransmission/utils.cc#L179) without adjusting their permission.

I would like to change the permission to at least `-rw-r-----` (`umask 027`), so I can back them up as a different user in the `transmission` group. (Or even better: `-rw-r--r--` (`umask 022`), like everything else.)

`settings.json` has a setting `umask`, but apparently that's only for files in `download-dir`.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

3.00

### PR DESCRIPTION
**Pull request by jggimi**
Fix #7006

Notes: New files are assigned a file mode per the process _umask_ defined in `settings.json`.

### CODE REVIEW

**Comment by jggimi** [comment]
This (or a similar patch) may also resolve #958 and #982, related to settings.json defaulting to chmod 0600.

**Comment by ilf** [comment]
Awesome, thanks!

**Review by ckerr — CHANGES_REQUESTED** [review]
I like the idea of fixing the issue that this PR is trying to fix, but I don't like this implementation.

- Only works on Linux
- Only works for default config location
- Couples a generic utility `tr_file_save()` with a config-specific / platform-specific setting

I'd really prefer a fix without these issues

**Comment by jggimi** [comment]
> I like the idea of fixing the issue that this PR is trying to fix, but I don't like this implementation.

Thank you for reviewing this!

I'll have to give it more thought.

**Review by tearfur — CHANGES_REQUESTED** [review]
I'd also like to suggest that the Unix implmentation should follow the umask instead of hard coding to `0640`.

**Comment by jggimi** [comment]
Thank you for the recommendation, @tearfur, which is better than what I'd proposed.  

It may take me a while to come up with a revised fix.

**Comment by jggimi** [comment]
I've reworked the diff, and I hope this is an improvement, ready for review again.

1.  The diff in utils.cc was reverted.
2.  The new diff is in file-posix.cc, revising tr_sys_file_open_temp().
3.  The calling process's umask() is used to set the file mode.

**Comment by reardonia** [comment]
This will also set 0640 for resume files?

**Comment by jggimi** [comment]
Yes, but it will do so only if the process umask has been set to 26.  That's because this revised diff uses the process umask(2) to assign file modes.

To address OS differences -- as @ckerr requested in his review --  this proposed change is to file-posix.cc.  Windows uses a different, but identically named _tr_sys_file_open_temp()_ function call, defined in file-win32.cc.

**Comment by ilf** [comment]
@jggimi: Thanks again for your work on this.

I would propose to make these files group readable (permission 640) by default, without having to change the umask of the process. As the discussion in #7006 showed, there is no good reason not to make these files group readable by default.

I also like making this a configuration option. We already have an option `umask` in `settings.json`. How about using that value for these files, too? That would be coherent and obvious.

(Personally, I would like these files to be group *and* world readable (permission 644), so hard-coding them to 640 would only solve part of the issue.)

Thanks, all.

**Comment by jggimi** [comment]
> How about using that value for these files, too? That would be coherent and obvious.

I didn't realize the umask was available from `settings.json` -- thanks for the cluebat!  It appears to default to 22, which would result in file mode 644.  I'll revise the diff to use it.

**Comment by jggimi** [comment]
>  I'll revise the diff to use it.

I'm unable to figure out how to correctly acquire the settings value.  I've tried a few things -- adding an #include for quark.h provides me with the TR_KEY but I cannot determine if I lack the knowledge to correctly utilize the key or if I'm completely off base and heading in the wrong direction

Could anyone point me to an example of obtaining and using a settings.json value, that I may be able to adapt for this?

**Comment by tearfur** [comment]
Actually all the umask setting does is set the process umask, so you can get the value by just calling `umask(2)`.

https://github.com/transmission/transmission/blob/1f36458e1061ad64e9427bdf2ae6748195ab367a/libtransmission/session.cc#L773-L776

**Review by tearfur — CHANGES_REQUESTED** [review]
Also would you please move the code back to `tr_file_save()`? Just wrap the code in `#ifndef _WIN32` to avoid comiling it in Windows.

I'm requesting this because we don't want *any* temp files to have default permissions.

**Comment by jggimi** [comment]
It can't be this easy.  Can it?

https://github.com/transmission/transmission/pull/7195/commits/ea6e095993acdd158bd85960f68da0de6b416c2f

File: libtransmission/utils.cc [hunk 1]
```diff
@@ -193,6 +196,15 @@ bool tr_file_save(std::string_view filename, std::string_view contents, tr_error
     {
         return false;
     }
+#ifndef _WIN32
+    // set file mode per settings umask()
+    else
+    {
+	mode_t val = umask(0);
```
Comment (nevack) [inline libtransmission/utils.cc:203]: Please reformat your code, we use spaces instead of tabs.

You can run `./code_style.sh check` from project directory to check and `./code_style.sh fix` to fix automatically according project's clang-format rules.

Comment (nevack) [inline libtransmission/utils.cc:203]: Do use `::umask` consistently.

You have both just `umask` and explicit `::umask` here.

Comment (jggimi) [reply libtransmission/utils.cc]: reformatted with clang-format, then checked with ./code-style.sh

Comment (jggimi) [reply libtransmission/utils.cc]: Corrected.  Explicit ::umask used.

File: libtransmission/utils.cc [hunk 2]
```diff
@@ -55,6 +55,9 @@
 #include "libtransmission/tr-strbuf.h"
 #include "libtransmission/utils.h"
 #include "libtransmission/values.h"
+#ifndef _WIN32
+#include <sys/stat.h> /* umask() */
+#endif
```
Comment (tearfur) [inline libtransmission/utils.cc:60]: Please include `<sys/stat.h>` below `<arpa/inet.h>` above.

File: libtransmission/utils.cc [hunk 3]
```diff
@@ -193,6 +196,15 @@ bool tr_file_save(std::string_view filename, std::string_view contents, tr_error
     {
         return false;
     }
+#ifndef _WIN32
+    // set file mode per settings umask()
+    else
```
Comment (tearfur) [inline libtransmission/utils.cc:201]: Please delete the `else` line.

**Review by tearfur — COMMENTED** [review]
I'm generally happy with the code, just a few minor nits.

File: libtransmission/utils.cc (hunk 2 above)
Comment (jggimi) [reply libtransmission/utils.cc]: done. https://github.com/transmission/transmission/pull/7195/commits/4f10c20eecf8ec6c3180696786c94889e22aa216

File: libtransmission/utils.cc (hunk 3 above)
Comment (jggimi) [reply libtransmission/utils.cc]: done. https://github.com/transmission/transmission/pull/7195/commits/4f10c20eecf8ec6c3180696786c94889e22aa216

**Comment by jggimi** [comment]
Minor edits completed.

**Comment by tearfur** [comment]
I'll be waiting for the CI workflows to be approved before approving this PR. Can't do that myself.

**Comment by tearfur** [comment]
In the meantime, please update the PR title and description.

Change `Fix for #7006` to `Fix #7006` so that GitHub will automatically close the issue once this PR is merged.

**Comment by jggimi** [comment]
Done.

**Comment by jggimi** [comment]
CI presented a misc-const-correctness error.   Fixed in 1aa82de1fb662584e25924e8f66677e8d96aa802.

**Comment by jggimi** [comment]
Is there any action I need to take to move this forward?

**Comment by jggimi** [comment]
"Notes:" added to first PR comment.

**Review by jggimi — COMMENTED** [review]
@ckerr, is there anything else needed?  Anything I missed?

**Comment by ilf** [comment]
@ckerr: If you find the time for review, I'd love to see this merged.

Background: The freeze for the next Debian stable release is coming up in January, and I would love to see this patch in the next stable package. For that, there needs to be a transmission release with this included, and that needs to be packaged before the freeze.

Thanks, everyone! <3

File: libtransmission/utils.cc [hunk 4]
```diff
@@ -193,6 +194,14 @@ bool tr_file_save(std::string_view filename, std::string_view contents, tr_error
     {
         return false;
     }
+#ifndef _WIN32
+    // set file mode per settings umask()
+    {
+        auto const val = ::umask(0);
+        fchmod(fd, 0666 - val);
```
Comment (ckerr) [inline libtransmission/utils.cc:201]: Are you sure this is correct?

The idiom I usually see is `fchmod(fd, 0666 & ~val);`

Comment (ckerr) [reply libtransmission/utils.cc:201]: First hit on Google that I saw looking for `filetype:c "0666" "fchmod"` is a `tmpfile()` function similar to what we're doing in utils.cc, and its implementation is:

https://android.googlesource.com/platform/bionic/+/ics-mr0/libc/stdio/tmpfile.c

```c++
fd = mkstemp(buf);
if (fd != -1) {
    ...
    u = umask(0);
    (void)umask(u);
    (void)fchmod(fd, 0666 & ~u);
    ...
}
```

Comment (tearfur) [reply libtransmission/utils.cc:201]: Can confirm the current code does not work correctly for umask `033`. My bad for missing that and approving.

Comment (jggimi) [reply libtransmission/utils.cc]: @ckerr @tearfur Thank you both!  I've pushed a correction to use bitwise complement.  Sorry for my thinko.

I've tested this correciton with the default umask 022 (-rw-r--r--), 543 (--w--w-r--), and 330 (-r--r--rw-).

**Comment by jggimi** [comment]
This comment might get buried in a resolved conversation, so I'm duplicating it here.  @ckerr @tearfur Thank you both! I've pushed a correction to use bitwise complement. Sorry for my thinko.

I've tested this correction with the default umask 022 (-rw-r--r--), 543 (--w--w-r--), and 330 (-r--r--rw-).

File: libtransmission/utils.cc [hunk 5]
```diff
@@ -193,6 +194,14 @@ bool tr_file_save(std::string_view filename, std::string_view contents, tr_error
     {
         return false;
     }
+#ifndef _WIN32
+    // set file mode per settings umask()
```
Comment (reardonia) [inline libtransmission/utils.cc:198]: shouldn't this just be done in `tr_sys_file_open_temp()` in file-posix rather than here?

Comment (tearfur) [reply libtransmission/utils.cc:198]: > shouldn't this just be done in `tr_sys_file_open_temp()` in file-posix rather than here?

https://github.com/transmission/transmission/pull/7195#pullrequestreview-2406903681

Comment (jggimi) [reply libtransmission/utils.cc:198]: This has been in *file-posix.cc* before.  It moved back to *utils.cc* at @tearfur's recommendation earlier in this PR conversation.  @tearfur wrote:

> I'm requesting this because we don't want _any_ temp files to have default permissions.

How would y'all like error handling to proceed?

Comment (ckerr) [reply libtransmission/utils.cc:198]: I started to make the exact same suggestion as @reardonia but @tearfur is right about this -- the mask makes sense for every file we want to save, but not necessarily for every call to `tr_sys_file_open_temp()`

**Review by tearfur — APPROVED** [review]

**Comment by ilf** [comment]
Would love to see this in 4.1.0 <3

**Comment by jggimi** [comment]
There were unsuccessful checks, which I believe might have been fixed, since: 

- macos-15-arm64 had a pkgconf <> pkg_config symlink error
- debian-11-from-tarball NPM version mismatch
- windows (x64) NPM version not found
- windows (x86) NPM version not found

**Comment by jggimi** [comment]
@ckerr, is any action on my part needed after your `$ push -f` two weeks ago?

**Comment by ckerr** [comment]
TBH I thought I'd already merged this for 4.1.0-beta.1 :sob:

**Comment by ckerr** [comment]
> @ckerr, is any action on my part needed after your `$ push -f` two weeks ago?

TBH I thought I'd already merged this for 4.1.0-beta.1 😭

Thanks for the reping @jggimi
