### PR TITLE
fix: cannot add magnet links in GTK client

### LINKED ISSUE #8123: Magnet links no longer working
### What is the issue?

I just built the GTK client from source (using main branch, commit a89ca4f), and adding magnet links no longer works.

Building from the latest tag (4.1.0-beta.5), it works fine.

To reproduce:
- click on a magnet link in a browser that has transmission registered for magnet links

Results:
- Transmission client opens, but no new torrent is added

Environment:
- Debian 13
- ARM64

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

main branch a89ca4f

### PR DESCRIPTION
**Pull request by ckerr**
Fixes #8123 in `main` for `4.2.x`.

Fixed by #8277 for `4.1.x`.

This bug was introduced in #8115 and was first released in 4.1.0.

### CODE REVIEW

File: gtk/Session.cc [hunk 1]
```diff
@@ -876,12 +878,11 @@ bool Session::add_from_url(Glib::ustring const& url)
 
 bool Session::Impl::add_from_url(Glib::ustring const& url)
 {
-    auto const file = Gio::File::create_for_uri(url);
```
Comment (tearfur) [inline gtk/Session.cc:879]: Just curious, please help me understand here, because I'm not able to tell where this PR made a difference just by eyeballing it.

M guess now is, when `create_for_uri()` is given a magnet link, the `File` object it produces does not return the exact same string when calling `get_uri()` on it?

Comment (ckerr) [reply gtk/Session.cc:879]: @tearfur sorry, didn't see this question until now.

The problem is Gio::File doesn't handle magnet links correctly, e.g. this test would fail:

```c++
auto file = Gio::File::create_for_uri(magnet_link);
auto actual = file->get_uri();
EXPECT_EQ(magnet_link, actual);
```

So we need to have magnet links get into `Session::Impl::add()` without a middle step of being a `Gio::File`
