### PR TITLE
fix(remote): failure reason should be printed

### LINKED ISSUE #7010: transmission-remote should display an error on connection failure
### What is the issue?

```
$ transmission-remote 0.0.0.0 --session-info
(nothing)
```

It would be nice if `transmission-remote` could dump the underlying error on connection failure for ease of troubleshooting and to avoid confusion as to whether the command succeeded or not. (The exit code is correct though.)

### Which application of Transmission?

transmission-remote

### Which version of Transmission?

4.0.6 (38c164933e)

### PR DESCRIPTION
**Pull request by bheesham**
Uses `fmt::print` to log failure messages. Results in a connection
failure being printed as:

        Unable to send request to 'http://localhost:9091/transmission/rpc/': Couldn't connect to server
Fixes #7010

### CODE REVIEW

**Review by tearfur — COMMENTED** [review]
IMO this should use `fmt::print()` like all other lines. Having log levels and whatnot here adds no value.

**Comment by bheesham** [comment]
@tearfur done! I changed the format of the connection error to be similar to the other messages as well (e.g. `error message: subject`).

**Review by tearfur — APPROVED** [review]

File: utils/remote.cc [hunk 1]
```diff
@@ -2397,7 +2397,7 @@ int flush(char const* rpcurl, tr_variant* benc, RemoteConfig& config)
     auto status = EXIT_SUCCESS;
     if (auto const res = curl_easy_perform(curl); res != CURLE_OK)
     {
-        tr_logAddWarn(fmt::format(" ({}) {}", rpcurl_http, curl_easy_strerror(res)));
+        fmt::print(stderr, "{}: {}\n", curl_easy_strerror(res), rpcurl_http);
```
Comment (mikedld) [inline utils/remote.cc:2400]: Not sure what `curl_easy_strerror()` returns, but I think general approach is to prepend the failure with some description of our own, so maybe
```suggestion
        fmt::print(stderr, "Unable to send request to '{}': {}\n", rpcurl_http, curl_easy_strerror(res));
```

Comment (bheesham) [reply utils/remote.cc]: Ah, yeah, good call. Applied.

**Review by ckerr — COMMENTED** [review]
Do the other calls to `tr_logAddWarn()` make sense in `utils/remote.cc`, or should they be removed too?

**Comment by bheesham** [comment]
> Do the other calls to `tr_logAddWarn()` make sense in `utils/remote.cc`, or should they be removed too?

Solid call -- I rebased and replaced the other `tr_logAddWarn` with a print. I also went ahead and removed the include for the log header, since we're not using anything from there any more.

**Comment by bheesham** [comment]
<details>
<summary>How this looks with <code>-b</code></summary>

```
; ./build/utils/transmission-remote localhost -b --list
posting:
--------
{"arguments":{"fields":["addedDate","error","errorString","eta","id","isFinished","leftUntilDone","name","peersGettingFromUs","peersSendingToUs","rateDownload","rateUpload","sizeWhenDone","status","uploadRatio"]},"method":"torrent-get","tag":6}
--------
* processing: http://localhost:9091/transmission/rpc/
* Couldn't find host localhost in the (nil) file; using defaults
*   Trying [::1]:9091...
* connect to ::1 port 9091 failed: Connection refused
*   Trying 127.0.0.1:9091...
* connect to 127.0.0.1 port 9091 failed: Connection refused
* Failed to connect to localhost port 9091 after 0 ms: Couldn't connect to server
* Closing connection
Unable to send request to 'http://localhost:9091/transmission/rpc/': Couldn't connect to server
```
</details>

<details>
<summary>How this looks <i>without</i> <code>-b</code></summary>

```
; ./build/utils/transmission-remote localhost --list
Unable to send request to 'http://localhost:9091/transmission/rpc/': Couldn't connect to server
```
</details>

<details>
<summary>How this looks <b>on main</b> with <code>-b</code></summary>

```
; ./build/utils/transmission-remote localhost -b --list
posting:
--------
{"arguments":{"fields":["addedDate","error","errorString","eta","id","isFinished","leftUntilDone","name","peersGettingFromUs","peersSendingToUs","rateDownload","rateUpload","sizeWhenDone","status","uploadRatio"]},"method":"torrent-get","tag":6}
--------
* processing: http://localhost:9091/transmission/rpc/
* Couldn't find host localhost in the (nil) file; using defaults
*   Trying [::1]:9091...
* connect to ::1 port 9091 failed: Connection refused
*   Trying 127.0.0.1:9091...
* connect to 127.0.0.1 port 9091 failed: Connection refused
* Failed to connect to localhost port 9091 after 0 ms: Couldn't connect to server
* Closing connection
```
</details>

<details>
<summary>How this looks <b>on main</b> <i>without</i> <code>-b</code></summary>

```
; ./build/utils/transmission-remote localhost --list
< empty >
```
</details>

**Review by ckerr — APPROVED** [review]

**Comment by tearfur** [comment]
@ckerr ping

**Review by ckerr — APPROVED** [review]

**Review by ckerr — APPROVED** [review]

**Comment by ckerr** [comment]
Notes: Improved error logging.

**Comment by bheesham** [comment]
Thanks @ckerr and @tearfur !
