### PR TITLE
fix: parse all http announce responses

### LINKED ISSUE #6216: announces to torrent.ubuntu.com are worse after 42198afc5f
Prior to that commit, announces to torrent.ubuntu.com usually yielded somewhere between 15 and 30 peers.

Starting in 42198afc5feb1c017f6a9c54bef5c854980d201d, only one peer is found.

Very repeatable. The problematic commit was found with `git bisect`. Found while investigating [this test](https://github.com/transmission/transmission/issues/5261#issuecomment-1793599776) by @ziovelvet.

Ubuntu 22.04.3 test torrent @ https://releases.ubuntu.com/22.04/ubuntu-22.04.3-desktop-amd64.iso.torrent

### PR DESCRIPTION
**Pull request by tearfur**
Fixes #6216.

Until Ubuntu fixes their tracker, users may still see that they got just 1 peer from the announce response. But those who used to connect to just 1 peer should connect to more peers now.

Notes: Improved parsing HTTP tracker announce response.

### CODE REVIEW

**Review by ckerr — COMMENTED** [review]
Fix LGTM. 

Also :+1:  on the side-cleanups e.g. migrating the function to take a reference instead of a pointer

**Review by ckerr — APPROVED** [review]

**Comment by Pentaphon** [comment]
>But those who used to connect to just 1 peer should connect to more peers now.
Still getting only 1 peer on the Ubuntu torrent despite 260 seeds. 

It says they use tracker version: T-0.3.18 (BitTornado)
https://torrent.ubuntu.com/tracker_index

I'm thinking of contacting their admin to see if they can switch to a better tracker.

**Comment by tearfur** [comment]
I forgot to mention that only dual stack users benefit from this. IPv4-only users still suffers and there is nothing we can do about it.

**Comment by Pentaphon** [comment]
> IPv4-only users still suffers and there is nothing we can do about it.

Ah yes that's still most people including me. I'll contact them and show them these issues. Thanks for your help, Tearfur.

**Comment by flowerey** [comment]
Any updates? @Pentaphon

File: libtransmission/announcer-http.cc [hunk 1]
```diff
@@ -140,24 +139,21 @@ bool handleAnnounceResponse(tr_web::FetchResponse const& web_response, tr_announ
 void onAnnounceDone(tr_web::FetchResponse const& web_response)
 {
     auto const& [status, body, did_connect, did_timeout, vdata] = web_response;
-    auto* data = static_cast<struct http_announce_data*>(vdata);
+    auto* data = static_cast<http_announce_data*>(vdata);
 
-    ++data->requests_answered_count;
+    auto const got_all_responses = ++data->requests_answered_count == data->requests_sent_count;
```
Comment (miltonmiller7879-cloud) [inline libtransmission/announcer-http.cc:144]: R
