### PR TITLE
Enable global IP query and fixes/refactorings

### LINKED ISSUE #5554: HTTPS tracker issues
### What is the issue?

I'm regularly compiling Transmission from the Github repository (main branch) on a Raspberry Pi 4.
A few days ago, a private tracker was switched from HTTP to HTTPS, and their torrents stopped working with my builds. Scrape and announce calls fail all of a sudden:
```
*   Trying xxx.xxx.xxx.xxx:443...
* Name '2003:c2:7f43:3c00:7e4f:xxxx:xxxx:xxxx' family 2 resolved to '2003:c2:7f43:3c00:7e4f:xxxx:xxxx:xxxx' family 10
* Closing connection 0
[2023-05-23 23:18:50.908] trc xxxxxxxx at tracker.xxxxxxxx.com:443 Sending scrape to libcurl: 'https://tracker.xxxxxxxx.com/yyyyyyyyy/scrape?info_hash=zzzzzzzzzzzzzzzz' (announcer-http.cc:555)
[2023-05-23 23:18:50.909] trc xxxxxxxxx at tracker.xxxxxxxx.com:443 Got scrape response for 'https://tracker.xxxxxxxx.com/yyyyyyyyy/scrape' (announcer-http.cc:505)
[2023-05-23 23:18:50.909] trc xxxxxxxxx at tracker.xxxxxxxx.com:443 scraped url:https://tracker.xxxxxxxx.com/yyyyyyyyy/scrape  -- did_connect:false did_timeout:false seeders:-1 leechers:-1 downloads:-1 downloaders:0 min_request_interval:0 err:Tracker HTTP response 0 (No Response)  (announcer.cc:1340)
[2023-05-23 23:18:50.909] dbg xxxxxxxxx at tracker.xxxxxxxx.com:443 Tracker 'tracker.xxxxxxxx.com:443' scrape error: Could not connect to tracker (Retrying in 20 seconds) (announcer.cc:1256)
```
( I used `TR_CURL_VERBOSE=1 transmission-daemon -f --log-level=trace` for capturing the log messages).

I went back to v4.0.3 and noticed the issue was gone.
I then used `git bisect` and found 474a30ab2dcadd909f076c24407481cd4d07e60e to be the culprit:
Something has changed in this commit that causes Transmission to not work with this tracker.

Note:
If I take the full URL from this log message:
```
[2023-05-23 23:18:50.908] trc xxxxxxxx at tracker.xxxxxxxx.com:443 Sending scrape to libcurl: 'https://tracker.xxxxxxxx.com/yyyyyyyyy/scrape?info_hash=zzzzzzzzzzzzzzzz' (announcer-http.cc:555)
```
and feed it to cURL on the command line, it works just fine. The tracker responds with the bencoded data.

I have both an IPv4 and IPv6 address.

Let me know if you need more information.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

474a30ab2dcadd909f076c24407481cd4d07e60e

### PR DESCRIPTION
**Pull request by tearfur**
1. Enable global IP query, thanks to the new endpoints on transmissionbt.com. https://github.com/transmission/transmission/pull/5329#discussion_r1189389905
2. Fix unintended behavioural change in `tr_address::publicAddress()` for IPv6.
3. Added a new test for the callback of the global IP query feature.
4. Refactor `tr_global_ip_cache` to use a mediator, so that more tests are possible.

Fixes #5554.

### CODE REVIEW

**Comment by ckerr** [comment]
```
The following tests FAILED:
[14:41:24 ](https://trtc.mikedld.com/buildConfiguration/Transmission_Sanity_FreeBSDAmd64polarssl/358577?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandchucktcpluginBuild=true&expandPull+Request+Details=true&expandBuildProblemsSection=true&expandBuildChangesSection=true&showLog=358577_10970_10970&logView=flowAware)    154 - LT.HandshakeTest.outgoingPlaintext (SEGFAULT)
```

The TC Sanity test looks similar to a Windows GitHub action error I saw in another PR earlier today & may not be related to this PR. I think it may be related to 51fd7056ba; if I can't figure it out shortly I'll revert that PR in `main` and then sync this one to `main`

File: libtransmission/global-ip-cache.h [hunk 1]
```diff
@@ -94,19 +119,11 @@ class tr_global_ip_cache
...
-    void update_global_addr(tr_address_type type) noexcept;
-    void update_source_addr(tr_address_type type) noexcept;
-
-    // Only use as a callback for web_->fetch()
-    void on_response_ip_query(tr_address_type type, tr_web::FetchResponse const& response) noexcept;
-
-    tr_web& web_;
-
-    array_ip_t<std::optional<tr_address>> settings_bind_addr_;
+    Mediator& mediator_;
```
Comment (ckerr) [inline libtransmission/global-ip-cache.h:122]: Can't do a full review tonight, but this stuck out and I thought I'd best write it down before I forget

`mediator_` should be private

Comment (tearfur) [reply libtransmission/global-ip-cache.h:122]: It is private.

**Comment by ckerr** [comment]
This looks pretty good. Rebasing to get it caught up with `main` & waiting to make sure it goes green.

@tearfur I've been pretty busy with non-Transmission work and as you've probably noticed my repsonse time is slower than it was before 4.0.3 came out. Please feel free to @-nag me on PRs like this; I really appreciate these improvements :green_heart:

**Comment by 1100101** [comment]
I’ve been using this branch locally since @tearfur pointed me here via #5554 , and haven’t had any issues so far.

**Comment by ckerr** [comment]
> Error: The `brew link` step did not complete successfully

The two macOS CI failures appear to be unrelated to this PR.

**Comment by ckerr** [comment]
If it is related to the Python 3.11.4 bump, that landed about 5 hours ago at https://github.com/Homebrew/homebrew-core/pull/133015. That's consistent with CI being red now but was working last night.

**Comment by nevack** [comment]
> > Error: The `brew link` step did not complete successfully
> 
> The two macOS CI failures appear to be unrelated to this PR. I'm chasing them down in #5606.

/offtopic Brew tries to upgrade both `python@3.11` and `python@3.10`, both are linked (read, links are created in `/usr/local/bin`), so one interferes with the other.
Odd. Maybe we should just run `brew upgrade` as first step, before installing any deps.
Also, should I create an issue for updating our macOS runner?
We are using 11 (aka Big Sur), but 12 (Monterey) and beta of 13 (Ventura, beta) image are available.
This will allow us to use newer Xcode, obviously.

**Comment by ckerr** [comment]
(@nevack maybe follow up in 5606? Adding `brew upgrade` didn't work + also tried to upgrade a bunch of unnecessary crap. Removing `brew update` did work but maybe another fix would have been better.)

**Comment by GaryElshaw** [comment]
> (@nevack maybe follow up in 5606? Adding `brew upgrade` didn't work + also tried to upgrade a bunch of unnecessary crap. Removing `brew update` did work but maybe another fix would have been better.)

I _think_ homebrew deprecated `brew update` for `brew upgrade` a while back.

**Comment by nevack** [comment]
> > (@nevack maybe follow up in 5606? Adding `brew upgrade` didn't work + also tried to upgrade a bunch of unnecessary crap. Removing `brew update` did work but maybe another fix would have been better.)
> 
> I _think_ homebrew deprecated `brew update` for `brew upgrade` a while back.

Wrong, this commands do different things.
`update` just fetches info (index) about new and updated packages.
`upgrade` also really upgrades installed packages.
Neither of them are deprecated, they just serve different purpose.

**Comment by tearfur** [comment]
Notes: Added ability to cache IP addresses used in global communications, and use it to fix UDP6 warning log spam.
