### PR TITLE
fix: crash on invalid command-line value for `--cache` / `-e` arg

### LINKED ISSUE #8134: transmission-remote crash on bad cmdline params
### What is the issue?

typo just led to this:

`transmission-remote localhost:9091 -exit`

yields:

```
terminate called after throwing an instance of 'std::bad_optional_access'
  what():  bad optional access
Aborted
```

### Which application of Transmission?

transmission-remote

### Which version of Transmission?

Tr4.1b5

### PR DESCRIPTION
**Pull request by ckerr**
Fixes #8134.
Introduced in #6798 (4.1.0-beta.1).

Notes: Fixed 4.1.0-beta.1 crash when passing an invalid value for numeric command-line args.

### CODE REVIEW

File: utils/remote.cc [hunk 1]
```diff
@@ -2878,7 +2878,10 @@ int process_args(char const* rpcurl, int argc, char const* const* argv, RemoteCo
                 break;
 
             case 'e':
-                args.insert_or_assign(TR_KEY_cache_size_mib, tr_num_parse<int64_t>(optarg_sv).value());
+                if (auto val = tr_num_parse<int64_t>(optarg_sv))
+                {
+                    args.insert_or_assign(TR_KEY_cache_size_mib, *val);
+                }
```
Comment (tearfur) [inline utils/remote.cc:2884]: If we're going to be faithful to the original behaviour of `atoi()` (pre-6798), then I think the fix should be:

```suggestion
                args.insert_or_assign(TR_KEY_cache_size_mib, tr_num_parse<int64_t>(optarg_sv).value_or(0));
```

But if we were to improve the handling of `-e`, then I think the fix should be:

```suggestion
                if (auto val = tr_num_parse<int64_t>(optarg_sv))
                {
                    args.insert_or_assign(TR_KEY_cache_size_mib, *val);
                }
                else
                {
                    fmt::print(stderr, "Argument to '-e'/'--cache' should be an integer");
                    status |= EXIT_FAILURE;
                }
```

**Review by tearfur — APPROVED** [review]
