### PR TITLE
Fix: values above INT_MAX (68 years) are interpreted as negative values

### LINKED ISSUE #3451: [3.00] Time remaining becomes negative
It's a subtle bug -- relatively hard to see because the format of the text is `0 of 3.14 GB (0%) - 22 years remaining` which looks very similar to `0 of 3.14 GB (0%) - -22 years remaining` (negative 22 years remaining). It's hard to capture a screenshot since it tends to toggle back and forth between positive and negative numbers of years, and eventually settles on "remaining time unknown".

Version: 3.00 (f4489c982e) for OSX

### PR DESCRIPTION
**Pull request by Coeur**
Fix #3451

### CODE REVIEW

File: macosx/Torrent.mm [hunk 1]
```diff
@@ -2068,20 +2068,25 @@ - (BOOL)shouldShowEta
...
 - (NSString*)etaString
 {
-    NSInteger eta;
-    BOOL fromIdle;
-    //don't check for both, since if there's a regular ETA, the torrent isn't idle so it's meaningless
-    if (self.fStat->eta != TR_ETA_NOT_AVAIL && self.fStat->eta != TR_ETA_UNKNOWN)
+    BOOL unknown = NO;
+    time_t eta = self.fStat->eta;
+    // if there's a regular ETA, the torrent isn't idle
+    BOOL fromIdle = NO;
```
Comment (nevack) [inline macosx/Torrent.mm:2074]: I suggest to simplify all this.

As far as I see, `unknown` means early return, so:
```objc++
if (eta > INT_MAX || eta == TR_ETA_NOT_AVAIL || eta >= kETAIdleDisplaySec)
{
    return NSLocalizedString(@"remaining time unknown", "Torrent -> eta string");
}

if (eta == TR_ETA_UNKNOWN)
{
        eta = self.fStat->etaIdle;
        fromIdle = YES;
}
```

Maybe i'm missing something here?

Comment (Coeur) [reply macosx/Torrent.mm:2074]: Yes, you're missing something:
- if fStat->eta is TR_ETA_NOT_AVAIL, we check for fStat->etaIdle
- kETAIdleDisplaySec is to be compared with fStat->etaIdle (not fStat->eta)

So we can't adopt your simplification, we need to keep the way I did. I also had a solution with `goto`, but it would have been frown upon.

Comment (nevack) [reply macosx/Torrent.mm:2074]: If `eta == TR_ETA_NOT_AVAIL` you set `unknown = YES` and then early return on `unknown`.
`self.fStat->etaIdle` is not used in this case.
What am I missing here?

Comment (Coeur) [reply macosx/Torrent.mm:2074]: The second point:
- kETAIdleDisplaySec is to be compared with fStat->etaIdle (not fStat->eta)

Comment (Coeur) [reply macosx/Torrent.mm:2074]: You're also missing the first point:
- if fStat->eta is TR_ETA_NOT_AVAIL, we check for fStat->etaIdle

My PR isn't changing the existing logic (which is already correct), it's just adding a cap for INT_MAX.

Comment (Coeur) [reply macosx/Torrent.mm:2073]: @nevack I've now adopted a code change to avoid declaring `unknown`, if that makes it more readable for you?

**Review by nevack — APPROVED** [review]
LGTM

**Comment by Coeur** [comment]
Notes: Fix values above 68 years (INT_MAX) were displayed as negative values.
