### PR TITLE
fix: acquire lock in tr_peerMgrPeerStats

### LINKED ISSUE #6762: Transmission-87862e506d Build #9564 crash
### What is the issue?

Mac mini (late 2012, 2.5-GHz 4-Core i5), 16GB RAM, plus an assortment of USB & FW HDs.
macOS 14.4.1 Sonoma (w/OCLP 1.4.2), PIA 3.5.7, and Xcode.
Pipe is 450 Mbps wifi to Comcast coax 100/25 Mbps, with PIA beaming me thru to Canada.

Running Transmission-87862e506d Build #9564

Launched with all torrents (~950) paused. Transmission took a *long* time to load / bring up the Main window.  After a while (20+ mins), I opened the Inspector window then resumed all torrents.  Got a couple dozen peers going.  Then I started playing in the Main window, selecting and unselecting various torrents.  Tried to select a whole large group of torrents - when I clicked, Transmission crashed immediately.

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Transmission [7601]
Path:                  /Users/USER/*/Transmission-87862e506d Build #9564.app/Contents/MacOS/Transmission
Identifier:            org.m0k.transmission
Version:               4.1.0-dev (14718.1.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-03-31 23:43:19.2122 -0400
OS Version:            macOS 14.4.1 (23E224)
Report Version:        12
Anonymous UUID:        C5048D24-7417-7AA9-D745-755E4ED63C56

Time Awake Since Boot: 200000 seconds

System Integrity Protection: enabled

Crashed Thread:        1

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000040
Exception Codes:       0x0000000000000001, 0x0000000000000040

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [7601]

VM Region Info: 0x40 is not in any region.  Bytes before following region: 4344172480
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      102eed000-103161000    [ 2512K] r-x/r-x SM=COW  /Users/USER/*/Transmission-87862e506d Build #9564.app/Contents/MacOS/Transmission

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff802a69f7a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff802aa76f3 _pthread_cond_wait + 1211
2   libc++.1.dylib                	    0x7ff8029e0d12 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   libc++.1.dylib                	    0x7ff8029e3ec7 std::__1::__assoc_sub_state::__sub_wait(std::__1::unique_lock<std::__1::mutex>&) + 45
4   libc++.1.dylib                	    0x7ff8029e3f2e std::__1::__assoc_sub_state::wait() + 46
5   Transmission                  	       0x10300b7cd std::__1::future<void>::wait() const + 9 (future:1249) [inlined]
6   Transmission                  	       0x10300b7cd tr_peerMgrPeerStats(tr_torrent const*, unsigned long*) + 280 (peer-mgr.cc:1853)
7   Transmission                  	       0x102f402a1 -[Torrent peers] + 59 (Torrent.mm:947)
8   Transmission                  	       0x102f87786 -[InfoPeersViewController updateInfo] + 1260 (InfoPeersViewController.mm:161)
9   Transmission                  	       0x102f4bbb4 -[InfoWindowController updateInfoStats] + 48 (InfoWindowController.mm:469)
10  Transmission                  	       0x102f0458e -[Controller updateUI] + 904 (Controller.mm:2386)
11  Foundation                    	    0x7ff803ad4814 __NSFireTimer + 67
12  CoreFoundation                	    0x7ff802b9f509 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
13  CoreFoundation                	    0x7ff802b9f0b9 __CFRunLoopDoTimer + 785
14  CoreFoundation                	    0x7ff802b9ecea __CFRunLoopDoTimers + 285
15  CoreFoundation                	    0x7ff802b830ad __CFRunLoopRun + 2108
16  CoreFoundation                	    0x7ff802b822a9 CFRunLoopRunSpecific + 557
17  HIToolbox                     	    0x7ff80da6d829 RunCurrentEventLoopInMode + 292
18  HIToolbox                     	    0x7ff80da6d636 ReceiveNextEventCommon + 665
19  HIToolbox                     	    0x7ff80da6d381 _BlockUntilNextEventMatchingListInModeWithFilter + 66
20  AppKit                        	    0x7ff80614bbe5 _DPSNextEvent + 880
21  AppKit                        	    0x7ff806a5bfe9 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1273
22  AppKit                        	    0x7ff80613d005 -[NSApplication run] + 603
23  AppKit                        	    0x7ff806110ff1 NSApplicationMain + 816
24  Transmission                  	       0x102ef2e7f main + 73 (main.mm:17)
25  dyld                          	    0x7ff80271b366 start + 1942

Thread 1 Crashed:
0   Transmission                  	       0x10301f8d8 (anonymous namespace)::peer_stat_helpers::get_peer_stats(tr_peerMsgs const*, long, unsigned long long) + 71 (peer-mgr.cc:1734) [inlined]
1   Transmission                  	       0x10301f8d8 auto tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8::operator()() const::'lambda'(auto const*)::operator()<tr_peerMsgs>(auto const*) const + 71 (peer-mgr.cc:1850) [inlined]
2   Transmission                  	       0x10301f8d8 tr_peer_stat* std::__1::transform<std::__1::__wrap_iter<tr_peerMsgs* const*>, tr_peer_stat*, tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8::operator()() const::'lambda'(auto const*)>(auto, auto, tr_peer_stat*, tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8::operator()() const::'lambda'(auto const*)) + 78 (transform.h:29) [inlined]
3   Transmission                  	       0x10301f8d8 tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8::operator()() const + 159 (peer-mgr.cc:1846) [inlined]
4   Transmission                  	       0x10301f8d8 decltype(static_cast<tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8&>(fp)()) std::__1::__invoke<tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8&>(tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8&) + 159 (type_traits:3918) [inlined]
5   Transmission                  	       0x10301f8d8 std::__1::__bind_return<tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8, std::__1::tuple<>, std::__1::tuple<>, __is_valid_bind_return<tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8, std::__1::tuple<>, std::__1::tuple<>>::value>::type std::__1::__apply_functor<tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8, std::__1::tuple<>, std::__1::tuple<>>(tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8&, std::__1::tuple<>&, std::__1::__tuple_indices<>, std::__1::tuple<>&&) + 159 (bind.h:257) [inlined]
6   Transmission                  	       0x10301f8d8 std::__1::__bind_return<tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8, std::__1::tuple<>, std::__1::tuple<>, __is_valid_bind_return<tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8, std::__1::tuple<>, std::__1::tuple<>>::value>::type std::__1::__bind<tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8>::operator()<>() + 159 (bind.h:292) [inlined]
7   Transmission                  	       0x10301f8d8 decltype(static_cast<std::__1::__bind<tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8>&>(fp)()) std::__1::__invoke<std::__1::__bind<tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8>&>(std::__1::__bind<tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8>&) + 159 (type_traits:3918) [inlined]
8   Transmission                  	       0x10301f8d8 void std::__1::__invoke_void_return_wrapper<void, true>::__call<std::__1::__bind<tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8>&>(std::__1::__bind<tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8>&) + 159 (invoke.h:61) [inlined]
9   Transmission                  	       0x10301f8d8 std::__1::__function::__alloc_func<std::__1::__bind<tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8>, std::__1::allocator<std::__1::__bind<tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8>>, void ()>::operator()() + 159 (function.h:178) [inlined]
10  Transmission                  	       0x10301f8d8 std::__1::__function::__func<std::__1::__bind<tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8>, std::__1::allocator<std::__1::__bind<tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_8>>, void ()>::operator()() + 196 (function.h:352)
11  Transmission                  	       0x102ff399b std::__1::__function::__value_func<void ()>::operator()() const + 15 (function.h:505) [inlined]
12  Transmission                  	       0x102ff399b std::__1::function<void ()>::operator()() const + 15 (function.h:1182) [inlined]
13  Transmission                  	       0x102ff399b tr_session_thread_impl::on_work_available() + 121 (session-thread.cc:272)
14  Transmission                  	       0x1030b77c0 event_process_active_single_queue + 502 (event.c:1691)
15  Transmission                  	       0x1030b48cb event_process_active + 220 [inlined]
16  Transmission                  	       0x1030b48cb event_base_loop + 1134 (event.c:2006)
17  Transmission                  	       0x102ff3755 tr_session_thread_impl::session_thread_func(event_base*) + 87 (session-thread.cc:244)
18  Transmission                  	       0x102ff3b5f decltype(*static_cast<tr_session_thread_impl*>(fp0).*fp(static_cast<event_base*>(fp1))) std::__1::__invoke<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, void>(void (tr_session_thread_impl::*&&)(event_base*), tr_session_thread_impl*&&, event_base*&&) + 30 (type_traits:3859) [inlined]
19  Transmission                  	       0x102ff3b5f void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, 2ul, 3ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*>&, std::__1::__tuple_indices<2ul, 3ul>) + 30 (thread:287) [inlined]
20  Transmission                  	       0x102ff3b5f void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*>>(void*) + 63 (thread:298)
21  libsystem_pthread.dylib       	    0x7ff802aa718b _pthread_start + 99
22  libsystem_pthread.dylib       	    0x7ff802aa2ae3 thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	    0x7ff802a69e46 __semwait_signal + 10
1   libsystem_c.dylib             	    0x7ff80295c531 nanosleep + 199
2   libc++.1.dylib                	    0x7ff8029f10b4 std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>> const&) + 73
3   Transmission                  	       0x103044bb2 void std::__1::this_thread::sleep_for<long long, std::__1::ratio<1l, 1000l>>(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l>> const&) + 17 (thread:386) [inlined]
4   Transmission                  	       0x103044bb2 tr_web::Impl::curlThreadFunc() + 448 (web.cc:717)
5   Transmission                  	       0x103044e4b decltype(*static_cast<tr_web::Impl*>(fp0).*fp()) std::__1::__invoke<void (tr_web::Impl::*)(), tr_web::Impl*, void>(void (tr_web::Impl::*&&)(), tr_web::Impl*&&) + 26 (type_traits:3859) [inlined]
6   Transmission                  	       0x103044e4b void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*>&, std::__1::__tuple_indices<2ul>) + 26 (thread:287) [inlined]
7   Transmission                  	       0x103044e4b void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*>>(void*) + 59 (thread:298)
8   libsystem_pthread.dylib       	    0x7ff802aa718b _pthread_start + 99
9   libsystem_pthread.dylib       	    0x7ff802aa2ae3 thread_start + 15

Thread 3:: VDKQueue
0   libsystem_kernel.dylib        	    0x7ff802a6c0ae kevent + 10
1   Transmission                  	       0x102f9b1a8 -[VDKQueue watcherThread:] + 240 (VDKQueue.mm:183)
2   Foundation                    	    0x7ff803a8e3cc __NSThread__start__ + 1013
3   libsystem_pthread.dylib       	    0x7ff802aa718b _pthread_start + 99
4   libsystem_pthread.dylib       	    0x7ff802aa2ae3 thread_start + 15

Thread 4:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	    0x7ff802a673ce mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff802a75c88 mach_msg2_internal + 84
2   libsystem_kernel.dylib        	    0x7ff802a6e510 mach_msg_overwrite + 653
3   libsystem_kernel.dylib        	    0x7ff802a676bd mach_msg + 19
4   CoreFoundation                	    0x7ff802b84359 __CFRunLoopServiceMachPort + 143
5   CoreFoundation                	    0x7ff802b82dcc __CFRunLoopRun + 1371
6   CoreFoundation                	    0x7ff802b822a9 CFRunLoopRunSpecific + 557
7   AppKit                        	    0x7ff8062a8abc _NSEventThread + 122
8   libsystem_pthread.dylib       	    0x7ff802aa718b _pthread_start + 99
9   libsystem_pthread.dylib       	    0x7ff802aa2ae3 thread_start + 15

Thread 5:
0   libsystem_pthread.dylib       	    0x7ff802aa2ac0 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	    0x7ff802aa2ac0 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	    0x7ff802aa2ac0 start_wqthread + 0

Thread 1 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007ff0fe054cc0  rcx: 0x0000000000000010  rdx: 0xffffffffffffffd0
  rdi: 0x000070000c3a3d08  rsi: 0x00007ff0f821ee00  rbp: 0x000070000c3a3e10  rsp: 0x000070000c3a3d00
   r8: 0x0000000000000000   r9: 0x0000000000000002  r10: 0x00007ff1018df200  r11: 0x00000ff0f1cb0ee0
  r12: 0x000070000c3a3d08  r13: 0x00006000024eac10  r14: 0x00000000660a2d12  r15: 0x00007ff0f821ee00
  rip: 0x000000010301f8d8  rfl: 0x0000000000010293  cr2: 0x0000000000000040
  
Logical CPU:     3
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14

Thread 1 instruction stream:
  48 8b 40 10 48 8b 18 49-83 c6 c4 48 89 9d 20 ff  H.@.H..I...H.. .
  ff ff 4d 8b 7d 00 0f 57-c0 0f 29 45 c0 0f 29 45  ..M.}..W..)E..)E
  b0 0f 29 45 a0 0f 29 45-90 0f 29 45 80 0f 29 85  ..)E..)E..)E..).
  70 ff ff ff 0f 29 85 60-ff ff ff 0f 29 85 50 ff  p....).`....).P.
  ff ff 0f 29 85 40 ff ff-ff 0f 29 85 30 ff ff ff  ...).@....).0...
  49 8b 07 4c 8d a5 f8 fe-ff ff 4c 89 e7 4c 89 fe  I..L......L..L..
 [ff]50 40 ba 2e 00 00 00-4c 89 e7 48 8d b5 3e ff  .P@.....L..H..>.	<==
  ff ff e8 ad 7e fc ff 49-8b 87 e0 09 00 00 48 89  ....~..I......H.
  45 90 0f b7 85 0c ff ff-ff 66 89 85 3c ff ff ff  E........f..<...
  49 8b 87 d0 09 00 00 8a-40 36 88 85 3a ff ff ff  I.......@6..:...
  49 8b 07 4c 89 ff ff 50-20 48 89 c7 e8 73 03 00  I..L...P H...s..
  00 f3 0f 11 45 98 41 8a-87 f2 09 00 00 88 85 30  ....E.A........0

### Which application of Transmission?

macOS app

### Which version of Transmission?

Transmission-87862e506d Build #9564

### LINKED ISSUE #7118: Reproducible crash in on Windows 11 with 4.1.0-dev (1593b993ad)
### What is the issue?

1) Use the build indicated on Windows 11 with a clean install (did this to test the nightlies)
2) Download the latest MX Linux torrent shown in my screenshot and watch the download progress move along. 
3) Open the torrent properties > peers tab on that torrent
4) Client freezes and Windows shows a "client is not responding" 
5) Client has to be closed and when you open it again, the torrent is back to 0% progress. 

This happens every single time when I do these steps. Pic of what happens below. 

crash

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.1.0-dev (1593b993ad)

### LINKED ISSUE #7309: 4.10 beta 1 unexpectedly terminated with local data piece corrupted
### What is the issue?

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Transmission [98491]
Path:                  /Applications/Transmission.app/Contents/MacOS/Transmission
Identifier:            org.m0k.transmission
Version:               4.1.0-beta.1 (14718.1.1)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-12-16 22:23:28.8835 +0300
OS Version:            macOS 15.2 (24C101)
Report Version:        12
Anonymous UUID:        0ABD00D3-A5D3-3876-416F-77F5393D1D0F


Time Awake Since Boot: 380000 seconds

System Integrity Protection: enabled

Crashed Thread:        1

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000048
Exception Codes:       0x0000000000000001, 0x0000000000000048

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [98491]

VM Region Info: 0x48 is not in any region.  Bytes before following region: 4423270328
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      107a5c000-107c93000    [ 2268K] r-x/r-x SM=COW  /Applications/Transmission.app/Contents/MacOS/Transmission

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff806263aaa __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff8062a27a8 _pthread_cond_wait + 1193
2   libc++.1.dylib                	    0x7ff8061e6a04 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   libc++.1.dylib                	    0x7ff8061e7051 std::__1::__assoc_sub_state::__sub_wait(std::__1::unique_lock<std::__1::mutex>&) + 45
4   libc++.1.dylib                	    0x7ff8061e70b8 std::__1::__assoc_sub_state::wait() + 46
5   Transmission                  	       0x107b6af92 0x107a5c000 + 1109906
6   Transmission                  	       0x107ab069b 0x107a5c000 + 345755
7   Transmission                  	       0x107af4997 0x107a5c000 + 625047
8   Transmission                  	       0x107abab86 0x107a5c000 + 387974
9   Transmission                  	       0x107ab747a 0x107a5c000 + 373882
10  Transmission                  	       0x107a70c9f 0x107a5c000 + 85151
11  Transmission                  	       0x107a7c881 0x107a5c000 + 133249
12  CoreFoundation                	    0x7ff80637e95e __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 137
13  CoreFoundation                	    0x7ff80640aec4 ___CFXRegistrationPost_block_invoke + 86
14  CoreFoundation                	    0x7ff80640ae1a _CFXRegistrationPost + 528
15  CoreFoundation                	    0x7ff80634e7de _CFXNotificationPost + 817
16  Foundation                    	    0x7ff8072d6e3b -[NSNotificationCenter postNotificationName:object:userInfo:] + 82
17  AppKit                        	    0x7ff809d5bee3 -[NSTableView _sendSelectionChangedNotificationForRows:columns:] + 349
18  AppKit                        	    0x7ff809d0076c -[NSTableView _enableSelectionPostingAndPost] + 235
19  AppKit                        	    0x7ff809f571f8 -[NSTableView mouseDown:] + 6067
20  AppKit                        	    0x7ff809f55868 -[NSOutlineView mouseDown:] + 73
21  Transmission                  	       0x107aa7d03 0x107a5c000 + 310531
22  AppKit                        	    0x7ff809e2600a -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 4471
23  AppKit                        	    0x7ff809d9f33d -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 409
24  AppKit                        	    0x7ff809d9ef89 -[NSWindow(NSEventRouting) sendEvent:] + 339
25  AppKit                        	    0x7ff80a69838e -[NSApplication(NSEventRouting) sendEvent:] + 1546
26  AppKit                        	    0x7ff80a2052c3 -[NSApplication _handleEvent:] + 65
27  AppKit                        	    0x7ff809c38575 -[NSApplication run] + 654
28  AppKit                        	    0x7ff809c0b7d4 NSApplicationMain + 823
29  Transmission                  	       0x107a5f73f 0x107a5c000 + 14143
30  dyld                          	    0x7ff805f132cd start + 1805

Thread 1 Crashed:
0   Transmission                  	       0x107b7eff5 0x107a5c000 + 1191925
1   Transmission                  	       0x107b540cf 0x107a5c000 + 1016015
2   Transmission                  	       0x107c03954 0x107a5c000 + 1734996
3   Transmission                  	       0x107c01d68 0x107a5c000 + 1727848
4   Transmission                  	       0x107b53f33 tr_session_thread_impl::session_thread_func(event_base*) + 77
5   Transmission                  	       0x107b542cf 0x107a5c000 + 1016527
6   libsystem_pthread.dylib       	    0x7ff8062a2253 _pthread_start + 99
7   libsystem_pthread.dylib       	    0x7ff80629dbef thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	    0x7ff806263976 __semwait_signal + 10
1   libsystem_c.dylib             	    0x7ff806151cc1 nanosleep + 199
2   libc++.1.dylib                	    0x7ff8061e80f2 std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>> const&) + 73
3   Transmission                  	       0x107ba2a8c tr_web::Impl::curlThreadFunc() + 446
4   Transmission                  	       0x107ba2d6f 0x107a5c000 + 1338735
5   libsystem_pthread.dylib       	    0x7ff8062a2253 _pthread_start + 99
6   libsystem_pthread.dylib       	    0x7ff80629dbef thread_start + 15

Thread 3:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	    0x7ff806260f0e mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff80626f5fa mach_msg2_internal + 84
2   libsystem_kernel.dylib        	    0x7ff806268016 mach_msg_overwrite + 649
3   libsystem_kernel.dylib        	    0x7ff8062611ff mach_msg + 19
4   CoreFoundation                	    0x7ff8063895dd __CFRunLoopServiceMachPort + 143
5   CoreFoundation                	    0x7ff806387fed __CFRunLoopRun + 1393
6   CoreFoundation                	    0x7ff80638744c CFRunLoopRunSpecific + 550
7   AppKit                        	    0x7ff809d9ca9d _NSEventThread + 127
8   libsystem_pthread.dylib       	    0x7ff8062a2253 _pthread_start + 99
9   libsystem_pthread.dylib       	    0x7ff80629dbef thread_start + 15

Thread 4:
0   libsystem_kernel.dylib        	    0x7ff806263aaa __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff8062a27a8 _pthread_cond_wait + 1193
2   GeForceMTLDriver              	       0x2dd973b23 0x2dd802000 + 1514275
3   libsystem_pthread.dylib       	    0x7ff8062a2253 _pthread_start + 99
4   libsystem_pthread.dylib       	    0x7ff80629dbef thread_start + 15

Thread 5:: caulk.messenger.shared:17
0   libsystem_kernel.dylib        	    0x7ff806260e8a semaphore_wait_trap + 10
1   caulk                         	    0x7ff811a88c9d caulk::semaphore::timed_wait(double) + 151
2   caulk                         	    0x7ff811a88bc8 caulk::concurrent::details::worker_thread::run() + 30
3   caulk                         	    0x7ff811a8890a void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 41
4   libsystem_pthread.dylib       	    0x7ff8062a2253 _pthread_start + 99
5   libsystem_pthread.dylib       	    0x7ff80629dbef thread_start + 15

Thread 6:: caulk.messenger.shared:high
0   libsystem_kernel.dylib        	    0x7ff806260e8a semaphore_wait_trap + 10
1   caulk                         	    0x7ff811a88c9d caulk::semaphore::timed_wait(double) + 151
2   caulk                         	    0x7ff811a88bc8 caulk::concurrent::details::worker_thread::run() + 30
3   caulk                         	    0x7ff811a8890a void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 41
4   libsystem_pthread.dylib       	    0x7ff8062a2253 _pthread_start + 99
5   libsystem_pthread.dylib       	    0x7ff80629dbef thread_start + 15

Thread 7:: caulk::deferred_logger
0   libsystem_kernel.dylib        	    0x7ff806260e8a semaphore_wait_trap + 10
1   caulk                         	    0x7ff811a88c9d caulk::semaphore::timed_wait(double) + 151
2   caulk                         	    0x7ff811a88bc8 caulk::concurrent::details::worker_thread::run() + 30
3   caulk                         	    0x7ff811a8890a void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 41
4   libsystem_pthread.dylib       	    0x7ff8062a2253 _pthread_start + 99
5   libsystem_pthread.dylib       	    0x7ff80629dbef thread_start + 15

Thread 8:
0   libsystem_pthread.dylib       	    0x7ff80629dbcc start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	    0x7ff80629dbcc start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	    0x7ff80629dbcc start_wqthread + 0

Thread 11:
0   libsystem_pthread.dylib       	    0x7ff80629dbcc start_wqthread + 0

Thread 12:
0   libsystem_pthread.dylib       	    0x7ff80629dbcc start_wqthread + 0

Thread 13:
0   libsystem_pthread.dylib       	    0x7ff80629dbcc start_wqthread + 0

Thread 14:
0   libsystem_pthread.dylib       	    0x7ff80629dbcc start_wqthread + 0

Thread 15:
0   libsystem_pthread.dylib       	    0x7ff80629dbcc start_wqthread + 0


Thread 1 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000067607df2  rcx: 0x0000000000000010  rdx: 0xffffffffffffffd0
  rdi: 0x0000700006cf4d18  rsi: 0x00007fbfdcd83400  rbp: 0x0000700006cf4e20  rsp: 0x0000700006cf4d10
   r8: 0x0000000000000007   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x00000fbfc89021d0
  r12: 0x00007fbfdcd83400  r13: 0x00007fbfde643250  r14: 0x0000700006cf4d18  r15: 0x0000000107cde068
  rip: 0x0000000107b7eff5  rfl: 0x0000000000010283  cr2: 0x0000000000000048
  
Logical CPU:     6
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14

Thread 1 instruction stream:
  e8 00 00 00 49 89 ff 48-8b 05 ba 4a 11 00 48 8b  ....I..H...J..H.
  00 48 89 45 d0 48 8d 05-34 f0 15 00 48 8b 18 e8  .H.E.H..4...H...
  24 c0 f8 ff 48 89 85 18-ff ff ff 4c 89 bd 28 ff  $...H......L..(.
  ff ff 49 8b 47 08 4c 8b-28 48 8b 40 08 48 89 85  ..I.G.L.(H.@.H..
  10 ff ff ff 49 39 c5 0f-84 ba 03 00 00 48 8b 85  ....I9.......H..
  28 ff ff ff 48 8b 40 10-4c 8b 30 48 83 c3 c4 4c  (...H.@.L.0H...L
  89 b5 20 ff ff ff 4d 8b-65 00 0f 57 c0 0f 29 45  .. ...M.e..W..)E
  c0 0f 29 45 b0 0f 29 45-a0 0f 29 45 90 0f 29 45  ..)E..)E..)E..)E
  80 0f 29 85 70 ff ff ff-0f 29 85 60 ff ff ff 0f  ..).p....).`....
  29 85 50 ff ff ff 0f 29-85 40 ff ff ff 0f 29 85  ).P....).@....).
  30 ff ff ff 49 8b 04 24-4c 8d b5 f8 fe ff ff 4c  0...I..$L......L
  89 f7 4c 89 e6[ff]50 48-ba 2e 00 00 00 4c 89 f7  ..L...PH.....L..	<==

Binary Images:
       0x107a5c000 -        0x107c92fff org.m0k.transmission (4.1.0-beta.1) <1f69c5b8-9564-32e5-8c9f-26e60cd8d417> /Applications/Transmission.app/Contents/MacOS/Transmission
       0x107e91000 -        0x107edcfff org.sparkle-project.Sparkle (1.27.1) <37b3b035-3c83-3a37-a235-cbe17e25f29e> /Applications/Transmission.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x107d61000 -        0x107d6ffff com.apple.CoreWiFi (1.0) <fd1c2624-54f7-3818-b4a6-61b68f81ffd6> /System/Library/PrivateFrameworks/CoreWiFi.framework/Versions/A/CoreWiFi
       0x107d91000 -        0x107d95fff com.apple.Metal (367.6) <9d64b352-2dea-3e5f-b839-e8eff3513fce> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
       0x107d3b000 -        0x107d3bfff com.apple.CoreImage (19.0.0) <e139ac2e-6feb-3e44-b7b4-6045fd99d668> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
       0x1084f7000 -        0x1088aafff CoreImageOld.dylib (*) <66ee7d8d-ed35-3650-8b54-9bede38b7ece> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImageOld.dylib
       0x108aaf000 -        0x108c8efff MetalOld.dylib (*) <6581cd53-8583-38d1-b4b9-773f1dc3f551> /System/Library/Frameworks/Metal.framework/Versions/A/MetalOld.dylib
       0x107dad000 -        0x107db0fff com.apple.IO80211 (1.0) <cc837832-e7ac-35d7-8f85-8b121fa96817> /System/Library/PrivateFrameworks/IO80211.framework/Versions/A/IO80211
       0x108fc7000 -        0x10901afff IO80211Old.dylib (*) <d5cf0107-6e6e-383c-abe9-d66eb450ae2d> /System/Library/PrivateFrameworks/IO80211.framework/Versions/A/IO80211Old.dylib
       0x178b28000 -        0x178cc3fff CoreWiFiOld.dylib (*) <d5cf0107-23e9-3d37-bf68-8c6a05c9024c> /System/Library/PrivateFrameworks/CoreWiFi.framework/Versions/A/CoreWiFiOld.dylib
       0x107d50000 -        0x107d51fff com.apple.WiFiPeerToPeer (685.4.0) <4677bb02-ab92-31a2-b6c8-943d4e522c6b> /System/Library/PrivateFrameworks/WiFiPeerToPeer.framework/Versions/A/WiFiPeerToPeer
       0x1e1f41000 -        0x1e1f68fff WiFiPeerToPeerOld.dylib (*) <d5cf0107-33e0-337b-ba08-5e2854254fd0> /System/Library/PrivateFrameworks/WiFiPeerToPeer.framework/Versions/A/WiFiPeerToPeerOld.dylib
       0x107e01000 -        0x107e01fff com.apple.framework.CoreWLAN (16.0) <f9406e19-e560-343c-a88f-55571d0fedee> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
       0x258f97000 -        0x259011fff CoreWLANOld.dylib (*) <d5cf0107-ffdd-3481-a8d3-a2df28f40b76> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLANOld.dylib
       0x1082ac000 -        0x1082b8fff libobjc-trampolines.dylib (*) <22db7df6-db05-3d65-a80d-137657874408> /usr/lib/libobjc-trampolines.dylib
       0x2dd802000 -        0x2dd9c1fff com.apple.GeForceMTLDriver (16.0.12) <dc9e7ee8-2b92-3fc3-9524-fcae13d2f69d> /System/Library/Extensions/GeForceMTLDriver.bundle/Contents/MacOS/GeForceMTLDriver
       0x1083ad000 -        0x1083b0fff Shim.dylib (*) <a8c8d7c3-9a85-391b-a3f3-430a2bf54b91> /System/Library/Extensions/GeForceMTLDriver.bundle/Contents/MacOS/Shim.dylib
       0x2e0b1f000 -        0x2e0b4bfff com.apple.CIInpainting (3.0) <a78d9fb9-2034-313c-9512-14764f398469> /System/Library/CoreImage/CIInpainting.cifilter/Contents/MacOS/CIInpainting
       0x2e0b5e000 -        0x2e0b78fff com.apple.CIBarcode (2.0) <70d5a4f6-bb10-3dd1-be7e-56f1956e2db5> /System/Library/CoreImage/CIBarcode.cifilter/Contents/MacOS/CIBarcode
       0x2e07a4000 -        0x2e07a6fff com.apple.CIPassThrough (2.0) <7666236f-b143-3d69-9886-a9a74a92b92d> /System/Library/CoreImage/CIPassThrough.cifilter/Contents/MacOS/CIPassThrough
       0x2e0cd4000 -        0x2e0d5efff com.apple.PortraitFilters (1.0) <72375466-de43-3023-bef8-1d12b32f83ca> /System/Library/CoreImage/PortraitFilters.cifilter/Contents/MacOS/PortraitFilters
       0x2e8e61000 -        0x2e8e65fff com.apple.audio.AppleHDAHALPlugIn (600.2) <a49d770e-342b-3d32-a2ee-b0be50b1f7aa> /System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn
       0x2e991b000 -        0x2e9a5ffff com.apple.audio.units.Components (1.14) <d2d515b7-27fe-3023-8925-cee127b886ab> /System/Library/Components/CoreAudio.component/Contents/MacOS/CoreAudio
       0x2ef470000 -        0x2efe36fff com.apple.audio.AudioDSPComponents (1.0) <a6d8d80f-dbf7-3725-9b0f-ba166ca45a8f> /System/Library/Components/AudioDSP.component/Contents/MacOS/AudioDSP
    0x7ff806260000 -     0x7ff80629bfff libsystem_kernel.dylib (*) <907f6ba6-6b4b-39d3-ba4b-d1f4244b50bc> /usr/lib/system/libsystem_kernel.dylib
    0x7ff80629c000 -     0x7ff8062a7fff libsystem_pthread.dylib (*) <7324bb8c-37ad-3a44-becd-969f31077819> /usr/lib/system/libsystem_pthread.dylib
    0x7ff8061cb000 -     0x7ff806247ffb libc++.1.dylib (*) <0c5439f1-011a-38c6-b6f8-de47c8cd2468> /usr/lib/libc++.1.dylib
    0x7ff80630d000 -     0x7ff8067a9ff2 com.apple.CoreFoundation (6.9) <90c186b0-d673-32bc-8916-b12ffa001bc4> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff8072cd000 -     0x7ff8080feff3 com.apple.Foundation (6.9) <80444dda-74a7-353b-a8d4-3e3a05d275d6> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7ff809c07000 -     0x7ff80b0fdffd com.apple.AppKit (6.9) <52c57e92-92f8-3e03-9513-77cc61b010c2> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7ff805f0d000 -     0x7ff805f98c7f dyld (*) <7e2d5f84-7d4f-3322-83cb-dd7bd247f06a> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
    0x7ff806142000 -     0x7ff8061caff7 libsystem_c.dylib (*) <83c4abe1-cf0a-3460-80c9-123e8ecd53ae> /usr/lib/system/libsystem_c.dylib
    0x7ff811a87000 -     0x7ff811aaafff com.apple.audio.caulk (1.0) <69b6d3ae-dd5f-30b4-8cca-a28056f502c1> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)
Writable regions: Total=9.0G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9.0G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               256K        2 
Activity Tracing                   256K        1 
CG image                          1148K      194 
ColorSync                          280K       38 
CoreAnimation                     7524K      701 
CoreGraphics                        12K        2 
CoreImage                           24K        6 
CoreUI image data                 5580K       87 
Foundation                         112K        3 
Image IO                            32K        8 
Kernel Alloc Once                  144K        3 
MALLOC                             1.9G      115 
MALLOC guard page                  120K       30 
SQLite page cache                  384K        3 
STACK GUARD                       56.1M       16 
Stack                             15.6M       16 
VM_ALLOCATE                        744K       20 
VM_ALLOCATE (reserved)             7.1G       10         reserved VM address space (unallocated)
__CTF                               824        1 
__DATA                            32.8M      929 
__DATA_CONST                      91.7M      927 
__DATA_DIRTY                      2556K      337 
__FONT_DATA                        2352        1 
__INFO_FILTER                         8        1 
__LINKEDIT                       190.9M       26 
__OBJC_RO                         76.8M        1 
__OBJC_RW                         2370K        2 
__TEXT                             1.0G      952 
__TPRO_CONST                       272K        2 
dsce.got                           124K        1 
dyld private memory                512K        2 
libnetwork                         640K       16 
mapped file                      308.3M       85 
owned unmapped memory             1060K        1 
shared memory                     1328K       24 
===========                     =======  ======= 
TOTAL                             10.8G     4563 
TOTAL, minus reserved VM space     3.7G     4563 



-----------
Full Report
-----------

{"app_name":"Transmission","timestamp":"2024-12-16 22:23:48.00 +0300","app_version":"4.1.0-beta.1","slice_uuid":"1f69c5b8-9564-32e5-8c9f-26e60cd8d417","build_version":"14718.1.1","platform":1,"bundleID":"org.m0k.transmission","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 15.2 (24C101)","roots_installed":0,"name":"Transmission","incident_id":"415A46DC-5E87-4929-AFC5-250137AA4682"}
{
  "uptime" : 380000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iMac13,2",
  "coalitionID" : 40592,
  "osVersion" : {
    "train" : "macOS 15.2",
    "build" : "24C101",
    "releaseType" : "User"
  },
  "captureTime" : "2024-12-16 22:23:28.8835 +0300",
  "codeSigningMonitor" : 0,
  "incident" : "415A46DC-5E87-4929-AFC5-250137AA4682",
  "pid" : 98491,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-12-15 19:28:10.2071 +0300",
  "procStartAbsTime" : 287286767242131,
  "procExitAbsTime" : 384206561273932,
  "procName" : "Transmission",
  "procPath" : "\/Applications\/Transmission.app\/Contents\/MacOS\/Transmission",
  "bundleInfo" : {"CFBundleShortVersionString":"4.1.0-beta.1","CFBundleVersion":"14718.1.1","CFBundleIdentifier":"org.m0k.transmission"},
  "storeInfo" : {"deviceIdentifierForVendor":"7548CC90-330B-561C-8FB5-A4B3B6D224DB","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.m0k.transmission",
  "crashReporterKey" : "0ABD00D3-A5D3-3876-416F-77F5393D1D0F",
  "codeSigningID" : "org.m0k.transmission",
  "codeSigningTeamID" : "5DPYRBHEAR",
  "codeSigningFlags" : 570490881,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 4294967295,
  "bootSessionUUID" : "EE9A6A92-1E98-4035-8FA1-51415BAAB5BF",
  "sip" : "enabled",
  "vmRegionInfo" : "0x48 is not in any region.  Bytes before following region: 4423270328\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      107a5c000-107c93000    [ 2268K] r-x\/r-x SM=COW  \/Applications\/Transmission.app\/Contents\/MacOS\/Transmission",
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000048","rawCodes":[1,72],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000048"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":98491},
  "vmregioninfo" : "0x48 is not in any region.  Bytes before following region: 4423270328\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      107a5c000-107c93000    [ 2268K] r-x\/r-x SM=COW  \/Applications\/Transmission.app\/Contents\/MacOS\/Transmission",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 1,
  "threads" : [{"id":3759446,"threadState":{"r13":{"value":4294967552},"rax":{"value":260},"rflags":{"value":583},"cpu":{"value":0},"r14":{"value":140704353294912,"symbolLocation":0,"symbol":"_main_thread"},"rsi":{"value":4294967552},"r8":{"value":0},"cr2":{"value":0},"rdx":{"value":0},"r10":{"value":0},"r9":{"value":160},"r15":{"value":0},"rbx":{"value":22},"trap":{"value":133},"err":{"value":33554737},"r11":{"value":582},"rip":{"value":140703231785642},"rbp":{"value":140701925514832},"rsp":{"value":140701925514680},"r12":{"value":0},"rcx":{"value":140701925514680},"flavor":"x86_THREAD_STATE","rdi":{"value":105553288373048}},"queue":"com.apple.main-thread","frames":[{"imageOffset":15018,"symbol":"__psynch_cvwait","symbolLocation":10,"imageIndex":24},{"imageOffset":26536,"symbol":"_pthread_cond_wait","symbolLocation":1193,"imageIndex":25},{"imageOffset":113156,"symbol":"std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)","symbolLocation":18,"imageIndex":26},{"imageOffset":114769,"symbol":"std::__1::__assoc_sub_state::__sub_wait(std::__1::unique_lock<std::__1::mutex>&)","symbolLocation":45,"imageIndex":26},{"imageOffset":114872,"symbol":"std::__1::__assoc_sub_state::wait()","symbolLocation":46,"imageIndex":26},{"imageOffset":1109906,"imageIndex":0},{"imageOffset":345755,"imageIndex":0},{"imageOffset":625047,"imageIndex":0},{"imageOffset":387974,"imageIndex":0},{"imageOffset":373882,"imageIndex":0},{"imageOffset":85151,"imageIndex":0},{"imageOffset":133249,"imageIndex":0},{"imageOffset":465246,"symbol":"__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__","symbolLocation":137,"imageIndex":27},{"imageOffset":1040068,"symbol":"___CFXRegistrationPost_block_invoke","symbolLocation":86,"imageIndex":27},{"imageOffset":1039898,"symbol":"_CFXRegistrationPost","symbolLocation":528,"imageIndex":27},{"imageOffset":268254,"symbol":"_CFXNotificationPost","symbolLocation":817,"imageIndex":27},{"imageOffset":40507,"symbol":"-[NSNotificationCenter postNotificationName:object:userInfo:]","symbolLocation":82,"imageIndex":28},{"imageOffset":1396451,"symbol":"-[NSTableView _sendSelectionChangedNotificationForRows:columns:]","symbolLocation":349,"imageIndex":29},{"imageOffset":1021804,"symbol":"-[NSTableView _enableSelectionPostingAndPost]","symbolLocation":235,"imageIndex":29},{"imageOffset":3473912,"symbol":"-[NSTableView mouseDown:]","symbolLocation":6067,"imageIndex":29},{"imageOffset":3467368,"symbol":"-[NSOutlineView mouseDown:]","symbolLocation":73,"imageIndex":29},{"imageOffset":310531,"imageIndex":0},{"imageOffset":2224138,"symbol":"-[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:]","symbolLocation":4471,"imageIndex":29},{"imageOffset":1671997,"symbol":"-[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]","symbolLocation":409,"imageIndex":29},{"imageOffset":1671049,"symbol":"-[NSWindow(NSEventRouting) sendEvent:]","symbolLocation":339,"imageIndex":29},{"imageOffset":11080590,"symbol":"-[NSApplication(NSEventRouting) sendEvent:]","symbolLocation":1546,"imageIndex":29},{"imageOffset":6283971,"symbol":"-[NSApplication _handleEvent:]","symbolLocation":65,"imageIndex":29},{"imageOffset":202101,"symbol":"-[NSApplication run]","symbolLocation":654,"imageIndex":29},{"imageOffset":18388,"symbol":"NSApplicationMain","symbolLocation":823,"imageIndex":29},{"imageOffset":14143,"imageIndex":0},{"imageOffset":25293,"symbol":"start","symbolLocation":1805,"imageIndex":30}]},{"triggered":true,"id":3759516,"instructionState":{"instructionStream":{"bytes":[232,0,0,0,73,137,255,72,139,5,186,74,17,0,72,139,0,72,137,69,208,72,141,5,52,240,21,0,72,139,24,232,36,192,248,255,72,137,133,24,255,255,255,76,137,189,40,255,255,255,73,139,71,8,76,139,40,72,139,64,8,72,137,133,16,255,255,255,73,57,197,15,132,186,3,0,0,72,139,133,40,255,255,255,72,139,64,16,76,139,48,72,131,195,196,76,137,181,32,255,255,255,77,139,101,0,15,87,192,15,41,69,192,15,41,69,176,15,41,69,160,15,41,69,144,15,41,69,128,15,41,133,112,255,255,255,15,41,133,96,255,255,255,15,41,133,80,255,255,255,15,41,133,64,255,255,255,15,41,133,48,255,255,255,73,139,4,36,76,141,181,248,254,255,255,76,137,247,76,137,230,255,80,72,186,46,0,0,0,76,137,247],"offset":181}},"threadState":{"r13":{"value":140462046589520},"rax":{"value":0},"rflags":{"value":66179},"cpu":{"value":6},"r14":{"value":123145416559896},"rsi":{"value":140462020637696},"r8":{"value":7},"cr2":{"value":72},"rdx":{"value":18446744073709551568},"r10":{"value":0},"r9":{"value":0},"r15":{"value":4425900136},"rbx":{"value":1734376946},"trap":{"value":14,"description":"(no mapping for user data read)"},"err":{"value":4},"r11":{"value":17316378059216},"rip":{"value":4424462325,"matchesCrashFrame":1},"rbp":{"value":123145416560160},"rsp":{"value":123145416559888},"r12":{"value":140462020637696},"rcx":{"value":16},"flavor":"x86_THREAD_STATE","rdi":{"value":123145416559896}},"frames":[{"imageOffset":1191925,"imageIndex":0},{"imageOffset":1016015,"imageIndex":0},{"imageOffset":1734996,"imageIndex":0},{"imageOffset":1727848,"imageIndex":0},{"imageOffset":1015603,"symbol":"tr_session_thread_impl::session_thread_func(event_base*)","symbolLocation":77,"imageIndex":0},{"imageOffset":1016527,"imageIndex":0},{"imageOffset":25171,"symbol":"_pthread_start","symbolLocation":99,"imageIndex":25},{"imageOffset":7151,"symbol":"thread_start","symbolLocation":15,"imageIndex":25}]},{"id":3759517,"frames":[{"imageOffset":14710,"symbol":"__semwait_signal","symbolLocation":10,"imageIndex":24},{"imageOffset":64705,"symbol":"nanosleep","symbolLocation":199,"imageIndex":32},{"imageOffset":119026,"symbol":"std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>> const&)","symbolLocation":73,"imageIndex":26},{"imageOffset":1337996,"symbol":"tr_web::Impl::curlThreadFunc()","symbolLocation":446,"imageIndex":0},{"imageOffset":1338735,"imageIndex":0},{"imageOffset":25171,"symbol":"_pthread_start","symbolLocation":99,"imageIndex":25},{"imageOffset":7151,"symbol":"thread_start","symbolLocation":15,"imageIndex":25}],"threadState":{"r13":{"value":123145417097020},"rax":{"value":4},"rflags":{"value":583},"cpu":{"value":0},"r14":{"value":123145417096920},"rsi":{"value":0},"r8":{"value":0},"cr2":{"value":0},"rdx":{"value":1},"r10":{"value":1},"r9":{"value":100000000},"r15":{"value":0},"rbx":{"value":123145417096920},"trap":{"value":133},"err":{"value":33554766},"r11":{"value":582},"rip":{"value":140703231785334},"rbp":{"value":123145417096896},"rsp":{"value":123145417096840},"r12":{"value":0},"rcx":{"value":123145417096840},"flavor":"x86_THREAD_STATE","rdi":{"value":7939}}},{"id":3760161,"name":"com.apple.NSEventThread","threadState":{"r13":{"value":21592279046},"rax":{"value":268451845},"rflags":{"value":518},"cpu":{"value":0},"r14":{"value":2},"rsi":{"value":21592279046},"r8":{"value":0},"cr2":{"value":0},"rdx":{"value":8589934592},"r10":{"value":254000070918144},"r9":{"value":254000070918144},"r15":{"value":254000070918144},"rbx":{"value":123145420849264},"trap":{"value":133},"err":{"value":16777263},"r11":{"value":518},"rip":{"value":140703231774478},"rbp":{"value":123145420849104},"rsp":{"value":123145420849000},"r12":{"value":4294967295},"rcx":{"value":123145420849000},"flavor":"x86_THREAD_STATE","rdi":{"value":123145420849264}},"frames":[{"imageOffset":3854,"symbol":"mach_msg2_trap","symbolLocation":10,"imageIndex":24},{"imageOffset":62970,"symbol":"mach_msg2_internal","symbolLocation":84,"imageIndex":24},{"imageOffset":32790,"symbol":"mach_msg_overwrite","symbolLocation":649,"imageIndex":24},{"imageOffset":4607,"symbol":"mach_msg","symbolLocation":19,"imageIndex":24},{"imageOffset":509405,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":143,"imageIndex":27},{"imageOffset":503789,"symbol":"__CFRunLoopRun","symbolLocation":1393,"imageIndex":27},{"imageOffset":500812,"symbol":"CFRunLoopRunSpecific","symbolLocation":550,"imageIndex":27},{"imageOffset":1661597,"symbol":"_NSEventThread","symbolLocation":127,"imageIndex":29},{"imageOffset":25171,"symbol":"_pthread_start","symbolLocation":99,"imageIndex":25},{"imageOffset":7151,"symbol":"thread_start","symbolLocation":15,"imageIndex":25}]},{"id":3762486,"frames":[{"imageOffset":15018,"symbol":"__psynch_cvwait","symbolLocation":10,"imageIndex":24},{"imageOffset":26536,"symbol":"_pthread_cond_wait","symbolLocation":1193,"imageIndex":25},{"imageOffset":1514275,"imageIndex":15},{"imageOffset":25171,"symbol":"_pthread_start","symbolLocation":99,"imageIndex":25},{"imageOffset":7151,"symbol":"thread_start","symbolLocation":15,"imageIndex":25}],"threadState":{"r13":{"value":33502123601102592},"rax":{"value":260},"rflags":{"value":583},"cpu":{"value":0},"r14":{"value":123145414414336},"rsi":{"value":33502123601102592},"r8":{"value":0},"cr2":{"value":0},"rdx":{"value":7798016},"r10":{"value":0},"r9":{"value":160},"r15":{"value":7798016},"rbx":{"value":22},"trap":{"value":133},"err":{"value":33554737},"r11":{"value":582},"rip":{"value":140703231785642},"rbp":{"value":123145414414128},"rsp":{"value":123145414413976},"r12":{"value":999996000},"rcx":{"value":123145414413976},"flavor":"x86_THREAD_STATE","rdi":{"value":140462066109328}}},{"id":5001088,"name":"caulk.messenger.shared:17","threadState":{"r13":{"value":0},"rax":{"value":14},"rflags":{"value":515},"cpu":{"value":0},"r14":{"value":105553232185200},"rsi":{"value":105553275218778},"r8":{"value":105553275218752},"cr2":{"value":0},"rdx":{"value":0},"r10":{"value":3547258043381147648},"r9":{"value":25},"r15":{"value":0},"rbx":{"value":105553232185089},"trap":{"value":133},"err":{"value":16777252},"r11":{"value":515},"rip":{"value":140703231774346},"rbp":{"value":123145420316528},"rsp":{"value":123145420316488},"r12":{"value":0},"rcx":{"value":123145420316488},"flavor":"x86_THREAD_STATE","rdi":{"value":153491}},"frames":[{"imageOffset":3722,"symbol":"semaphore_wait_trap","symbolLocation":10,"imageIndex":24},{"imageOffset":7325,"symbol":"caulk::semaphore::timed_wait(double)","symbolLocation":151,"imageIndex":33},{"imageOffset":7112,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":30,"imageIndex":33},{"imageOffset":6410,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*)","symbolLocation":41,"imageIndex":33},{"imageOffset":25171,"symbol":"_pthread_start","symbolLocation":99,"imageIndex":25},{"imageOffset":7151,"symbol":"thread_start","symbolLocation":15,"imageIndex":25}]},{"id":5001089,"name":"caulk.messenger.shared:high","threadState":{"r13":{"value":0},"rax":{"value":14},"rflags":{"value":515},"cpu":{"value":0},"r14":{"value":105553232391376},"rsi":{"value":223235},"r8":{"value":4294967295},"cr2":{"value":0},"rdx":{"value":223235},"r10":{"value":18},"r9":{"value":0},"r15":{"value":0},"rbx":{"value":105553232391169},"trap":{"value":133},"err":{"value":16777252},"r11":{"value":515},"rip":{"value":140703231774346},"rbp":{"value":123145421389680},"rsp":{"value":123145421389640},"r12":{"value":0},"rcx":{"value":123145421389640},"flavor":"x86_THREAD_STATE","rdi":{"value":192619}},"frames":[{"imageOffset":3722,"symbol":"semaphore_wait_trap","symbolLocation":10,"imageIndex":24},{"imageOffset":7325,"symbol":"caulk::semaphore::timed_wait(double)","symbolLocation":151,"imageIndex":33},{"imageOffset":7112,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":30,"imageIndex":33},{"imageOffset":6410,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*)","symbolLocation":41,"imageIndex":33},{"imageOffset":25171,"symbol":"_pthread_start","symbolLocation":99,"imageIndex":25},{"imageOffset":7151,"symbol":"thread_start","symbolLocation":15,"imageIndex":25}]},{"id":5001128,"name":"caulk::deferred_logger","threadState":{"r13":{"value":0},"rax":{"value":14},"rflags":{"value":515},"cpu":{"value":0},"r14":{"value":105553166195320},"rsi":{"value":105553504702424},"r8":{"value":105553504702401},"cr2":{"value":0},"rdx":{"value":0},"r10":{"value":6873730473494144512},"r9":{"value":22},"r15":{"value":0},"rbx":{"value":105553166195201},"trap":{"value":133},"err":{"value":16777252},"r11":{"value":515},"rip":{"value":140703231774346},"rbp":{"value":123145421926256},"rsp":{"value":123145421926216},"r12":{"value":0},"rcx":{"value":123145421926216},"flavor":"x86_THREAD_STATE","rdi":{"value":244483}},"frames":[{"imageOffset":3722,"symbol":"semaphore_wait_trap","symbolLocation":10,"imageIndex":24},{"imageOffset":7325,"symbol":"caulk::semaphore::timed_wait(double)","symbolLocation":151,"imageIndex":33},{"imageOffset":7112,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":30,"imageIndex":33},{"imageOffset":6410,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*)","symbolLocation":41,"imageIndex":33},{"imageOffset":25171,"symbol":"_pthread_start","symbolLocation":99,"imageIndex":25},{"imageOffset":7151,"symbol":"thread_start","symbolLocation":15,"imageIndex":25}]},{"id":5043191,"frames":[{"imageOffset":7116,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":25}],"threadState":{"r13":{"value":0},"rax":{"value":33554800},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":0},"rsi":{"value":241207},"r8":{"value":409604},"cr2":{"value":0},"rdx":{"value":123145415499776},"r10":{"value":0},"r9":{"value":18446744073709551615},"r15":{"value":0},"rbx":{"value":123145416024064},"trap":{"value":133},"err":{"value":33554800},"r11":{"value":582},"rip":{"value":140703232023500},"rbp":{"value":0},"rsp":{"value":123145416024064},"r12":{"value":0},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":123145416024064}}},{"id":5043192,"frames":[{"imageOffset":7116,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":25}],"threadState":{"r13":{"value":0},"rax":{"value":33554800},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":222347},"r8":{"value":409604},"cr2":{"value":0},"rdx":{"value":123145417646080},"r10":{"value":0},"r9":{"value":18446744073709551615},"r15":{"value":123145418169208},"rbx":{"value":123145418170368},"trap":{"value":133},"err":{"value":33554800},"r11":{"value":582},"rip":{"value":140703232023500},"rbp":{"value":0},"rsp":{"value":123145418170368},"r12":{"value":5193733},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":123145418170368}}},{"id":5043193,"frames":[{"imageOffset":7116,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":25}],"threadState":{"r13":{"value":0},"rax":{"value":33554800},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":0},"rsi":{"value":17531},"r8":{"value":409604},"cr2":{"value":0},"rdx":{"value":123145418719232},"r10":{"value":0},"r9":{"value":18446744073709551615},"r15":{"value":0},"rbx":{"value":123145419243520},"trap":{"value":133},"err":{"value":33554800},"r11":{"value":582},"rip":{"value":140703232023500},"rbp":{"value":0},"rsp":{"value":123145419243520},"r12":{"value":0},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":123145419243520}}},{"id":5043534,"frames":[{"imageOffset":7116,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":25}],"threadState":{"r13":{"value":0},"rax":{"value":33554800},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":270635},"r8":{"value":409604},"cr2":{"value":0},"rdx":{"value":123145414426624},"r10":{"value":0},"r9":{"value":18446744073709551615},"r15":{"value":123145414949760},"rbx":{"value":123145414950912},"trap":{"value":133},"err":{"value":33554800},"r11":{"value":582},"rip":{"value":140703232023500},"rbp":{"value":0},"rsp":{"value":123145414950912},"r12":{"value":1966080},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":123145414950912}}},{"id":5043535,"frames":[{"imageOffset":7116,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":25}],"threadState":{"r13":{"value":0},"rax":{"value":33554800},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":0},"rsi":{"value":239375},"r8":{"value":409604},"cr2":{"value":0},"rdx":{"value":123145414963200},"r10":{"value":0},"r9":{"value":18446744073709551615},"r15":{"value":0},"rbx":{"value":123145415487488},"trap":{"value":133},"err":{"value":33554800},"r11":{"value":582},"rip":{"value":140703232023500},"rbp":{"value":0},"rsp":{"value":123145415487488},"r12":{"value":0},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":123145415487488}}},{"id":5043540,"frames":[{"imageOffset":7116,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":25}],"threadState":{"r13":{"value":0},"rax":{"value":33554800},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":0},"rsi":{"value":225659},"r8":{"value":409604},"cr2":{"value":0},"rdx":{"value":123145417109504},"r10":{"value":0},"r9":{"value":18446744073709551615},"r15":{"value":0},"rbx":{"value":123145417633792},"trap":{"value":133},"err":{"value":33554800},"r11":{"value":582},"rip":{"value":140703232023500},"rbp":{"value":0},"rsp":{"value":123145417633792},"r12":{"value":0},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":123145417633792}}},{"id":5043541,"frames":[{"imageOffset":7116,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":25}],"threadState":{"r13":{"value":0},"rax":{"value":33554800},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":0},"rsi":{"value":217863},"r8":{"value":409604},"cr2":{"value":0},"rdx":{"value":123145418182656},"r10":{"value":0},"r9":{"value":18446744073709551615},"r15":{"value":0},"rbx":{"value":123145418706944},"trap":{"value":133},"err":{"value":33554800},"r11":{"value":582},"rip":{"value":140703232023500},"rbp":{"value":0},"rsp":{"value":123145418706944},"r12":{"value":0},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":123145418706944}}},{"id":5043849,"frames":[{"imageOffset":7116,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":25}],"threadState":{"r13":{"value":0},"rax":{"value":0},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":0},"rsi":{"value":0},"r8":{"value":278532},"cr2":{"value":0},"rdx":{"value":123145419255808},"r10":{"value":0},"r9":{"value":18446744073709551615},"r15":{"value":0},"rbx":{"value":0},"trap":{"value":0},"err":{"value":0},"r11":{"value":0},"rip":{"value":140703232023500},"rbp":{"value":0},"rsp":{"value":123145419780096},"r12":{"value":0},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":123145419780096}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4423270400,
    "CFBundleShortVersionString" : "4.1.0-beta.1",
    "CFBundleIdentifier" : "org.m0k.transmission",
    "size" : 2322432,
    "uuid" : "1f69c5b8-9564-32e5-8c9f-26e60cd8d417",
    "path" : "\/Applications\/Transmission.app\/Contents\/MacOS\/Transmission",
    "name" : "Transmission",
    "CFBundleVersion" : "14718.1.1"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4427681792,
    "CFBundleShortVersionString" : "1.27.1",
    "CFBundleIdentifier" : "org.sparkle-project.Sparkle",
    "size" : 311296,
    "uuid" : "37b3b035-3c83-3a37-a235-cbe17e25f29e",
    "path" : "\/Applications\/Transmission.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/A\/Sparkle",
    "name" : "Sparkle",
    "CFBundleVersion" : "1.106"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4426436608,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.CoreWiFi",
    "size" : 61440,
    "uuid" : "fd1c2624-54f7-3818-b4a6-61b68f81ffd6",
    "path" : "\/System\/Library\/PrivateFrameworks\/CoreWiFi.framework\/Versions\/A\/CoreWiFi",
    "name" : "CoreWiFi",
    "CFBundleVersion" : "845.7"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4426633216,
    "CFBundleShortVersionString" : "367.6",
    "CFBundleIdentifier" : "com.apple.Metal",
    "size" : 20480,
    "uuid" : "9d64b352-2dea-3e5f-b839-e8eff3513fce",
    "path" : "\/System\/Library\/Frameworks\/Metal.framework\/Versions\/A\/Metal",
    "name" : "Metal",
    "CFBundleVersion" : "367.6"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4426280960,
    "CFBundleShortVersionString" : "19.0.0",
    "CFBundleIdentifier" : "com.apple.CoreImage",
    "size" : 4096,
    "uuid" : "e139ac2e-6feb-3e44-b7b4-6045fd99d668",
    "path" : "\/System\/Library\/Frameworks\/CoreImage.framework\/Versions\/A\/CoreImage",
    "name" : "CoreImage",
    "CFBundleVersion" : "1510.60.3"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4434391040,
    "size" : 3883008,
    "uuid" : "66ee7d8d-ed35-3650-8b54-9bede38b7ece",
    "path" : "\/System\/Library\/Frameworks\/CoreImage.framework\/Versions\/A\/CoreImageOld.dylib",
    "name" : "CoreImageOld.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4440387584,
    "size" : 1966080,
    "uuid" : "6581cd53-8583-38d1-b4b9-773f1dc3f551",
    "path" : "\/System\/Library\/Frameworks\/Metal.framework\/Versions\/A\/MetalOld.dylib",
    "name" : "MetalOld.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4426747904,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.IO80211",
    "size" : 16384,
    "uuid" : "cc837832-e7ac-35d7-8f85-8b121fa96817",
    "path" : "\/System\/Library\/PrivateFrameworks\/IO80211.framework\/Versions\/A\/IO80211",
    "name" : "IO80211",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4445728768,
    "size" : 344064,
    "uuid" : "d5cf0107-6e6e-383c-abe9-d66eb450ae2d",
    "path" : "\/System\/Library\/PrivateFrameworks\/IO80211.framework\/Versions\/A\/IO80211Old.dylib",
    "name" : "IO80211Old.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 6319931392,
    "size" : 1687552,
    "uuid" : "d5cf0107-23e9-3d37-bf68-8c6a05c9024c",
    "path" : "\/System\/Library\/PrivateFrameworks\/CoreWiFi.framework\/Versions\/A\/CoreWiFiOld.dylib",
    "name" : "CoreWiFiOld.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4426366976,
    "CFBundleShortVersionString" : "685.4.0",
    "CFBundleIdentifier" : "com.apple.WiFiPeerToPeer",
    "size" : 8192,
    "uuid" : "4677bb02-ab92-31a2-b6c8-943d4e522c6b",
    "path" : "\/System\/Library\/PrivateFrameworks\/WiFiPeerToPeer.framework\/Versions\/A\/WiFiPeerToPeer",
    "name" : "WiFiPeerToPeer",
    "CFBundleVersion" : "685.4"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8085835776,
    "size" : 163840,
    "uuid" : "d5cf0107-33e0-337b-ba08-5e2854254fd0",
    "path" : "\/System\/Library\/PrivateFrameworks\/WiFiPeerToPeer.framework\/Versions\/A\/WiFiPeerToPeerOld.dylib",
    "name" : "WiFiPeerToPeerOld.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4427091968,
    "CFBundleShortVersionString" : "16.0",
    "CFBundleIdentifier" : "com.apple.framework.CoreWLAN",
    "size" : 4096,
    "uuid" : "f9406e19-e560-343c-a88f-55571d0fedee",
    "path" : "\/System\/Library\/Frameworks\/CoreWLAN.framework\/Versions\/A\/CoreWLAN",
    "name" : "CoreWLAN",
    "CFBundleVersion" : "1657"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 10082676736,
    "size" : 503808,
    "uuid" : "d5cf0107-ffdd-3481-a8d3-a2df28f40b76",
    "path" : "\/System\/Library\/Frameworks\/CoreWLAN.framework\/Versions\/A\/CoreWLANOld.dylib",
    "name" : "CoreWLANOld.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4431986688,
    "size" : 53248,
    "uuid" : "22db7df6-db05-3d65-a80d-137657874408",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 12306096128,
    "CFBundleShortVersionString" : "16.0.12",
    "CFBundleIdentifier" : "com.apple.GeForceMTLDriver",
    "size" : 1835008,
    "uuid" : "dc9e7ee8-2b92-3fc3-9524-fcae13d2f69d",
    "path" : "\/System\/Library\/Extensions\/GeForceMTLDriver.bundle\/Contents\/MacOS\/GeForceMTLDriver",
    "name" : "GeForceMTLDriver",
    "CFBundleVersion" : "16.0.0"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4433039360,
    "size" : 16384,
    "uuid" : "a8c8d7c3-9a85-391b-a3f3-430a2bf54b91",
    "path" : "\/System\/Library\/Extensions\/GeForceMTLDriver.bundle\/Contents\/MacOS\/Shim.dylib",
    "name" : "Shim.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 12359692288,
    "CFBundleShortVersionString" : "3.0",
    "CFBundleIdentifier" : "com.apple.CIInpainting",
    "size" : 184320,
    "uuid" : "a78d9fb9-2034-313c-9512-14764f398469",
    "path" : "\/System\/Library\/CoreImage\/CIInpainting.cifilter\/Contents\/MacOS\/CIInpainting",
    "name" : "CIInpainting",
    "CFBundleVersion" : "1510.60.3"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 12359950336,
    "CFBundleShortVersionString" : "2.0",
    "CFBundleIdentifier" : "com.apple.CIBarcode",
    "size" : 110592,
    "uuid" : "70d5a4f6-bb10-3dd1-be7e-56f1956e2db5",
    "path" : "\/System\/Library\/CoreImage\/CIBarcode.cifilter\/Contents\/MacOS\/CIBarcode",
    "name" : "CIBarcode",
    "CFBundleVersion" : "1510.60.3"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 12356042752,
    "CFBundleShortVersionString" : "2.0",
    "CFBundleIdentifier" : "com.apple.CIPassThrough",
    "size" : 12288,
    "uuid" : "7666236f-b143-3d69-9886-a9a74a92b92d",
    "path" : "\/System\/Library\/CoreImage\/CIPassThrough.cifilter\/Contents\/MacOS\/CIPassThrough",
    "name" : "CIPassThrough",
    "CFBundleVersion" : "1510.60.3"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 12361482240,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.PortraitFilters",
    "size" : 569344,
    "uuid" : "72375466-de43-3023-bef8-1d12b32f83ca",
    "path" : "\/System\/Library\/CoreImage\/PortraitFilters.cifilter\/Contents\/MacOS\/PortraitFilters",
    "name" : "PortraitFilters",
    "CFBundleVersion" : "30"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 12497326080,
    "CFBundleShortVersionString" : "600.2",
    "CFBundleIdentifier" : "com.apple.audio.AppleHDAHALPlugIn",
    "size" : 20480,
    "uuid" : "a49d770e-342b-3d32-a2ee-b0be50b1f7aa",
    "path" : "\/System\/Library\/Extensions\/AppleHDA.kext\/Contents\/PlugIns\/AppleHDAHALPlugIn.bundle\/Contents\/MacOS\/AppleHDAHALPlugIn",
    "name" : "AppleHDAHALPlugIn",
    "CFBundleVersion" : "600.2"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 12508573696,
    "CFBundleShortVersionString" : "1.14",
    "CFBundleIdentifier" : "com.apple.audio.units.Components",
    "size" : 1331200,
    "uuid" : "d2d515b7-27fe-3023-8925-cee127b886ab",
    "path" : "\/System\/Library\/Components\/CoreAudio.component\/Contents\/MacOS\/CoreAudio",
    "name" : "CoreAudio",
    "CFBundleVersion" : "1.14"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 12604342272,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.AudioDSPComponents",
    "size" : 10252288,
    "uuid" : "a6d8d80f-dbf7-3725-9b0f-ba166ca45a8f",
    "path" : "\/System\/Library\/Components\/AudioDSP.component\/Contents\/MacOS\/AudioDSP",
    "name" : "AudioDSP",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703231770624,
    "size" : 245760,
    "uuid" : "907f6ba6-6b4b-39d3-ba4b-d1f4244b50bc",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703232016384,
    "size" : 49152,
    "uuid" : "7324bb8c-37ad-3a44-becd-969f31077819",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703231160320,
    "size" : 511996,
    "uuid" : "0c5439f1-011a-38c6-b6f8-de47c8cd2468",
    "path" : "\/usr\/lib\/libc++.1.dylib",
    "name" : "libc++.1.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703232479232,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 4837363,
    "uuid" : "90c186b0-d673-32bc-8916-b12ffa001bc4",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "3208"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703248994304,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 14884852,
    "uuid" : "80444dda-74a7-353b-a8d4-3e3a05d275d6",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "3208"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703292223488,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 21983230,
    "uuid" : "52c57e92-92f8-3e03-9513-77cc61b010c2",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2575.30.19"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703228284928,
    "size" : 572544,
    "uuid" : "7e2d5f84-7d4f-3322-83cb-dd7bd247f06a",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703230599168,
    "size" : 561144,
    "uuid" : "83c4abe1-cf0a-3460-80c9-123e8ecd53ae",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703424868352,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 147456,
    "uuid" : "69b6d3ae-dd5f-30b4-8cca-a28056f502c1",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  }
],
  "sharedCache" : {
  "base" : 140703227535360,
  "size" : 25769803776,
  "uuid" : "a808c443-7710-3b25-8053-c8076aa3c7c8"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)\nWritable regions: Total=9.0G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9.0G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               256K        2 \nActivity Tracing                   256K        1 \nCG image                          1148K      194 \nColorSync                          280K       38 \nCoreAnimation                     7524K      701 \nCoreGraphics                        12K        2 \nCoreImage                           24K        6 \nCoreUI image data                 5580K       87 \nFoundation                         112K        3 \nImage IO                            32K        8 \nKernel Alloc Once                  144K        3 \nMALLOC                             1.9G      115 \nMALLOC guard page                  120K       30 \nSQLite page cache                  384K        3 \nSTACK GUARD                       56.1M       16 \nStack                             15.6M       16 \nVM_ALLOCATE                        744K       20 \nVM_ALLOCATE (reserved)             7.1G       10         reserved VM address space (unallocated)\n__CTF                               824        1 \n__DATA                            32.8M      929 \n__DATA_CONST                      91.7M      927 \n__DATA_DIRTY                      2556K      337 \n__FONT_DATA                        2352        1 \n__INFO_FILTER                         8        1 \n__LINKEDIT                       190.9M       26 \n__OBJC_RO                         76.8M        1 \n__OBJC_RW                         2370K        2 \n__TEXT                             1.0G      952 \n__TPRO_CONST                       272K        2 \ndsce.got                           124K        1 \ndyld private memory                512K        2 \nlibnetwork                         640K       16 \nmapped file                      308.3M       85 \nowned unmapped memory             1060K        1 \nshared memory                     1328K       24 \n===========                     =======  ======= \nTOTAL                             10.8G     4563 \nTOTAL, minus reserved VM space     3.7G     4563 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "7cf6571bdc4b047b0c42ab3f8c409ce7b64f21ac",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000083
    },
    {
      "rolloutId" : "6434420a89ec2e0a7a38bf5a",
      "factorPackIds" : {

      },
      "deploymentId" : 240000011
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "45f4e2a5-551b-4bc2-a2dc-19c244dda8f8",
      "experimentId" : "6643969b3099cf28e049862f",
      "deploymentId" : 400000007
    }
  ]
}
}

Model: iMac13,2, BootROM 429.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 3,4 GHz, 32 GB, SMC 2.11f14
Graphics: NVIDIA GeForce GTX 680MX, NVIDIA GeForce GTX 680MX, PCIe, 2 GB
Display: iMac, 2560 x 1440 (QHD/WQHD - Wide Quad High Definition), Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364A5446314736344A485A2D3147364532
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364A5446314736344A485A2D3147364532
Memory Module: BANK 0/DIMM1, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364A5446314736344A485A2D3147364532
Memory Module: BANK 1/DIMM1, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364A5446314736344A485A2D3147364532
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0xF4), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1772.1)
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet, Ethernet, en0
PCI Card: LaCie Storage Controller, RAID Controller, Thunderbolt@194,0,0
Serial ATA Device: APPLE SSD SM768E, 751,28 GB
USB Device: USB20Bus
USB Device: hub_device
USB Device: hub_device
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB20Bus
USB Device: hub_device
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB30Bus
USB Device: ASM107U3
USB Device: My Book Duo 25F6
USB Device: My Book 25EE
USB Device: USB3.0 Hub
USB Device: USB3.0 Hub
USB Device: Elements 25A3
USB Device: Elements 25A3
USB Device: ASM107U2
USB Device: Back-UPS XS 1100CI FW:920.T2 .I USB FW:T3
USB Device: USB2.0 Hub
USB Device: USB2.0 Hub
USB Device: iMac Stand Audio
USB Device: Satechi Compact Keyboard
Thunderbolt Bus: iMac, Apple Inc., 23.4
Thunderbolt Device: 5big Thunderbolt 2, LaCie, 3, 24.1
```

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.10 beta 1

### LINKED ISSUE #7752: Deadlock on session lock with current `main`
### What is the issue?

Callstacks (relevant threads):

```
Thread 8 (Thread 0x7fffe97fb6c0 (LWP 14712) "transmission-qt"):
#0  futex_wait (futex_word=0x55555640ce90, expected=2, private=0) at ../sysdeps/nptl/futex-internal.h:146
#1  __GI___lll_lock_wait (futex=futex@entry=0x55555640ce90, private=0) at lowlevellock.c:49
#2  0x00007ffff4ea9f68 in lll_mutex_lock_optimized (mutex=0x55555640ce90) at pthread_mutex_lock.c:48
#3  ___pthread_mutex_lock (mutex=0x55555640ce90) at pthread_mutex_lock.c:128
#4  0x0000555555970d56 in __gthread_mutex_lock (__mutex=0x55555640ce90) at …gcc…/g++-v15/x86_64-pc-linux-gnu/bits/gthr-default.h:795
#5  __gthread_recursive_mutex_lock (__mutex=0x55555640ce90) at …gcc…/g++-v15/x86_64-pc-linux-gnu/bits/gthr-default.h:857
#6  std::recursive_mutex::lock (this=0x55555640ce90) at …gcc…/g++-v15/mutex:127
#7  0x00005555559775dd in std::unique_lock<std::recursive_mutex>::lock (this=0x7fffe97f3970) at …gcc…/g++-v15/bits/unique_lock.h:144
#8  0x000055555597443f in std::unique_lock<std::recursive_mutex>::unique_lock (this=0x7fffe97f3970, __m=...) at …gcc…/g++-v15/bits/unique_lock.h:75
#9  0x0000555555970f82 in tr_session::unique_lock (this=0x55555640cae0) at …/libtransmission/../libtransmission/session.h:580
#10 0x0000555555a3c541 in tr_peerMgr::unique_lock (this=0x5555563d9f60) at …/libtransmission/peer-mgr.cc:1213
#11 0x0000555555a22bd4 in tr_peerMgrAddPex (tor=0x7fffd4052fe0, from=TR_PEER_FROM_TRACKER, pex=0x7fffd48f7740, n_pex=1) at …/libtransmission/peer-mgr.cc:1498
#12 0x0000555555b80e81 in tr_torrent::on_tracker_response (this=0x7fffd4052fe0, event=0x7fffe97f3ce0) at …/libtransmission/torrent.cc:2035
#13 0x0000555555b90313 in std::__invoke_impl<void, void (tr_torrent::*&)(tr_tracker_event const*), tr_torrent&, tr_tracker_event const*> (__f=@0x7fffd4076e78: (void (tr_torrent::*)(tr_torrent * const, const tr_tracker_event *)) 0x555555b80c7e <tr_torrent::on_tracker_response(tr_tracker_event const*)>, __t=...) at …gcc…/g++-v15/bits/invoke.h:69
#14 0x0000555555b8e8c0 in std::__invoke_r<void, void (tr_torrent::*&)(tr_tracker_event const*), tr_torrent&, tr_tracker_event const*> (__fn=@0x7fffd4076e78: (void (tr_torrent::*)(tr_torrent * const, const tr_tracker_event *)) 0x555555b80c7e <tr_torrent::on_tracker_response(tr_tracker_event const*)>) at …gcc…/g++-v15/bits/invoke.h:113
#15 0x0000555555b8cf39 in std::_Function_handler<void(tr_torrent&, tr_tracker_event const*), void (tr_torrent::*)(tr_tracker_event const*)>::_M_invoke (__functor=..., __args#0=..., __args#1=@0x7fffe97f3c48: 0x7fffe97f3ce0) at …gcc…/g++-v15/bits/std_function.h:292
#16 0x0000555555975cf4 in std::function<void(tr_torrent&, tr_tracker_event const*)>::operator() (this=0x7fffd4076e78, __args#0=..., __args#1=0x7fffe97f3ce0) at …gcc…/g++-v15/bits/std_function.h:593
#17 0x00005555559683b3 in (anonymous namespace)::publish_helpers::publishPeersPex (tier=0x7fffd40558d0, pex=std::vector of length 1, capacity 1 = {...}) at …/libtransmission/announcer.cc:731
#18 0x000055555596abbe in tr_announcer_impl::onAnnounceDone (this=0x555555f89110, tier_id=0, event=TR_ANNOUNCE_EVENT_STARTED, is_running_on_success=true, response=...) at …/libtransmission/announcer.cc:1115
#19 0x000055555596cfa8 in operator() (__closure=0x7fffd468b070, response=...) at …/libtransmission/announcer.cc:1550
#20 0x0000555555970047 in std::__invoke_impl<void, (anonymous namespace)::upkeep_helpers::tierAnnounce(tr_announcer_impl*, tr_tier*)::<lambda(const tr_announce_response&)>&, const tr_announce_response&>(std::__invoke_other, struct {...} &) (__f=...) at …gcc…/g++-v15/bits/invoke.h:63
#21 0x000055555596f978 in std::__invoke_r<void, (anonymous namespace)::upkeep_helpers::tierAnnounce(tr_announcer_impl*, tr_tier*)::<lambda(const tr_announce_response&)>&, const tr_announce_response&>(struct {...} &) (__fn=...) at …gcc…/g++-v15/bits/invoke.h:113
#22 0x000055555596f242 in std::_Function_handler<void(const tr_announce_response&), (anonymous namespace)::upkeep_helpers::tierAnnounce(tr_announcer_impl*, tr_tier*)::<lambda(const tr_announce_response&)> >::_M_invoke(const std::_Any_data &, const tr_announce_response &) (__functor=..., __args#0=...) at …gcc…/g++-v15/bits/std_function.h:292
#23 0x00005555559509ff in std::function<void(tr_announce_response const&)>::operator() (this=0x7fffd5d82710, __args#0=...) at …gcc…/g++-v15/bits/std_function.h:593
#24 0x000055555594a917 in (anonymous namespace)::announce_helpers::onAnnounceDone (web_response=...) at …/libtransmission/announcer-http.cc:159
#25 0x0000555555955e56 in std::__invoke_impl<void, void (*&)(tr_web::FetchResponse const&), tr_web::FetchResponse const&> (__f=@0x7fffc816a5e0: 0x55555594a76d <(anonymous namespace)::announce_helpers::onAnnounceDone(tr_web::FetchResponse const&)>) at …gcc…/g++-v15/bits/invoke.h:63
#26 0x000055555595514c in std::__invoke_r<void, void (*&)(tr_web::FetchResponse const&), tr_web::FetchResponse const&> (__fn=@0x7fffc816a5e0: 0x55555594a76d <(anonymous namespace)::announce_helpers::onAnnounceDone(tr_web::FetchResponse const&)>) at …gcc…/g++-v15/bits/invoke.h:113
#27 0x00005555559534b8 in std::_Function_handler<void(tr_web::FetchResponse const&), void (*)(tr_web::FetchResponse const&)>::_M_invoke (__functor=..., __args#0=...) at …gcc…/g++-v15/bits/std_function.h:292
#28 0x0000555555932b71 in std::function<void(tr_web::FetchResponse const&)>::operator() (this=0x7fffc816a5e0, __args#0=...) at …gcc…/g++-v15/bits/std_function.h:593
#29 0x0000555555b36c85 in std::__invoke_impl<void, std::function<void(tr_web::FetchResponse const&)> const, tr_web::FetchResponse const> (__f=...) at …gcc…/g++-v15/bits/invoke.h:63
#30 0x0000555555b34a7a in std::__invoke<std::function<void(tr_web::FetchResponse const&)> const, tr_web::FetchResponse const> (__fn=...) at …gcc…/g++-v15/bits/invoke.h:98
#31 0x0000555555b31480 in std::__apply_impl<std::function<void(tr_web::FetchResponse const&)> const, std::tuple<tr_web::FetchResponse> const, 0ul> (__f=..., __t=...) at …gcc…/g++-v15/tuple:2920
#32 0x0000555555b314ba in std::apply<std::function<void(tr_web::FetchResponse const&)> const, std::tuple<tr_web::FetchResponse> const> (__f=..., __t=...) at …gcc…/g++-v15/tuple:2935
#33 0x0000555555b3143b in tr_session_thread::run<std::function<void (tr_web::FetchResponse const&)>, tr_web::FetchResponse>(std::function<void (tr_web::FetchResponse const&)>&&, tr_web::FetchResponse&&)::{lambda()#1}::operator()() const (__closure=0x7fffc816a5e0) at …/libtransmission/../libtransmission/session-thread.h:50
#34 0x0000555555b3af1e in std::__invoke_impl<void, tr_session_thread::run<std::function<void (tr_web::FetchResponse const&)>, tr_web::FetchResponse>(std::function<void (tr_web::FetchResponse const&)>&&, tr_web::FetchResponse&&)::{lambda()#1}&>(std::__invoke_other, tr_session_thread::run<std::function<void (tr_web::FetchResponse const&)>, tr_web::FetchResponse>(std::function<void (tr_web::FetchResponse const&)>&&, tr_web::FetchResponse&&)::{lambda()#1}&) (__f=...) at …gcc…/g++-v15/bits/invoke.h:63
#35 0x0000555555b38a51 in std::__invoke_r<void, tr_session_thread::run<std::function<void (tr_web::FetchResponse const&)>, tr_web::FetchResponse>(std::function<void (tr_web::FetchResponse const&)>&&, tr_web::FetchResponse&&)::{lambda()#1}&>(tr_session_thread::run<std::function<void (tr_web::FetchResponse const&)>, tr_web::FetchResponse>(std::function<void (tr_web::FetchResponse const&)>&&, tr_web::FetchResponse&&)::{lambda()#1}&) (__fn=...) at …gcc…/g++-v15/bits/invoke.h:113
#36 0x0000555555b36cf1 in std::_Function_handler<void (), tr_session_thread::run<std::function<void (tr_web::FetchResponse const&)>, tr_web::FetchResponse>(std::function<void (tr_web::FetchResponse const&)>&&, tr_web::FetchResponse&&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) (__functor=...) at …gcc…/g++-v15/bits/std_function.h:292
#37 0x0000555555834708 in std::function<void()>::operator() (this=0x7fffc80443e0) at …gcc…/g++-v15/bits/std_function.h:593
#38 0x0000555555b0f14d in tr_session_thread_impl::on_work_available (this=0x55555627ea70) at …/libtransmission/session-thread.cc:281
#39 0x0000555555b0f01a in tr_session_thread_impl::on_work_available_static (vself=0x55555627ea70) at …/libtransmission/session-thread.cc:266
#40 0x00007ffff7d1a538 in event_process_active_single_queue (base=base@entry=0x555555d47af0, activeq=0x5555561e2450, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0) at …libevent…/event.c:1691
#41 0x00007ffff7d1b1bf in event_process_active (base=0x555555d47af0) at …libevent…/event.c:1783
#42 event_base_loop (base=0x555555d47af0, flags=4) at …libevent…/event.c:2006
#43 0x0000555555b0ef34 in tr_session_thread_impl::session_thread_func (this=0x55555627ea70, evbase=0x555555d47af0) at …/libtransmission/session-thread.cc:253
#44 0x0000555555b12476 in std::__invoke_impl<void, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> (__f=@0x55555627eb58: (void (tr_session_thread_impl::*)(tr_session_thread_impl * const, event_base *)) 0x555555b0ee38 <tr_session_thread_impl::session_thread_func(event_base*)>, __t=@0x55555627eb50: 0x55555627ea70) at …gcc…/g++-v15/bits/invoke.h:76
#45 0x0000555555b123a2 in std::__invoke<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> (__fn=@0x55555627eb58: (void (tr_session_thread_impl::*)(tr_session_thread_impl * const, event_base *)) 0x555555b0ee38 <tr_session_thread_impl::session_thread_func(event_base*)>) at …gcc…/g++-v15/bits/invoke.h:98
#46 0x0000555555b122df in std::thread::_Invoker<std::tuple<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> >::_M_invoke<0ul, 1ul, 2ul> (this=0x55555627eb48) at …gcc…/g++-v15/bits/std_thread.h:303
#47 0x0000555555b1226a in std::thread::_Invoker<std::tuple<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> >::operator() (this=0x55555627eb48) at …gcc…/g++-v15/bits/std_thread.h:310
#48 0x0000555555b1222c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> > >::_M_run (this=0x55555627eb40) at …gcc…/g++-v15/bits/std_thread.h:255
#49 0x00007ffff52e78e4 in ?? () from …/libstdc++.so.6
#50 0x00007ffff4ea6a01 in start_thread (arg=<optimized out>) at pthread_create.c:448
#51 0x00007ffff4f3850c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 1 (Thread 0x7ffff5ca8cc0 (LWP 14688) "transmission-qt"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff52e2301 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) () from …/libstdc++.so.6
#2  0x00005555558a5af3 in std::__atomic_futex_unsigned<2147483648u>::_M_load_and_test_until (this=0x5555562f9220, __assumed=0, __operand=1, __equal=true, __mo=std::memory_order_acquire, __has_timeout=false, __s=std::chrono::duration = { 0s }, __ns=std::chrono::duration = { 0ns }) at …gcc…/g++-v15/bits/atomic_futex.h:111
#3  0x00005555558a4944 in std::__atomic_futex_unsigned<2147483648u>::_M_load_and_test (this=0x5555562f9220, __assumed=0, __operand=1, __equal=true, __mo=std::memory_order_acquire) at …gcc…/g++-v15/bits/atomic_futex.h:160
#4  0x000055555589f982 in std::__atomic_futex_unsigned<2147483648u>::_M_load_when_equal (this=0x5555562f9220, __val=1, __mo=std::memory_order_acquire) at …gcc…/g++-v15/bits/atomic_futex.h:218
#5  std::__future_base::_State_baseV2::wait (this=0x5555562f9210) at …gcc…/g++-v15/future:362
#6  0x0000555555a43f1e in std::__basic_future<void>::wait (this=0x7fffffffb860) at …gcc…/g++-v15/future:725
#7  0x0000555555a2548f in tr_peerMgrPeerStats (tor=0x7fffd40c4ff0, setme_count=0x7fffffffb950) at …/libtransmission/peer-mgr.cc:1971
#8  0x0000555555b7d6a2 in tr_torrentPeers (tor=0x7fffd40c4ff0, peer_count=0x7fffffffb950) at …/libtransmission/torrent.cc:1481
#9  0x0000555555af0e4a in (anonymous namespace)::make_torrent_field_helpers::make_peer_vec (tor=...) at …/libtransmission/rpcimpl.cc:434
#10 0x0000555555af29ea in (anonymous namespace)::make_torrent_field (tor=..., st=..., key=213) at …/libtransmission/rpcimpl.cc:638
#11 0x0000555555af327f in (anonymous namespace)::make_torrent_info_vec (tor=0x7fffd40c4ff0, fields=0x555555fc2530, field_count=19) at …/libtransmission/rpcimpl.cc:700
#12 0x0000555555af338c in (anonymous namespace)::make_torrent_info (tor=0x7fffd40c4ff0, format=(anonymous namespace)::TrFormat::Table, fields=0x555555fc2530, field_count=19) at …/libtransmission/rpcimpl.cc:712
#13 0x0000555555af3a0e in (anonymous namespace)::torrentGet (session=0x55555640cae0, args_in=..., args_out=...) at …/libtransmission/rpcimpl.cc:774
#14 0x0000555555afc36d in tr_rpc_request_exec (session=0x55555640cae0, request=..., callback=...) at …/libtransmission/rpcimpl.cc:2188
#15 0x00005555558e4da2 in RpcClient::sendLocalRequest (this=0x555555d45a28, req=std::shared_ptr<tr_variant> (use count 3, weak count 0) = {...}, promise=..., tag=10) at …/qt/RpcClient.cc:153
#16 0x00005555558e4f37 in RpcClient::sendRequest (this=0x555555d45a28, json=std::shared_ptr<tr_variant> (use count 3, weak count 0) = {...}) at …/qt/RpcClient.cc:185
#17 0x00005555558e3ce4 in RpcClient::exec (this=0x555555d45a28, method="torrent-get", args=0x7fffffffc430) at …/qt/RpcClient.cc:97
#18 0x00005555558e3bc7 in RpcClient::exec (this=0x555555d45a28, method=365, args=0x7fffffffc430) at …/qt/RpcClient.cc:76
#19 0x00005555558f2d7c in Session::exec (this=0x555555d45900, method=365, args=0x7fffffffc430) at …/qt/Session.cc:808
#20 0x00005555558f1e66 in operator() (__closure=0x7fffffffc320) at …/qt/Session.cc:661
#21 0x00005555558f7210 in operator() (__closure=0x7fffffffc320) at …/qt/RpcQueue.h:92
#22 0x00005555558fd55a in std::__invoke_impl<QFuture<RpcResponse>, RpcQueue::normalizeFunc<Session::refreshTorrents(const torrent_ids_t&, TorrentProperties)::<lambda()> >(const Session::refreshTorrents(const torrent_ids_t&, TorrentProperties)::<lambda()>&) const::<lambda(const RpcResponseFuture&)>&, const QFuture<RpcResponse>&>(std::__invoke_other, struct {...} &) (__f=...) at …gcc…/g++-v15/bits/invoke.h:63
#23 0x00005555558fb7fd in std::__invoke_r<QFuture<RpcResponse>, RpcQueue::normalizeFunc<Session::refreshTorrents(const torrent_ids_t&, TorrentProperties)::<lambda()> >(const Session::refreshTorrents(const torrent_ids_t&, TorrentProperties)::<lambda()>&) const::<lambda(const RpcResponseFuture&)>&, const QFuture<RpcResponse>&>(struct {...} &) (__fn=...) at …gcc…/g++-v15/bits/invoke.h:118
#24 0x00005555558f97b3 in std::_Function_handler<QFuture<RpcResponse>(const QFuture<RpcResponse>&), RpcQueue::normalizeFunc<Session::refreshTorrents(const torrent_ids_t&, TorrentProperties)::<lambda()> >(const Session::refreshTorrents(const torrent_ids_t&, TorrentProperties)::<lambda()>&) const::<lambda(const RpcResponseFuture&)> >::_M_invoke(const std::_Any_data &, const QFuture<RpcResponse> &) (__functor=..., __args#0=...) at …gcc…/g++-v15/bits/std_function.h:293
#25 0x00005555558edb13 in std::function<QFuture<RpcResponse>(QFuture<RpcResponse> const&)>::operator() (this=0x7fffffffc320, __args#0=...) at …gcc…/g++-v15/bits/std_function.h:593
#26 0x00005555558ed55e in RpcQueue::runNext (this=0x7fffec015970, response=...) at …/qt/RpcQueue.cc:70
#27 0x00005555558ed627 in RpcQueue::run (this=0x7fffec015970) at …/qt/RpcQueue.cc:75
#28 0x00005555558f20da in Session::refreshTorrents (this=0x555555d45900, torrent_ids=std::unordered_set with 1 element = {...}, props=Session::TorrentProperties::DetailStat) at …/qt/Session.cc:681
#29 0x00005555558f21be in Session::refreshExtraStats (this=0x555555d45900, ids=std::unordered_set with 1 element = {...}) at …/qt/Session.cc:691
#30 0x0000555555801e87 in DetailsDialog::refreshModel (this=0x5555561b1ef0) at …/qt/DetailsDialog.cc:342
#31 0x0000555555801c4c in DetailsDialog::setIds (this=0x5555561b1ef0, ids=std::unordered_set with 1 element = {...}) at …/qt/DetailsDialog.cc:314
#32 0x000055555587eb30 in MainWindow::openProperties (this=0x555555d6ccd0) at …/qt/MainWindow.cc:573
#33 0x000055555589a546 in QtPrivate::FunctorCall<std::integer_sequence<unsigned long>, QtPrivate::List<>, void, void (MainWindow::*)()>::call(void (MainWindow::*)(), MainWindow*, void**)::{lambda()#1}::operator()() const (__closure=0x7fffffffc5f0) at …qt…/QtCore/qobjectdefs_impl.h:127
#34 0x000055555589b912 in QtPrivate::FunctorCallBase::call_internal<void, QtPrivate::FunctorCall<std::integer_sequence<unsigned long>, QtPrivate::List<>, void, void (MainWindow::*)()>::call(void (MainWindow::*)(), MainWindow*, void**)::{lambda()#1}>(void**, QtPrivate::FunctorCall<std::integer_sequence<unsigned long>, QtPrivate::List<>, void, void (MainWindow::*)()>::call(void (MainWindow::*)(), MainWindow*, void**)::{lambda()#1}&&) (args=0x7fffffffc7e0, fn=...) at …qt…/QtCore/qobjectdefs_impl.h:65
#35 0x000055555589a5bc in QtPrivate::FunctorCall<std::integer_sequence<unsigned long>, QtPrivate::List<>, void, void (MainWindow::*)()>::call(void (MainWindow::*)(), MainWindow*, void**) (f=(void (MainWindow::*)(MainWindow * const)) 0x55555587ea9a <MainWindow::openProperties()>, o=0x555555d6ccd0, arg=0x7fffffffc7e0) at …qt…/QtCore/qobjectdefs_impl.h:126
#36 0x0000555555898de6 in QtPrivate::FunctionPointer<void (MainWindow::*)()>::call<QtPrivate::List<>, void>(void (MainWindow::*)(), MainWindow*, void**) (f=(void (MainWindow::*)(MainWindow * const)) 0x55555587ea9a <MainWindow::openProperties()>, o=0x555555d6ccd0, arg=0x7fffffffc7e0) at …qt…/QtCore/qobjectdefs_impl.h:174
#37 0x000055555589706d in QtPrivate::QCallableObject<void (MainWindow::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x555555dd28e0, r=0x555555d6ccd0, a=0x7fffffffc7e0, ret=0x0) at …qt…/QtCore/qobjectdefs_impl.h:545
#38 0x00007ffff599b88a in QtPrivate::QSlotObjectBase::call (this=0x555555dd28e0, r=<optimized out>, a=0x7fffffffc7e0) at …qtbase…/src/corelib/kernel/qobjectdefs_impl.h:461
#39 doActivate<false> (sender=0x555555d4bc20, signal_index=7, argv=argv@entry=0x7fffffffc7e0) at …qtbase…/src/corelib/kernel/qobject.cpp:4170
#40 0x00007ffff594b3a6 in QMetaObject::activate (sender=sender@entry=0x555555d4bc20, m=m@entry=0x7ffff67cbc60 <QAction::staticMetaObject>, local_signal_index=local_signal_index@entry=4, argv=argv@entry=0x7fffffffc7e0) at …qtbase…/src/corelib/kernel/qobject.cpp:4230
#41 0x00007ffff65069de in QMetaObject::activate<void, bool> (sender=0x555555d4bc20, mo=0x7ffff67cbc60 <QAction::staticMetaObject>, local_signal_index=4, ret=0x0) at …qtbase…/src/corelib/kernel/qobjectdefs.h:306
#42 QAction::triggered (this=<optimized out>, _t1=<optimized out>) at …qtbase…_build/src/gui/Gui_autogen/include/moc_qaction.cpp:372
#43 QAction::activate (this=0x555555d4bc20, event=<optimized out>) at …qtbase…/src/gui/kernel/qaction.cpp:1104
#44 0x0000555555887b31 in QAction::trigger (this=0x555555d4bc20) at …qt…/QtGui/qaction.h:210
#45 0x000055555589a716 in QtPrivate::FunctorCall<std::integer_sequence<unsigned long>, QtPrivate::List<>, void, void (QAction::*)()>::call(void (QAction::*)(), QAction*, void**)::{lambda()#1}::operator()() const (__closure=0x7fffffffc8b0) at …qt…/QtCore/qobjectdefs_impl.h:127
#46 0x000055555589ba2d in QtPrivate::FunctorCallBase::call_internal<void, QtPrivate::FunctorCall<std::integer_sequence<unsigned long>, QtPrivate::List<>, void, void (QAction::*)()>::call(void (QAction::*)(), QAction*, void**)::{lambda()#1}>(void**, QtPrivate::FunctorCall<std::integer_sequence<unsigned long>, QtPrivate::List<>, void, void (QAction::*)()>::call(void (QAction::*)(), QAction*, void**)::{lambda()#1}&&) (args=0x7fffffffcb60, fn=...) at …qt…/QtCore/qobjectdefs_impl.h:65
#47 0x000055555589a78c in QtPrivate::FunctorCall<std::integer_sequence<unsigned long>, QtPrivate::List<>, void, void (QAction::*)()>::call(void (QAction::*)(), QAction*, void**) (f=(void (QAction::*)(QAction * const)) 0x555555887b10 <QAction::trigger()>, o=0x555555d4bc20, arg=0x7fffffffcb60) at …qt…/QtCore/qobjectdefs_impl.h:126
#48 0x0000555555898ea2 in QtPrivate::FunctionPointer<void (QAction::*)()>::call<QtPrivate::List<>, void>(void (QAction::*)(), QAction*, void**) (f=(void (QAction::*)(QAction * const)) 0x555555887b10 <QAction::trigger()>, o=0x555555d4bc20, arg=0x7fffffffcb60) at …qt…/QtCore/qobjectdefs_impl.h:174
#49 0x00005555558972a1 in QtPrivate::QCallableObject<void (QAction::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x555555dd2a00, r=0x555555d4bc20, a=0x7fffffffcb60, ret=0x0) at …qt…/QtCore/qobjectdefs_impl.h:545
#50 0x00007ffff599b88a in QtPrivate::QSlotObjectBase::call (this=0x555555dd2a00, r=<optimized out>, a=0x7fffffffcb60) at …qtbase…/src/corelib/kernel/qobjectdefs_impl.h:461
#51 doActivate<false> (sender=0x555555d94c30, signal_index=10, argv=argv@entry=0x7fffffffcb60) at …qtbase…/src/corelib/kernel/qobject.cpp:4170
#52 0x00007ffff594b3a6 in QMetaObject::activate (sender=sender@entry=0x555555d94c30, m=m@entry=0x7ffff7436f60 <QAbstractItemView::staticMetaObject>, local_signal_index=local_signal_index@entry=3, argv=argv@entry=0x7fffffffcb60) at …qtbase…/src/corelib/kernel/qobject.cpp:4230
#53 0x00007ffff6f92e03 in QMetaObject::activate<void, QModelIndex> (sender=0x555555d94c30, mo=0x7ffff7436f60 <QAbstractItemView::staticMetaObject>, local_signal_index=3, ret=0x0) at …qtbase…/src/corelib/kernel/qobjectdefs.h:306
#54 QAbstractItemView::activated (this=0x555555d94c30, _t1=...) at …qtbase…_build/src/widgets/Widgets_autogen/include/moc_qabstractitemview.cpp:564
#55 QAbstractItemView::mouseDoubleClickEvent (this=0x555555d94c30, event=0x7fffffffd1a0) at …qtbase…/src/widgets/itemviews/qabstractitemview.cpp:2016
#56 0x00007ffff7294401 in QWidget::event (this=this@entry=0x555555d94c30, event=event@entry=0x7fffffffd1a0) at …qtbase…/src/widgets/kernel/qwidget.cpp:8999
#57 0x00007ffff70cb091 in QFrame::event (this=<optimized out>, e=<optimized out>) at …qtbase…/src/widgets/widgets/qframe.cpp:521
#58 QAbstractScrollArea::viewportEvent (this=<optimized out>, e=<optimized out>) at …qtbase…/src/widgets/widgets/qabstractscrollarea.cpp:1064
#59 0x00007ffff59b69ba in QCoreApplicationPrivate::sendThroughObjectEventFilters (receiver=receiver@entry=0x555555d6ead0, event=event@entry=0x7fffffffd1a0) at …qtbase…/src/corelib/kernel/qcoreapplication.cpp:1243
#60 0x00007ffff727e502 in QApplicationPrivate::notify_helper (this=this@entry=0x555555c8dd90, receiver=receiver@entry=0x555555d6ead0, e=e@entry=0x7fffffffd1a0) at …qtbase…/src/widgets/kernel/qapplication.cpp:3294
#61 0x00007ffff727f46b in QApplication::notify (this=<optimized out>, receiver=0x555555d6ead0, e=0x7fffffffd1a0) at …qtbase…/src/widgets/kernel/qapplication.cpp:2777
#62 0x00007ffff59b6c68 in QCoreApplication::notifyInternal2 (receiver=0x555555d6ead0, event=0x7fffffffd1a0) at …qtbase…/src/corelib/kernel/qcoreapplication.cpp:1106
#63 0x00007ffff59b6ffd in QCoreApplication::sendSpontaneousEvent (receiver=<optimized out>, event=<optimized out>) at …qtbase…/src/corelib/kernel/qcoreapplication.cpp:1560
#64 0x00007ffff728b963 in QApplicationPrivate::sendMouseEvent (receiver=receiver@entry=0x555555d6ead0, event=event@entry=0x7fffffffd1a0, alienWidget=<optimized out>, alienWidget@entry=0x555555d6ead0, nativeWidget=nativeWidget@entry=0x555555d6ccd0, buttonDown=buttonDown@entry=0x7ffff7478cb0 <qt_button_down>, lastMouseReceiver=..., spontaneous=true, onlyDispatchEnterLeave=false) at …qtbase…/src/widgets/kernel/qapplication.cpp:2358
#65 0x00007ffff728f31a in QWidgetWindow::handleMouseEvent (this=0x555555ddcd00, event=0x7fffffffd480) at …qtbase…/src/widgets/kernel/qwidgetwindow.cpp:683
#66 0x00007ffff7295f43 in QWidgetWindow::event (this=<optimized out>, event=<optimized out>) at …qtbase…/src/widgets/kernel/qwidgetwindow.cpp:292
#67 QWidgetWindow::event (this=<optimized out>, event=<optimized out>) at …qtbase…/src/widgets/kernel/qwidgetwindow.cpp:248
#68 0x00007ffff727e512 in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x555555ddcd00, e=0x7fffffffd480) at …qtbase…/src/widgets/kernel/qapplication.cpp:3300
#69 0x00007ffff59b6c68 in QCoreApplication::notifyInternal2 (receiver=0x555555ddcd00, event=0x7fffffffd480) at …qtbase…/src/corelib/kernel/qcoreapplication.cpp:1106
#70 0x00007ffff59b6ffd in QCoreApplication::sendSpontaneousEvent (receiver=<optimized out>, event=<optimized out>) at …qtbase…/src/corelib/kernel/qcoreapplication.cpp:1560
#71 0x00007ffff5fc0566 in QGuiApplicationPrivate::processMouseEvent (e=0x555555f2ade0) at …qtbase…/src/gui/kernel/qguiapplication.cpp:2516
#72 0x00007ffff603892b in QWindowSystemInterface::sendWindowSystemEvents (flags=flags@entry=...) at …qtbase…/src/gui/kernel/qwindowsysteminterface.cpp:1117
#73 0x00007ffff3fa046e in xcbSourceDispatch (source=<optimized out>) at …qtbase…/src/plugins/platforms/xcb/qxcbeventdispatcher.cpp:57
#74 0x00007ffff50eee53 in g_main_dispatch (context=context@entry=0x7fffec000f70) at ../glib-2.84.4/glib/gmain.c:3398
#75 0x00007ffff50f26a8 in g_main_context_dispatch_unlocked (context=0x7fffec000f70) at ../glib-2.84.4/glib/gmain.c:4249
#76 g_main_context_iterate_unlocked (context=context@entry=0x7fffec000f70, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib-2.84.4/glib/gmain.c:4314
#77 0x00007ffff50f3000 in g_main_context_iteration (context=0x7fffec000f70, may_block=1) at ../glib-2.84.4/glib/gmain.c:4379
#78 0x00007ffff56cf908 in QEventDispatcherGlib::processEvents (this=0x555555c9a410, flags=...) at …qtbase…/src/corelib/kernel/qeventdispatcher_glib.cpp:399
#79 0x00007ffff59f1396 in QEventLoop::processEvents (this=0x7fffffffd810, flags=...) at …qtbase…/src/corelib/kernel/qeventloop.cpp:104
#80 QEventLoop::exec (this=this@entry=0x7fffffffd810, flags=..., flags@entry=...) at …qtbase…/src/corelib/kernel/qeventloop.cpp:186
#81 0x00007ffff59f1770 in QCoreApplication::exec () at …qtbase…/src/corelib/kernel/qcoreapplication.cpp:1449
#82 0x0000555555873cbb in main (argc=1, argv=0x7fffffffdc88) at …/qt/main.cc:251
```

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

`main` (9b496350a9537e551120a1a5617622401568ac5b)

### PR DESCRIPTION
**Pull request by tearfur**
Fixes #6762
Fixes #7118
Fixes #7309
Fixes #7752
Regression from #5992.

Notes: Fixed `4.1.0-beta.1` bug where opening the Torrent Properties window while downloading would hang the Qt client.

This is (one of the possibilities of) how the hang manifests:

```mermaid
sequenceDiagram
    participant U as User
    participant M as Main Thread
    participant L as Session Lock<br/>std::unique_lock<std::recursive_mutex>
    participant S as Session Thread
    U->>M: Open Torrent Properties
    Note over M: Calls tr_rpc_request_exec()
    M->>L: Acquire Session Lock
    activate L
    L-->>M: Lock acquired
    Note over S: Receives block and calls<br/>tr_peerIo::can_read_wrapper()
    S-xL: Acquire Session Lock
    S->>S: Wait for Session Lock to release
    Note over M: Enter tr_peerMgrPeerStats() inside RPC callback
    M->>S: Queue function to get peer stats
    Note over S: Does not progress, still waiting for Session Lock,<br/>which in turn is still being held by Main Thread
    M->>M: Stuck waiting for Session Thread
    Note over U,S: Deadlock
    M-->>U: Application hangs
    deactivate L
```

With this fix, the diagram becomes (Scope of this PR highlighted in green):

```mermaid
sequenceDiagram
    participant U as User
    participant M as Main Thread
    participant L as Session Lock<br/>std::unique_lock<std::recursive_mutex>
    participant S as Session Thread
    U->>M: Open Torrent Properties
    Note over M: Calls tr_rpc_request_exec()
    M->>L: Acquire Session Lock
    activate L
    L-->>M: Lock acquired
    Note over S: Receives block and calls<br/>tr_peerIo::can_read_wrapper()
    S-xL: Acquire Session Lock
    S->>S: Wait for Session Lock to release
    Note over M: Enter tr_peerMgrPeerStats() inside RPC callback
    rect DarkGreen
    M->>L: Acquire Session Lock
    activate L
    L-->>M: Lock acquired
    Note over M: Does it's thing and return from<br/>tr_peerMgrPeerStats()
    M->>L: Release Session Lock
    L-->>M: Lock released
    deactivate L
    end
    Note over M: Return from tr_rpc_request_exec()
    M->>L: Release Session Lock
    L-->>M: Lock released
    deactivate L
    M-->>U: Display Torrent Properties content
    L-->>S: Lock acquired
    activate L
    Note over S: Does it's thing
    deactivate L
```

### CODE REVIEW

**Comment by reardonia** [comment]
funny enough, i have EXACTLY this patch running local, for months now.  revert #5992 together w torrent lock.  it's effectively a no-op in the daemon case, but I can at least confirm it runs properly in that scenario.

**Review by reardonia — APPROVED** [review]

**Review by nevack — APPROVED** [review]

**Comment by nevack** [comment]
Also should fix #6762

@tearfur Will you link it?

**Comment by dftf-stu** [comment]
Great to see this is getting sorted... so does this mean a 4.1.0-beta3 will go-out soon with this fix, or will this fix only go into the final 4.1.0 stable-release, and any subsequent betas will retain this issue?

If the answer to that is a 4.1.0-beta3 will be issued with this fix, then could I suggest issue 7629 be looked-at next please?

Currently this issue (Properties freezing) and 7629 (multiple instances of the app) are the two major reasons I cannot use the 4.1.0-beta builds, so it would be great if both could be fixed ahead of any new download.  Thanks

(I've reverted to 4.0.6, but I read that there was a bug where it spams trackers or something, so some will simply ignore it now?)

**Comment by tearfur** [comment]
> Also should fix #6762
> 
> @tearfur Will you link it?

Can someone test and verify if this is fixed?

**Review by Coeur — APPROVED** [review]
To summarise, the whole change is just 1 line addition of:
```
auto const lock = tor->unique_lock();
```

I did suggested multiple times that we should have reverted my changes in `tr_peerMgrPeerStats` way earlier, so I'm entirely OK with that.
I had made such revert more than a year ago in #6766.

(note: I'm still holding myself from doing any contributions to Transmission until someone fixes macOS support: #7499 in March 2025, superseded by #7573 in April 2025)

**Comment by Coeur** [comment]
Fix: https://github.com/transmission/transmission/issues/6762

**Comment by dftf-stu** [comment]
@Coeur: great if this is now fixed... but when will the fix go-out publicly, do you know?

In a comment near the start of this pull, it says "tearfur added this to the 4.1.0 milestone 2 weeks ago".
But the final, stable-release of 4.1.0 could be months, if not years, away yet.

Is there any possible chance a 4.1.0-beta3 might get pushed out with this fix, as currently users have a poor choice:
- Use the current stable 4.0.6, which many trackers now ban, due to the bug where it floods them with requests;
- Or use the current 4.1.0-beta2, which hangs when accessing torrent Properties, and opens multiple instances of the app;
- Or... switch to qBittorrent or Deluge (or other client), which I'm sure people here wouldn't want?

**Comment by tearfur** [comment]
> Fix: #6762

I'll take it that you have tested to verify that this PR fixes the issue. Please correct me if I'm wrong.

**Comment by tearfur** [comment]
@dftf-stu None of the people that spoke in this PR thus far have the final say or control over the release schedule, or which PR is to be merged when. The people that have the say is the core devs, and as you can tell they have been mostly inactive in this project.

Sad to say, I know as little as you regarding your concerns.

You best treat the milestone as merely a "suggestion" to the core devs. I add the PR to the milestone to indicate that this PR is important for the next release, but whether the core devs will honour it or not is another story.

**Comment by dftf-stu** [comment]
@tearfur: fair-enough... I wouldn't be sure who does what around here myself.

All I know is as an end-user the choice at the moment on the [download](https://transmissionbt.com/download) page is pretty-poor:
- transmission-4.0.6, which many public-trackers now block due to an issue where it spams them with requests, or;
- transmission-4.1.0-beta.2, which locks-up if you try to call-up the Properties dialog for any currently-active torrent, and also opens a new-instance of the app for every additional torrent or magnet added to it

So the choice is "stay on the current stable, but accept fewer trackers will acknowledge you, compared to Deluge, qBittorrent or other clients" or "use the current beta, but be sure to pause any torrent before going into the Properties.  Oh, and make-sure to right-click and do "Copy link" on any magnet, then manually add them from within the app, or you'll end up with more-than-one Transmission instance running and newer instances will be confused by all torrents that were active from prior instances". 🙃

Needless to say, as an end-user the fact a 4.0.7 hasn't been issued to fix that one tracker issue, and that such obvious bugs made it into 4.1.0-beta1 and still persist in 4.1.0-beta2, does suggest the people higher-up either don't care much, or don't seem to actually be using their own app... 🤔😥

**Comment by Coeur** [comment]
> > Fix: #6762
> 
> I'll take it that you have tested to verify that this PR fixes the issue. Please correct me if I'm wrong.

No, I did not test it since I did not reproduce the user issue. Just assumed based on my analysis.

**Comment by tearfur** [comment]
Both you and @nevack reached the same conclusion that this should fix #6762, so I'll trust you on it.

File: libtransmission/peer-mgr.cc [hunk 1]
```diff
@@ -1860,21 +1860,14 @@ tr_peer_stat* tr_peerMgrPeerStats(tr_torrent const* tor, size_t* setme_count)
     auto* const ret = new tr_peer_stat[n];
 
     // TODO: re-implement as a callback solution (similar to tr_sessionSetCompletenessCallback) in case present call to run_in_session_thread is causing hangs when the peers info window is displayed.
```
Comment (mikedld) [inline libtransmission/peer-mgr.cc]: Could this TODO (also added by #5992) be removed as well?

Comment (tearfur) [reply libtransmission/peer-mgr.cc]: a50cb9443e00808924cb6f701f88325f87c2f83f I suppose we can. The implementation by #5992 didn't introduce noticeable beachballing/jank (at least there weren't any bug reports for it), then AFAICT this PR wouldn't either.

**Comment by tedfelix** [comment]
This has been working great for me over the past week with fairly heavy use of the Properties dialog in Linux.  Definitely recommend a new beta release to get it in the hands of more testers.

**Comment by tearfur** [comment]
@tedfelix This is in the beta 3 release.
