### PR TITLE
fix: support dark mode colors with pieces bar on macOS

### LINKED ISSUE #6958: Pieces bar in dark mode is still white
### What is the issue?

Can the pieces bar be darkened in the dark UI? It makes perfect sense in light mode, but it's just blinding in dark mode.

image

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.6

### PR DESCRIPTION
**Pull request by nevack**
Fixes #6958

Screenshots:
Screenshot Regular
Screenshot Magnet

### CODE REVIEW

**Review by Coeur — APPROVED** [review]

File: macosx/ProgressBarView.mm [hunk 1]
```diff
@@ -183,7 +191,14 @@ - (void)drawPiecesBar:(NSRect)barRect forTorrent:(Torrent*)torrent
         }
         else
         {
-            pieceColor = [NSColor.whiteColor blendedColorWithFraction:piecesPercent[i] ofColor:self.fBluePieceColor];
+            if (NSApp.darkMode)
```
Comment (mikedld) [inline macosx/ProgressBarView.mm:194]: Since this is in a loop and condition result doesn't (shouldn't) change, please move out, e.g.
```objc++
NSColor* const pieceBgColor = NSApp.darkMode ? NSColor.controlColor : NSColor.whiteColor;

for (int i = 0; i < pieceCount; i++)
{
    ...
    pieceColor = [pieceBgColor blendedColorWithFraction:piecesPercent[i] ofColor:self.fBluePieceColor];
    ...
}
```

Comment (Coeur) [reply macosx/ProgressBarView.mm:194]: @nevack can you address it in order to get the fix merged?

Comment (nevack) [reply macosx/ProgressBarView.mm:194]: Yes, will do this soon with a rebase.
Thanks for bringing this up!

Comment (nevack) [reply macosx/ProgressBarView.mm]: Done

**Comment by nevack** [comment]
@ckerr Ready to merge
