### PR TITLE
fix: escaped representation of non-BMP characters when generating JSON

### LINKED ISSUE #1718: JSON encoding issue with unicode
I think the json encoding for unicode is broken on the RPC. For example with the emoji 👊 is encoded as `\u1f44a` instead of `\ud83d\udc4a`. The Surrogate seem to not be used.

When a client decode the json with this unicode, it will decode `\u1f44` instead of `\u1f44a`, so it return `ὄa` instead of `👊`. Tested with Javascript and PHP.

```javascript
JSON.parse('["\u1f44a"]');
> Array [ "ὄa" ]

JSON.parse('["\ud83d\udc4a"]');
> Array [ "👊" ]
```

Transmission 2.94

### PR DESCRIPTION
**Pull request by xavery**
Fixes #1718.

According to [ECMA 404](https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf) : 

> To escape a code point that is not in the Basic Multilingual Plane, the character may be represented as a twelve-character sequence, encoding the UTF-16 surrogate pair corresponding to the code point. So for example, a string containing only the G clef character (U+1D11E) may be represented as "\uD834\uDD1E".

This currently doesn't work correctly in Transmission, as it converts the internal UTF-8 representation of its strings to UTF-32 and appends the absolute code point value as the escaped `\u` token. This is incorrect, since the UTF-16 encoding is not equal to UTF-32 for characters outside the BMP due to UTF-16's usage of high and low surrogates to represent those.

All the necessary plumbing is already done by `utf8.h`, so the only changes necessary need to be made in `variant-json.cc` to make sure that two UTF-16 code units are output when producing JSON if necessary, and similarly that two UTF-16 code units are read when parsing.

### CODE REVIEW

**Comment by GaryElshaw** [comment]
I love little fixes like this.

File: tests/libtransmission/json-test.cc [hunk 1]
```diff
@@ -121,6 +121,27 @@ TEST_P(JSONTest, testUtf8)
     tr_variantClear(&top);
 }
 
+TEST_P(JSONTest, testUtf16Surrogates)
+{
+    constexpr auto thinking_face_emoji_utf8 = "\xf0\x9f\xa4\x94"sv;
+    tr_variant top;
```
Comment (ckerr) [inline tests/libtransmission/json-test.cc:127]: Please AAA

```suggestion
    auto top = tr_variant{};
```

File: tests/libtransmission/json-test.cc [hunk 2]
```diff
@@ -121,6 +121,27 @@ TEST_P(JSONTest, testUtf8)
...
+    tr_variantInitDict(&top, 1);
+    tr_quark const key = tr_quark_new("key"sv);
```
Comment (ckerr) [inline tests/libtransmission/json-test.cc:129]: Please AAA

```suggestion
    auto const key = tr_quark_new("key"sv);
```

File: tests/libtransmission/json-test.cc [hunk 3]
```diff
@@ -121,6 +121,27 @@ TEST_P(JSONTest, testUtf8)
...
+    tr_variantDictAddStr(&top, key, thinking_face_emoji_utf8);
+    auto json = tr_variantToStr(&top, TR_VARIANT_FMT_JSON_LEAN);
```
Comment (ckerr) [inline tests/libtransmission/json-test.cc:131]: can be const

```suggestion
    auto const json = tr_variantToStr(&top, TR_VARIANT_FMT_JSON_LEAN);
```

File: tests/libtransmission/json-test.cc [hunk 4]
```diff
@@ -121,6 +121,27 @@ TEST_P(JSONTest, testUtf8)
...
+    EXPECT_NE(std::string::npos, json.find("ud83e"));
+    EXPECT_NE(std::string::npos, json.find("udd14"));
+    tr_variantClear(&top);
+
+    tr_variant parsed;
```
Comment (ckerr) [inline tests/libtransmission/json-test.cc:136]: Please AAA

```suggestion
    auto parsed = tr_variant{};
```

File: tests/libtransmission/json-test.cc [hunk 5]
```diff
@@ -121,6 +121,27 @@ TEST_P(JSONTest, testUtf8)
...
+    EXPECT_TRUE(tr_variantFromBuf(&parsed, TR_VARIANT_PARSE_JSON | TR_VARIANT_PARSE_INPLACE, json));
+    EXPECT_TRUE(tr_variantIsDict(&parsed));
+    std::string_view value;
```
Comment (ckerr) [inline tests/libtransmission/json-test.cc:139]: Please AAA

```suggestion
    auto value = std::string_view{};
```

File: libtransmission/variant-json.cc [hunk 6]
```diff
@@ -165,10 +165,50 @@ void action_callback_PUSH(jsonsl_t jsn, jsonsl_action_t /*action*/, struct jsons
...
 
-    *setme = val;
+    setme = val;
     return true;
 }
 
+template<typename Iter>
+void decode_single_uchar(char const*& in, char const* const in_end, Iter& buf16_out_it)
+{
+    constexpr unsigned escaped_uchar_length = 6;
```
Comment (ckerr) [inline libtransmission/variant-json.cc:175]: Please follow .clang-tidy rule `{ key: readability-identifier-naming.ConstexprVariableCase,    value: CamelCase  }`

```suggestion
    static auto constexpr EscapedUcharLength = 6U;
```

File: libtransmission/variant-json.cc [hunk 7]
```diff
@@ -165,10 +165,50 @@ void action_callback_PUSH(jsonsl_t jsn, jsonsl_action_t /*action*/, struct jsons
...
+        catch (utf8::exception const&) // invalid codepoint
+        {
+            buf.push_back('?');
+        }
+        return true;
+    }
+    else
+    {
+        return false;
+    }
```
Comment (ckerr) [inline libtransmission/variant-json.cc:209]: we can reduce the nesting depth by 1 if we switch the order here, e.g.

```
if (buf16_out_it == std::begin(buf16))
{
    return false;
}

// try-catch here...
return true;
```

File: tests/libtransmission/json-test.cc [hunk 8]
```diff
@@ -121,6 +121,27 @@ TEST_P(JSONTest, testUtf8)
     tr_variantClear(&top);
 }
 
+TEST_P(JSONTest, testUtf16Surrogates)
+{
+    constexpr auto thinking_face_emoji_utf8 = "\xf0\x9f\xa4\x94"sv;
```
Comment (ckerr) [inline tests/libtransmission/json-test.cc:126]: Please follow .clang-tidy rule `{ key: readability-identifier-naming.ConstexprVariableCase,    value: CamelCase  }`

```suggestion
    static auto constexpr ThinkingFaceEmojiUtf8 = "\xf0\x9f\xa4\x94"sv;
```

**Review by ckerr — CHANGES_REQUESTED** [review]
Several style nits but nothing structural -- this is nice work; thanks for the patch @xavery!

**Comment by ckerr** [comment]
@xavery does this fix #1718?

Notes: Fixed incorrect escaping of non-BMP characters when generating JSON.

**Comment by ckerr** [comment]
> I love little fixes like this.

Agreed. Well explained, adds a test to confirm the fix, reasonable code :tada:

**Comment by xavery** [comment]
> @xavery does this fix #1718?
> 
> Notes: Fixed incorrect escaping of non-BMP characters when generating JSON.

Yes, this is exactly the same issue. I just encountered it while investigating another bug in transgui, and didn't look in Transmission's own list.

**Review by ckerr — APPROVED** [review]
