### PR TITLE
fix: json string serializer improperly escaping characters

### LINKED ISSUE #5967: Transmission cannot process some Unicode names
### What is the issue?

For example text "Дыскаграфія" cannot be displayed correctly. In Qt client and in browser it is displayed as "Ды�?каг�?афі�?".

In JSON it looks like `Ð\u0094Ñ\u008bÑ?ÐºÐ°Ð³Ñ?Ð°Ñ\u0084Ñ\u0096Ñ?`

Client: Linux 4.0.3, Windows 4.0.4, Browser (Any)
Server: Windows 7 (4.0.4)

### PR DESCRIPTION
**Pull request by tearfur**
Fixes #5967.

This PR fixes 3 problems:

1. It is escaping characters that does not need to be escaped (e.g. non-BMP characters), which in turn:
   1. Makes the JSON object unnecessarily long.
   2. Gives more room for error because of extra code to escape stuff.
2. It decides which characters to escape using `isprint()`, which gives different output depending on locale. This is causing Transmission to improperly escaping strings in some locales.
3. The JSON tests were not following the locale settings of the apps, so locale issues were being swept under the rug.

JSON strings can contain *any* Unicode characters (with a few well-defined exceptions), so escaping non-BMP characters is optional. This PR modifies Transmsision to do as little escaping as possible.

> All Unicode characters may be placed within the quotation marks, except for the characters that MUST be escaped: quotation mark, reverse solidus, and the control characters (U+0000 through U+001F).

To be as compatible as possible with other applications, we should be sticking to UTF-8. We shoudn't have to worry about that, since the BT protocol is all in UTF-8 by definition. But to be safe, I have added a `tr_strv_convert_utf8()` call when serializing strings to JSON.

> JSON text exchanged between systems that are not part of a closed ecosystem MUST be encoded using UTF-8 [[RFC3629](https://datatracker.ietf.org/doc/html/rfc3629)].

*The quotes are from https://datatracker.ietf.org/doc/html/rfc8259#section-7*

Related PRs:
- #5444
- #5096

Notes: Fixed a bug where Transmission is incorrectly escaping JSON strings in some locales.

### CODE REVIEW

**Comment by tearfur** [comment]
CC @xavery

File: tests/libtransmission/json-test.cc [hunk 1]
```diff
@@ -127,32 +118,19 @@ TEST_P(JSONTest, testUtf8)
...
+    EXPECT_EQ(R"({"key":"Letöltések"})"sv, json);
     var = serde.parse(json).value_or(tr_variant{});
     EXPECT_TRUE(var.holds_alternative<tr_variant::Map>());
     EXPECT_TRUE(tr_variantDictFindStrView(&var, key, &sv));
     EXPECT_EQ("Letöltések"sv, sv);
-}
-
-TEST_P(JSONTest, testUtf16Surrogates)
-{
-    static auto constexpr ThinkingFaceEmojiUtf8 = "\xf0\x9f\xa4\x94"sv;
```
Comment (Coeur) [inline tests/libtransmission/json-test.cc:140]: Shouldn't we keep three lines of test for `"\xf0\x9f\xa4\x94"sv`? Just to assert that we're not having regressions here:
```
     tr_variantDictAddStr(&var, key, "\xf0\x9f\xa4\x94"sv);
     json = serde.to_string(var);
     EXPECT_EQ(R"({"key":"SOMETHING..."})"sv, json);
```

Comment (tearfur) [reply tests/libtransmission/json-test.cc:140]: I can incorporate this string in `testUtf8` too, sure.

**Comment by ckerr** [comment]
@tearfur Is this a 4.0.x change, or 4.1.0?

**Comment by tearfur** [comment]
@ckerr Ideally 4.0.x.

The fixes to the tests are not backwards-compatible, since it uses the new `tr_variant` serde API. But this shouldn't be difficult to manually backport.

File: tests/libtransmission/json-test.cc (hunk 1 above)
Comment (tearfur) [reply tests/libtransmission/json-test.cc:140]: 7ea2fac

File: libtransmission/variant-json.cc [hunk 2]
```diff
@@ -569,41 +569,36 @@ void jsonRealFunc(tr_variant const& /*var*/, double const val, void* vdata)
...
     {
-        switch (sv.front())
+        switch (utf8_sv.front())
         {
+        case '\\':
+            *walk++ = '\\';
+            *walk++ = '\\';
+            break;
+
+        case '"':
```
Comment (Coeur) [inline libtransmission/variant-json.cc:597]: nit: that reordering is not needed for the fix.
But if you're trying to have it in ASCII order of the resulting string, then `"` should be before `\`, while if you're trying to have in in ASCII order of the escape sequence, then it should be `\b`, `\t`, `\n`, `\f`, `\r`.

Comment (tearfur) [reply libtransmission/variant-json.cc:597]: The list of valid escape sequences was listed in this order in the RFC document.

Comment (Coeur) [reply libtransmission/variant-json.cc:597]:
```
              %x22 /          ; "    quotation mark  U+0022
              %x5C /          ; \    reverse solidus U+005C
              %x2F /          ; /    solidus         U+002F
              %x62 /          ; b    backspace       U+0008
              %x66 /          ; f    form feed       U+000C
              %x6E /          ; n    line feed       U+000A
              %x72 /          ; r    carriage return U+000D
              %x74 /          ; t    tab             U+0009
```
Straight from the RFC: https://datatracker.ietf.org/doc/html/rfc8259

Comment (tearfur) [reply libtransmission/variant-json.cc:597]: Damn I must've been blind.

Comment (tearfur) [reply libtransmission/variant-json.cc]: deee3f3

**Comment by xavery** [comment]
When working on #5096 , I was surprised to find out that Transmission does the non-BMP escape thing anyway, especially since the charset is explicitly set to utf-8 in the `Content-Type`. I didn't want to introduce a change that wasn't strictly needed so I just kept the escaping as-is.

However, I do agree that this is how this should've been handled from the beginning : just write out the UTF-8 encoded characters. To be fair, there's probably more bugs in client software related to unescaping UTF-16 surrogate pairs than there is in parsing UTF-8.

In fact, this means that one of the reasons why I started my own fork of transgui is now nullified, as it was related exactly to handling escaped UTF-16 surrogate pairs in JSON. This is, of course, a good thing.

**Review by Coeur — APPROVED** [review]

**Comment by ckerr** [comment]
> Are we going to do 4.0.5 though?

It feels like each 4.0.x release gets fewer bug reports, so it might not be necessary. But who knows. It wasn't clear that `4.0.4` would be released either. :man_shrugging:

**Comment by ckerr** [comment]
DragonFlyBSD CI keeps [failing](https://trtc.mikedld.com/buildConfiguration/Transmission_Sanity_DragonFlyBSDX8664/379330?buildTab=log&focusLine=0&linesState=2335.11420.11423&logView=flowAware) with this:

> 09:49:30     Failed to parse 12 reports
09:49:30     _build/tests/libtransmission/libtransmission-test_371.xml: Invalid byte 2 of 2-byte UTF-8 sequence.
09:49:30     _build/tests/libtransmission/libtransmission-test_359.xml: Invalid byte 2 of 2-byte UTF-8 sequence.
09:49:30     _build/tests/libtransmission/libtransmission-test_352.xml: Invalid byte 2 of 2-byte UTF-8 sequence.
09:49:30     _build/tests/libtransmission/libtransmission-test_364.xml: Invalid byte 2 of 2-byte UTF-8 sequence.
09:49:30     _build/tests/libtransmission/libtransmission-test_372.xml: Invalid byte 2 of 2-byte UTF-8 sequence.
09:49:30     _build/tests/libtransmission/libtransmission-test_360.xml: Invalid byte 2 of 2-byte UTF-8 sequence.
09:49:30     _build/tests/libtransmission/libtransmission-test_363.xml: Invalid byte 2 of 2-byte UTF-8 sequence.
09:49:30     _build/tests/libtransmission/libtransmission-test_351.xml: Invalid byte 2 of 2-byte UTF-8 sequence.
09:49:30     _build/tests/libtransmission/libtransmission-test_367.xml: Invalid byte 2 of 2-byte UTF-8 sequence.
09:49:30     _build/tests/libtransmission/libtransmission-test_368.xml: Invalid byte 2 of 2-byte UTF-8 sequence.
09:49:30     _build/tests/libtransmission/libtransmission-test_356.xml: Invalid byte 2 of 2-byte UTF-8 sequence.
09:49:30     _build/tests/libtransmission/libtransmission-test_355.xml: Invalid byte 2 of 2-byte UTF-8 sequence.
09:49:35   Failed to parse xml reports

This seems like it would be related to the changes in the PR; but when I try to confirm by [opening a terminal](https://trtc.mikedld.com/plugins/teamcity-agent-terminal/agentTerminal.html?agentId=44) to the DragonFlyBSD agent to read transmission-test_3xx.xml, I just get a blank screen :confused:

**Comment by tearfur** [comment]
> It feels like each 4.0.x release gets fewer bug reports, so it might not be necessary.

I'm kinda conflicted.

On one hand, it's getting harder and harder to backport changes as more and more of the core code is getting facelifts.

On the other hand, there are a bunch of long-standing bug reports that are quite disruptive to the user, but at the same time very elusive. One interesting thing I noticed is the vast majority of those reports are from Mac. Not sure if our userbase is just dominated by Mac users or there really is something wrong only on Mac.

**Comment by ckerr** [comment]
I'm not sure what to do about this. The fix looks correct, but for whatever reason the TeamCity CI is failing to parse the XML for tests that intentionally include invalid UTF-8. The obvious inference is that those invalid strings are getting logged in the test xml files but I'm not seeing this when I try to reproduce the issue locally.

@mikedld do you have any idea how to make progress on this?

**Comment by GaryElshaw** [comment]
Off-topic: I just noticed in the TC footer that the license expires in 10 days.

**Comment by ckerr** [comment]
> Off-topic: I just noticed in the TC footer that the license expires in 10 days.

^ @mikedld

**Comment by GaryElshaw** [comment]
Mike's sorted it.

**Comment by tearfur** [comment]
@ckerr Anything I can do to progress this PR?

**Comment by ckerr** [comment]
> @ckerr Anything I can do to progress this PR?

I still don't understand the issue but maybe these screenshots @mikedld took of the invalid XML will help us to figure out what's going on:

imagen_720

--- 

imagen_720

---

imagen_720

File: tests/libtransmission/json-test.cc [hunk 3]
```diff
@@ -24,27 +25,18 @@ class JSONTest : public ::testing::TestWithParam<char const*>
 protected:
     void SetUp() override
     {
+        ::testing::TestWithParam<char const*>::SetUp();
+
         auto const* locale_str = GetParam();
         try
         {
-            old_locale_ = std::locale::global(std::locale{ {}, new std::numpunct_byname<char>{ locale_str } });
+            tr_locale_set_global(locale_str);
```
Comment (mikedld) [inline tests/libtransmission/json-test.cc:33]: Not sure why these changes in `SetUp()` and `TearDown()` were necessary, but I'd start from rolling them back and seeing if it helps.

Comment (mikedld) [reply tests/libtransmission/json-test.cc:33]: I see, the util function does a bit more than changing numpunct locale. Still it'd be nice to restore the old locale in `TearDown()` so that the other tests (and apparently GTest) aren't affected.

Comment (tearfur) [reply tests/libtransmission/json-test.cc]: 041faba Thanks, finally got the CI green.

Comment (ckerr) [reply tests/libtransmission/json-test.cc]: @mikedld thank you, nice work!
