### PR TITLE
Fix deleting previously selected torrent when trying to clear search field using Command + Delete

### LINKED ISSUE #3599: Trying to clear search field using Command + Delete on search field (on macOS) deletes previously selected torrent
1. Use search field to find a few torrents
2. Select One of the torrents (to see some of its metadata for instance)
3. Select the search field to search for a new torrent
4. Press Command + Delete to clear the search field of its content
-> Transmission suggests deleting the torrent, which is a bug as the search field was selected, but for some torrents that are "problematic" (file not available due to disconnected external hard drive for instance), there is no confirmation window, torrent is immediately deleted.

### PR DESCRIPTION
**Pull request by subdan**
Fixes #3599

### CODE REVIEW

File: macosx/Controller.mm [hunk 1]
```diff
@@ -4772,6 +4772,11 @@ - (BOOL)validateMenuItem:(NSMenuItem*)menuItem
     {
         BOOL warning = NO;
 
+        if (self.fFilterBar.isFocused == NO)
```
Comment (Coeur) [inline macosx/Controller.mm:4775]: This disables the delete action whether the search field is focused or not.

**Review by Coeur — CHANGES_REQUESTED** [review]
Thanks for the initial attempt, but it causes a regression: cmd+delete will stop working even after selecting a row explicitly.

File: macosx/Controller.mm (hunk 1 above)
Comment (subdan) [reply macosx/Controller.mm]: > Thanks for the initial attempt, but it causes a regression: cmd+delete will stop working even after selecting a row explicitly.

Sorry. Fixed.

File: macosx/FilterBarController.mm [hunk 2]
```diff
@@ -266,7 +266,9 @@ - (void)focusSearchField
 
 - (BOOL)isFocused
 {
-    return self.fSearchField.window.firstResponder == self.fSearchField;
+    return ([[[self.fSearchField window] firstResponder] isKindOfClass:[NSTextView class]] &&
+            [[self.fSearchField window] fieldEditor:NO forObject:nil] != nil &&
+            [self.fSearchField isEqualTo:(id)[(NSTextView *)[[self.fSearchField window] firstResponder]delegate]]);
```
Comment (Coeur) [inline macosx/FilterBarController.mm:271]: nit:
- Prefer a space between `]` and `delegate` for consistency with all the objective-c code in the project.
- Prefer avoiding casting to `(id)`.
- Superfluous parenthesis.

ie:
```
    return [[[self.fSearchField window] firstResponder] isKindOfClass:[NSTextView class]] &&
        [[self.fSearchField window] fieldEditor:NO forObject:nil] != nil &&
        [self.fSearchField isEqualTo:[(NSTextView*)[[self.fSearchField window] firstResponder] delegate]];
```

**Review by Coeur — APPROVED** [review]
thanks: reviewed and tested; just style could be improved slightly

File: macosx/FilterBarController.mm (hunk 2 above)
Comment (subdan) [reply macosx/FilterBarController.mm:271]: Thanks for review. Fixed it.

**Comment by Coeur** [comment]
@ckerr I already approved the change

**Review by Coeur — APPROVED** [review]

File: macosx/FilterBarController.mm (hunk 2 above)
Comment (subdan) [reply macosx/FilterBarController.mm]: Do I need to fix code style again because [code-style](https://github.com/transmission/transmission/actions/runs/3559715798/jobs/5979254141) check didn’t pass.

**Comment by ckerr** [comment]
This PR needs a quick style change to make the bots happy:

@subdan need a minor style change to make the bot happy:

```
Run echo "code style does not match expected."
code style does not match expected.
diff --git a/macosx/FilterBarController.mm b/macosx/FilterBarController.mm
index 45c21cd..e510706 100644
--- a/macosx/FilterBarController.mm
+++ b/macosx/FilterBarController.mm
@@ -268,8 +268,7 @@ typedef NS_ENUM(NSInteger, FilterTypeTag) {
 {
     NSTextView* textView = (NSTextView*)self.fSearchField.window.firstResponder;
     return [self.fSearchField.window.firstResponder isKindOfClass:NSTextView.class] &&
-           [self.fSearchField.window fieldEditor:NO forObject:nil] != nil &&
-           [self.fSearchField isEqualTo:textView.delegate];
+        [self.fSearchField.window fieldEditor:NO forObject:nil] != nil && [self.fSearchField isEqualTo:textView.delegate];
 }
 
 - (void)searchFieldDidStartSearching:(NSSearchField*)sender
When CI is done, the above patch will be uploaded as 'code-style.diff' to https://github.com/transmission/transmission/actions/runs/355[9](https://github.com/transmission/transmission/actions/runs/3559715798/jobs/5979254141#step:7:10)7[15](https://github.com/transmission/transmission/actions/runs/3559715798/jobs/5979254141#step:7:16)798/ .
```

https://github.com/transmission/transmission/actions/runs/3559715798/

File: macosx/FilterBarController.mm (hunk 2 above)
Comment (ckerr) [reply macosx/FilterBarController.mm]: I pushed an update for code-style, so no worries

**Comment by Coeur** [comment]
Notes: Fixed deleting previously selected torrent when attempting to clear search field using ⌘⌫.
