### PR TITLE
fix: appendSanitizedComponent is too aggressive on non-WIN32 (and not enough aggressive on WIN32)

### LINKED ISSUE #5112: Only 99.97% verified after creating then verifying large (~500 GB) folder
### What is the issue?

I'm trying to create a torrent file of a full disk backup that I have in a folder, then seed it so I can sync it to another remote computer reliably. However, I keep running into an issue where Transmission will not verify the local content fully, after creating the torrent file, and then immediately verify it.

The folder in question is approximately 500 GB of varied content (including other folders etc.), and the torrent file creation runs without issues. I then add the torrent file so I can start seeding, and the local content is verified, but only up until 99.97% or so. Looking at what has been verified, random little files are just not found, and I see no pattern in the kind of file.

I've tried this with several different folders ranging from ~300 GB to ~700 GB, and the same thing always happens. I also tried creating the torrent file with mktorrent instead, and the result was the same. It seems like something goes wrong with how Transmission verifies local data. I've tried with both Transmission 3.0.0 stable and 4.0.1 stable.

I really wish I could get this working, as there aren't really many good ways to sync hundreds of gigabytes over the Internet with intermittent access and varying speeds. The beauty of using torrent for this is that I know I will eventually end up with the correct data, exactly because of the checksumming.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1

### PR DESCRIPTION
**Pull request by Coeur**
fix #5112

The current sanitation is (partially) only valid for Windows and is too aggressive for Linux/Apple, losing correct filenames.

- leading and trailing spaces are valid on Unix-like
- trailing dots are valid on Unix-like
- no reserved filenames on Unix-like except "." and ".."
- control chars are reserved on Win32

Testing:
1. make files or folders with such characteristics (like leading space, trailing space, quotes, slashes, backslashes, ...
2. `transmission-create <that file>`
3. `transmission-show <the generated torrent>`

tip: to create files with control characters:
```
date > "$(printf "foo\tbar")"
date > "$(printf "foo\nbar")"
```
This will create two distinct files.

### CODE REVIEW

File: libtransmission/torrent-files.cc [hunk 1]
```diff
@@ -361,15 +366,17 @@ namespace
 {
     switch (ch)
     {
+    case ':':
+#if !defined(__APPLE__) // only ':' is reserved on APFS
```
Comment (nevack) [inline libtransmission/torrent-files.cc:370]: What about HFS?

**Comment by ckerr** [comment]
Related: https://github.com/transmission/transmission/pull/3823

File: libtransmission/torrent-files.cc [hunk 2]
```diff
@@ -361,15 +366,17 @@ namespace
...
     case '"':
     case '*':
     case '/':
```
Comment (nevack) [inline libtransmission/torrent-files.cc:373]: I'm confident that this one is reserved.

Comment (Coeur) [reply libtransmission/torrent-files.cc]: I've updated the PR

**Comment by Coeur** [comment]
> Related: #3823

Ah, woah, more than 1 year old.
Well, it's time to look at both PR (the one old and mine) and figure out what is good to merge.
I'll update the tests like that old one did.

File: libtransmission/torrent-files.cc (hunk 1 above)
Comment (Coeur) [reply libtransmission/torrent-files.cc]: Same. While not an official source, we have:
https://www.reddit.com/r/MacOS/comments/rvilz7/reserved_file_names/
>The maximum filename length for HFS+ and APFS is 255 UTF-8 characters, and the reserved characters of HFS+ and APFS are /, :, CR (Carriage Return) and LF (Line Feed).

I've addressed CR and LF in the `> 31` catch-all for all control characters.

File: libtransmission/torrent-files.cc [hunk 3]
```diff
@@ -322,7 +322,11 @@ namespace
 
     // Shortcut to avoid extra work below.
     // All the paths below involve filenames that begin with one of these chars
+#if defined(_WIN32) || defined(_WIN64)
     static auto constexpr ReservedFilesBeginWithOneOf = "ACLNP"sv;
+#else
+    static auto constexpr ReservedFilesBeginWithOneOf = "."sv;
```
Comment (nevack) [inline libtransmission/torrent-files.cc:328]: Why thou?
In POSIX `.` at the beginning just marks file as hidden, but name is still valid.

File: libtransmission/torrent-files.cc [hunk 4]
```diff
@@ -332,16 +336,24 @@ namespace
     std::transform(std::begin(in_upper), std::end(in_upper), std::begin(in_upper), [](auto ch) { return toupper(ch); });
     auto const in_upper_sv = in_upper.sv();
 
+#if defined(_WIN32) || defined(_WIN64)
     static auto constexpr ReservedNames = std::array<std::string_view, 22>{
         "AUX"sv,  "CON"sv,  "NUL"sv,  "PRN"sv, //
         "COM1"sv, "COM2"sv, "COM3"sv, "COM4"sv, "COM5"sv, "COM6"sv, "COM7"sv, "COM8"sv, "COM9"sv, //
         "LPT1"sv, "LPT2"sv, "LPT3"sv, "LPT4"sv, "LPT5"sv, "LPT6"sv, "LPT7"sv, "LPT8"sv, "LPT9"sv, //
     };
+#else
```
Comment (nevack) [inline libtransmission/torrent-files.cc:345]: I don't have a Windows machine to test, but I think `.` and `..` mean the same as POSIx there.

File: libtransmission/torrent-files.cc [hunk 5]
```diff
@@ -361,23 +376,26 @@ namespace
 {
     switch (ch)
     {
+    case ':':
+    case '/':
+#if !defined(__APPLE__) // only ':' and '/' are reserved on APFS
```
Comment (nevack) [inline libtransmission/torrent-files.cc:381]: This is also not true on modern Apple filesystems. At least on APFS, cannot test HFS+
`:` was reserved on classic MacOS, before  Mac OS X.

```sh
$ echo LOL > 'foo:bar'
$ cat 'foo:bar'
LOL
```

File: libtransmission/torrent-files.cc (hunk 3 above)
Comment (Coeur) [reply libtransmission/torrent-files.cc:328]: It's to reserve two specific names: "." and "..". Not all of those starting with ".".

File: libtransmission/torrent-files.cc (hunk 4 above)
Comment (Coeur) [reply libtransmission/torrent-files.cc:345]: All trailing dots are removed on Windows, from previous method `appendSanitizedComponent`

File: libtransmission/torrent-files.cc (hunk 5 above)
Comment (Coeur) [reply libtransmission/torrent-files.cc:381]: Well, it displays itself as '/' in Finder. So in Finder you can use `/`, in Terminal you can use `:` ... but they are the same character.
I can try to save it...

File: tests/libtransmission/torrent-files-test.cc [hunk 6]
```diff
@@ -144,23 +144,45 @@ TEST_F(TorrentFilesTest, hasAnyLocalData)
 TEST_F(TorrentFilesTest, isSubpathPortable)
 {
     static auto constexpr Tests = std::array<std::pair<std::string_view, bool>, 15>{ {
```
Comment (nevack) [inline tests/libtransmission/torrent-files-test.cc:146]: nit: Maybe it would be easier to define
```c
TEST_F(TorrentFilesTest, isSubpathPortable)
{
#ifdef __APPLE__
#define RESERVED_NOT_APPLE true
#else
#define RESERVED_NOT_APPLE false
#endif
    static auto constexpr Tests = std::array<std::pair<std::string_view, bool>, 15>{ {
        // don't end with periods
        { "foo.", RESERVED_NOT_APPLE },
        { "foo..", RESERVED_NOT_APPLE },
        ...
    } };
#undef __APPLE__

```
and just use that instead of `true`/`false` here.

**Review by nevack — APPROVED** [review]
LGTM

File: libtransmission/torrent-files.cc (hunk 5 above)
Comment (nevack) [reply libtransmission/torrent-files.cc]: I won't really mind sanitizing `:` too, just shared my observations.
And yeah, Finder is confusing things here.

File: tests/libtransmission/torrent-files-test.cc (hunk 6 above)
Comment (Coeur) [reply tests/libtransmission/torrent-files-test.cc:146]: I figured out that all the Apple rules are identical to Linux rules.
So yes, I can do a RESERVED_WIN32.

**Comment by ckerr** [comment]
@Coeur, @nevack would either of you mind reviewing #3823 and giving it priority over this PR? It's been in the pipeline for quite a long time :hourglass_flowing_sand:  and I would rather not merge this one & then ask that author to resolve the merge conflicts, seems a little like adding insult to injury

**Comment by Coeur** [comment]
I read Charles has a concern from previous PR:
- Say one using Transmission3 downloads a torrent with "hello*world.mp4" and completes it as "hello_world.mp4".
- When upgrading to Transmission4.0, the file "hello*world.mp4" can't be found and is redownloaded.

So we'll need to keep both old and newer versions of `makeSubpathPortable`, in order to address Transmission upgrade concerns.

File: tests/libtransmission/torrent-files-test.cc (hunk 6 above)
Comment (Coeur) [reply tests/libtransmission/torrent-files-test.cc]: done in a8a4774

File: libtransmission/torrent-files.cc [hunk 7]
```diff
@@ -307,18 +307,28 @@ void tr_torrent_files::remove(std::string_view parent_in, std::string_view tmpdi
 namespace
 {
 
+[[nodiscard]] bool isUnixReservedFile(std::string_view in) noexcept
```
Comment (nevack) [inline libtransmission/torrent-files.cc:310]: Won't this, `isUnixReservedChar` and their Windows counterparts appear unused?
Maybe you should wrap them in `#ifdef` accordingly?

File: tests/libtransmission/torrent-files-test.cc [hunk 8]
```diff
@@ -143,30 +143,34 @@ TEST_F(TorrentFilesTest, hasAnyLocalData)
 
 TEST_F(TorrentFilesTest, isSubpathPortable)
 {
+#ifdef _WIN32
+#define PORTABLE_UNIX_NOT_WIN32 false
+#else
+#define PORTABLE_UNIX_NOT_WIN32 true
+#endif
```
Comment (nevack) [inline tests/libtransmission/torrent-files-test.cc:150]: Best practice is to undef it after being used, like right after Tests array.

File: libtransmission/torrent-files.cc (hunk 7 above)
Comment (Coeur) [reply libtransmission/torrent-files.cc:310]: Well, my thoughts (added recently in a previous comment):
>I still decided to make distinct functions for Win32 and Unix reserved names, so that we can eventually use either ones depending on the filesystem in the future.

So I would prefer keeping them instead of removing them from the builds.

File: tests/libtransmission/torrent-files-test.cc [hunk 9]
```diff
@@ -143,24 +143,34 @@ TEST_F(TorrentFilesTest, hasAnyLocalData)
 
 TEST_F(TorrentFilesTest, isSubpathPortable)
 {
-    static auto constexpr Tests = std::array<std::pair<std::string_view, bool>, 15>{ {
+#ifdef _WIN32
+#define PORTABLE_UNIX_NOT_WIN32 false
+#else
+#define PORTABLE_UNIX_NOT_WIN32 true
+#endif
```
Comment (tearfur) [inline tests/libtransmission/torrent-files-test.cc:150]: You don't have to worry about `#undef` this way.

```suggestion
static auto constexpr NotWin32 = TR_IF_WIN32(false, true);
```

File: libtransmission/torrent-files.cc (hunk 7 above)
Comment (nevack) [reply libtransmission/torrent-files.cc:310]: I understand that, but I think compiler/clang-tidy will complain about it right now.

**Review by tearfur — CHANGES_REQUESTED** [review]

File: libtransmission/torrent-files.cc (hunk 7 above)
Comment (tearfur) [reply libtransmission/torrent-files.cc:310]: How about this instead?

```suggestion
[[nodiscard, maybe_unused]] bool isUnixReservedFile(std::string_view in) noexcept
```

Comment (nevack) [reply libtransmission/torrent-files.cc:310]: Huh, I thought `[[maybe_unused]]` is for returned result, not for the function itself.
Also, `[[nodiscard]]` with `[[maybe_unused]]` looks pretty suspicious :)

Comment (tearfur) [reply libtransmission/torrent-files.cc:310]: > `[[maybe_unused]]` looks pretty suspicious :)

I know 🤣

File: tests/libtransmission/torrent-files-test.cc (hunk 8 above)
Comment (tearfur) [reply tests/libtransmission/torrent-files-test.cc:150]: https://github.com/transmission/transmission/pull/6187#discussion_r1378433852

File: tests/libtransmission/torrent-files-test.cc (hunk 9 above)
Comment (Coeur) [reply tests/libtransmission/torrent-files-test.cc]: 830bb6ecd3fd974785a6477c94e762fe76c679d9

File: libtransmission/torrent-files.cc (hunk 7 above)
Comment (Coeur) [reply libtransmission/torrent-files.cc]: I've verified the doc: it's valid for the function itself (https://en.cppreference.com/w/cpp/language/attributes/maybe_unused).

d30de1a93df7e188ae9c1384de3f5521ee3500d2

**Comment by tearfur** [comment]
LGTM right now, but I'll wait until #3823 to land and merge into this PR before approving.

**Comment by ckerr** [comment]
https://github.com/transmission/transmission/pull/3823 has landed

**Review by tearfur — APPROVED** [review]

**Comment by tearfur** [comment]
I wonder if #1700 and #4693 is also fixed now 🤔
