### PR TITLE
fix crash when updating blocklist

### LINKED ISSUE #3969: Constant Crashes #8377 build 572e1bb50f macOS M1 ARM 12.6 BlocklistFile::assertValidRules
edit: created as new issue as requested by @Coeur - thanks Coeur

Constant and immediate Crashes after each launch on newest build 572e1bb50f [#8377]#8377 https://build.transmissionbt.com/job/trunk-mac/8377/changes (url) 4.0.0-beta.1.dev 
macOS 12.6 Monterey on M1 Ultra ARM-64
please let me know if I should truncate part of this long crash report…

<details><summary>Translated Report</summary>

```
Process:               Transmission [61772]
Path:                  /Applications/Transmission.app/Contents/MacOS/Transmission
Identifier:            org.m0k.transmission
Version:               4.0.0-beta.1.dev (14714.4.0.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-10-14 16:15:30.8353 -0700
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Anonymous UUID:        C9574617-5AC7-0CB7-EE92-A1FB4E8060A3


Time Awake Since Boot: 1100000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called


Application Specific Backtrace 0:
0   CoreFoundation                      0x000000018fb9d148 __exceptionPreprocess + 240
1   libobjc.A.dylib                     0x000000018f8e7e04 objc_exception_throw + 60
2   CoreFoundation                      0x000000018fb9cf94 +[NSException exceptionWithName:reason:userInfo:] + 0
3   Transmission                        0x00000001010b7b18 _Z16tr_assert_reportNSt3__117basic_string_viewIcNS_11char_traitsIcEEEEiS3_ + 280
4   Transmission                        0x00000001010af3fc _ZN13BlocklistFile16assertValidRulesERKNSt3__16vectorINS_12AddressRangeENS0_9allocatorIS2_EEEE + 572
5   Transmission                        0x00000001010ae1f4 _ZN13BlocklistFile10setContentEPKc + 1760
6   Transmission                        0x0000000101057a20 _Z22tr_blocklistSetContentP10tr_sessionPKc + 604
7   Transmission                        0x0000000101011144 __73-[BlocklistDownloader URLSession:downloadTask:didFinishDownloadingToURL:]_block_invoke.77 + 108
8   libdispatch.dylib                   0x000000018f88a5f0 _dispatch_call_block_and_release + 32
9   libdispatch.dylib                   0x000000018f88c1b4 _dispatch_client_callout + 20
10  libdispatch.dylib                   0x000000018f89a6cc _dispatch_main_queue_drain + 928
11  libdispatch.dylib                   0x000000018f89a31c _dispatch_main_queue_callback_4CF + 44
12  CoreFoundation                      0x000000018fb5e998 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
13  CoreFoundation                      0x000000018fb1bc08 __CFRunLoopRun + 2532
14  CoreFoundation                      0x000000018fb1aa84 CFRunLoopRunSpecific + 600
15  HIToolbox                           0x000000019875a338 RunCurrentEventLoopInMode + 292
16  HIToolbox                           0x000000019875a0b4 ReceiveNextEventCommon + 564
17  HIToolbox                           0x0000000198759e68 _BlockUntilNextEventMatchingListInModeWithFilter + 72
18  AppKit                              0x000000019268251c _DPSNextEvent + 860
19  AppKit                              0x0000000192680e14 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1328
20  AppKit                              0x0000000192672fe0 -[NSApplication run] + 596
21  AppKit                              0x00000001926446fc NSApplicationMain + 1132
22  dyld                                0x00000001015c908c start + 520


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x18fa1ad98 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x18fa4fee0 pthread_kill + 288
2   libsystem_c.dylib             	       0x18f98a340 abort + 168
3   libc++abi.dylib               	       0x18fa0ab08 abort_message + 132
4   libc++abi.dylib               	       0x18f9fa950 demangling_terminate_handler() + 336
5   libobjc.A.dylib               	       0x18f8f0320 _objc_terminate() + 144
6   libc++abi.dylib               	       0x18fa09ea4 std::__terminate(void (*)()) + 20
7   libc++abi.dylib               	       0x18fa09e40 std::terminate() + 64
8   libdispatch.dylib             	       0x18f88c1c8 _dispatch_client_callout + 40
9   libdispatch.dylib             	       0x18f89a6cc _dispatch_main_queue_drain + 928
10  libdispatch.dylib             	       0x18f89a31c _dispatch_main_queue_callback_4CF + 44
11  CoreFoundation                	       0x18fb5e998 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
12  CoreFoundation                	       0x18fb1bc08 __CFRunLoopRun + 2532
13  CoreFoundation                	       0x18fb1aa84 CFRunLoopRunSpecific + 600
14  HIToolbox                     	       0x19875a338 RunCurrentEventLoopInMode + 292
15  HIToolbox                     	       0x19875a0b4 ReceiveNextEventCommon + 564
16  HIToolbox                     	       0x198759e68 _BlockUntilNextEventMatchingListInModeWithFilter + 72
17  AppKit                        	       0x19268251c _DPSNextEvent + 860
18  AppKit                        	       0x192680e14 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1328
19  AppKit                        	       0x192672fe0 -[NSApplication run] + 596
20  AppKit                        	       0x1926446fc NSApplicationMain + 1132
21  dyld                          	       0x1015c908c start + 520

Thread 1:
0   Transmission                  	       0x10108fe2c tr_salt_shaker<unsigned char, 1024ul>::operator()() + 72
1   Transmission                  	       0x101091a6c tr_peerMgr::makeNewPeerConnections(unsigned long) + 660
2   Transmission                  	       0x10109224c tr_peerMgr::bandwidthPulse() + 204
3   Transmission                  	       0x101110134 event_process_active_single_queue + 1108
4   Transmission                  	       0x10110ca34 event_base_loop + 980
5   Transmission                  	       0x10107df8c libeventThreadFunc(tr_event_handle*) + 104
6   Transmission                  	       0x10107eabc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(tr_event_handle*), tr_event_handle*> >(void*) + 44
7   libsystem_pthread.dylib       	       0x18fa5026c _pthread_start + 148
8   libsystem_pthread.dylib       	       0x18fa4b08c thread_start + 8

Thread 2:
0   libsystem_kernel.dylib        	       0x18fa1606c __semwait_signal + 8
1   libsystem_c.dylib             	       0x18f91efc8 nanosleep + 220
2   Transmission                  	       0x101037f9c tr_wait_msec(long) + 76
3   Transmission                  	       0x1010b4a6c tr_web::Impl::curlThreadFunc(tr_web::Impl*) + 668
4   Transmission                  	       0x1010b4e20 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(tr_web::Impl*), tr_web::Impl*> >(void*) + 44
5   libsystem_pthread.dylib       	       0x18fa5026c _pthread_start + 148
6   libsystem_pthread.dylib       	       0x18fa4b08c thread_start + 8

Thread 3:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x18fa128b0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x18fa12d20 mach_msg + 76
2   CoreFoundation                	       0x18fb1d210 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x18fb1b6c0 __CFRunLoopRun + 1180
4   CoreFoundation                	       0x18fb1aa84 CFRunLoopRunSpecific + 600
5   AppKit                        	       0x1927ef100 _NSEventThread + 196
6   libsystem_pthread.dylib       	       0x18fa5026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18fa4b08c thread_start + 8

Thread 4:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 11:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 12:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 13:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 14:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 15:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 16:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 17:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 18:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 19:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 20:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 21:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 22:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 23:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 24:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 25:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0

Thread 26:
0   libsystem_pthread.dylib       	       0x18fa4b078 start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x000000018fa0e0f5   x5: 0x000000016ee6dd50   x6: 0x000000000000006e   x7: 0x0000000000000001
    x8: 0x432d64618d3148cd   x9: 0x432d64608c528d4d  x10: 0x0000000000000200  x11: 0x000000000000000b
   x12: 0x000000000000000b  x13: 0x000000018ff5e2ed  x14: 0x000000018fa0e11b  x15: 0x000000000000e2bc
   x16: 0x0000000000000148  x17: 0x00000001e9b73680  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x000000010163c580  x21: 0x0000000000000103  x22: 0x000000010163c660  x23: 0x0000000000000114
   x24: 0x0000000000000000  x25: 0x000000010163c660  x26: 0x0000000103033940  x27: 0x000000000000000f
   x28: 0x0000000002ffffff   fp: 0x000000016ee6dcc0   lr: 0x000000018fa4fee0
    sp: 0x000000016ee6dca0   pc: 0x000000018fa1ad98 cpsr: 0x40001000
   far: 0x0000000121deca08  esr: 0x56000080  Address size fault

Binary Images:
       0x18fa11000 -        0x18fa48fff libsystem_kernel.dylib (*) <a9d87740-9c1d-3468-bf60-720a8d713cba> /usr/lib/system/libsystem_kernel.dylib
       0x18fa49000 -        0x18fa55fff libsystem_pthread.dylib (*) <63c4eef9-69a5-38b1-996e-8d31b66a051d> /usr/lib/system/libsystem_pthread.dylib
       0x18f910000 -        0x18f991fff libsystem_c.dylib (*) <b25d2080-bb9e-38d6-8236-9cef4b2f11a3> /usr/lib/system/libsystem_c.dylib
       0x18f9f9000 -        0x18fa10fff libc++abi.dylib (*) <4e8d8a11-4217-3d56-9d41-5426f7cf307c> /usr/lib/libc++abi.dylib
       0x18f8cf000 -        0x18f90cfff libobjc.A.dylib (*) <ec96f0fa-6341-3e1d-be54-49b544e17f7d> /usr/lib/libobjc.A.dylib
       0x18f888000 -        0x18f8cefff libdispatch.dylib (*) <b3c7a004-1069-3171-b630-2c386a8b399c> /usr/lib/system/libdispatch.dylib
       0x18fa98000 -        0x18ffdefff com.apple.CoreFoundation (6.9) <fc3c193d-0cdb-3569-9f0e-bd2507ca1dbb> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x198728000 -        0x198a5bfff com.apple.HIToolbox (2.1.1) <aaf900bd-bfb6-3af0-a8d3-e24bbe1d57f5> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x192641000 -        0x1934f9fff com.apple.AppKit (6.9) <5e432f87-5b58-391a-a542-fa2d909dd210> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x1015c4000 -        0x101623fff dyld (*) <38ee9fe9-b66d-3066-8c5c-6ddf0d6944c6> /usr/lib/dyld
       0x100f90000 -        0x1011abfff org.m0k.transmission (4.0.0-beta.1.dev) <90516f82-61d7-3d9b-b91b-a40b68e81b05> /Applications/Transmission.app/Contents/MacOS/Transmission

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=1.1G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.1G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework              1152K        9 
Activity Tracing                   256K        1 
CG backing stores                 4544K        4 
CG image                          16.6M       48 
ColorSync                          624K       27 
CoreAnimation                     38.2M       84 
CoreGraphics                        32K        2 
CoreUI image data                 2960K       25 
Dispatch continuations           160.0M        2 
Foundation                          48K        2 
Kernel Alloc Once                   32K        1 
MALLOC                           745.6M      198 
MALLOC guard page                  288K       15 
MALLOC_MEDIUM (reserved)         104.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.4M       27 
Stack                             21.8M       27 
VM_ALLOCATE                        400K       17 
VM_ALLOCATE (reserved)             256K        1         reserved VM address space (unallocated)
__AUTH                            2520K      295 
__AUTH_CONST                      19.7M      486 
__CTF                               756        1 
__DATA                            14.9M      476 
__DATA_CONST                      17.5M      493 
__DATA_DIRTY                      1726K      206 
__FONT_DATA                          4K        1 
__LINKEDIT                       579.6M        5 
__OBJC_CONST                      3382K      265 
__OBJC_RO                         83.0M        1 
__OBJC_RW                         3168K        1 
__TEXT                           478.8M      510 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
libnetwork                        1664K       24 
mapped file                      199.6M       33 
shared memory                      864K       14 
===========                     =======  ======= 
TOTAL                              2.5G     3304 
TOTAL, minus reserved VM space     2.4G     3304 
```
</details>

<details><summary>Full Report</summary>

```json
{
  "app_name": "Transmission",
  "timestamp": "2022-10-14 16:15:30.00 -0700",
  "app_version": "4.0.0-beta.1.dev",
  "slice_uuid": "90516f82-61d7-3d9b-b91b-a40b68e81b05",
  "build_version": "14714.4.0.0",
  "platform": 1,
  "bundleID": "org.m0k.transmission",
  "share_with_app_devs": 1,
  "is_first_party": 0,
  "bug_type": "309",
  "os_version": "macOS 12.6 (21G115)",
  "incident_id": "0902B409-A539-4E7D-A47D-790D1393C436",
  "name": "Transmission"
}
{
  "uptime": 1100000,
  "procLaunch": "2022-10-14 16:14:58.8902 -0700",
  "procRole": "Foreground",
  "version": 2,
  "userID": 501,
  "deployVersion": 210,
  "modelCode": "Mac13,2",
  "procStartAbsTime": 26454108245164,
  "coalitionID": 168865,
  "osVersion": {
    "train": "macOS 12.6",
    "build": "21G115",
    "releaseType": "User"
  },
  "captureTime": "2022-10-14 16:15:30.8353 -0700",
  "incident": "0902B409-A539-4E7D-A47D-790D1393C436",
  "bug_type": "309",
  "pid": 61772,
  "procExitAbsTime": 26454874737043,
  "translated": false,
  "cpuType": "ARM-64",
  "procName": "Transmission",
  "procPath": "\/Applications\/Transmission.app\/Contents\/MacOS\/Transmission",
  "bundleInfo": {
    "CFBundleShortVersionString": "4.0.0-beta.1.dev",
    "CFBundleVersion": "14714.4.0.0",
    "CFBundleIdentifier": "org.m0k.transmission"
  },
  "storeInfo": {
    "deviceIdentifierForVendor": "2A43E20A-3B04-5D49-AE65-45A7E4CD70F5",
    "thirdParty": true
  },
  "parentProc": "launchd",
  "parentPid": 1,
  "coalitionName": "org.m0k.transmission",
  "crashReporterKey": "C9574617-5AC7-0CB7-EE92-A1FB4E8060A3",
  "sip": "enabled",
  "isCorpse": 1,
  "exception": {
    "codes": "0x0000000000000000, 0x0000000000000000",
    "rawCodes": [
      0,
      0
    ],
    "type": "EXC_CRASH",
    "signal": "SIGABRT"
  },
  "asi": {
    "libsystem_c.dylib": [
      "abort() called"
    ]
  },
  "asiBacktraces": [
    "0   CoreFoundation                      0x000000018fb9d148 __exceptionPreprocess + 240\n1   libobjc.A.dylib                     0x000000018f8e7e04 objc_exception_throw + 60\n2   CoreFoundation                      0x000000018fb9cf94 +[NSException exceptionWithName:reason:userInfo:] + 0\n3   Transmission                        0x00000001010b7b18 _Z16tr_assert_reportNSt3__117basic_string_viewIcNS_11char_traitsIcEEEEiS3_ + 280\n4   Transmission                        0x00000001010af3fc _ZN13BlocklistFile16assertValidRulesERKNSt3__16vectorINS_12AddressRangeENS0_9allocatorIS2_EEEE + 572\n5   Transmission                        0x00000001010ae1f4 _ZN13BlocklistFile10setContentEPKc + 1760\n6   Transmission                        0x0000000101057a20 _Z22tr_blocklistSetContentP10tr_sessionPKc + 604\n7   Transmission                        0x0000000101011144 __73-[BlocklistDownloader URLSession:downloadTask:didFinishDownloadingToURL:]_block_invoke.77 + 108\n8   libdispatch.dylib                   0x000000018f88a5f0 _dispatch_call_block_and_release + 32\n9   libdispatch.dylib                   0x000000018f88c1b4 _dispatch_client_callout + 20\n10  libdispatch.dylib                   0x000000018f89a6cc _dispatch_main_queue_drain + 928\n11  libdispatch.dylib                   0x000000018f89a31c _dispatch_main_queue_callback_4CF + 44\n12  CoreFoundation                      0x000000018fb5e998 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16\n13  CoreFoundation                      0x000000018fb1bc08 __CFRunLoopRun + 2532\n14  CoreFoundation                      0x000000018fb1aa84 CFRunLoopRunSpecific + 600\n15  HIToolbox                           0x000000019875a338 RunCurrentEventLoopInMode + 292\n16  HIToolbox                           0x000000019875a0b4 ReceiveNextEventCommon + 564\n17  HIToolbox                           0x0000000198759e68 _BlockUntilNextEventMatchingListInModeWithFilter + 72\n18  AppKit                              0x000000019268251c _DPSNextEvent + 860\n19  AppKit                              0x0000000192680e14 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1328\n20  AppKit                              0x0000000192672fe0 -[NSApplication run] + 596\n21  AppKit                              0x00000001926446fc NSApplicationMain + 1132\n22  dyld                                0x00000001015c908c start + 520"
  ],
  "extMods": {
    "caller": {
      "thread_create": 0,
      "thread_set_state": 0,
      "task_for_pid": 0
    },
    "system": {
      "thread_create": 0,
      "thread_set_state": 0,
      "task_for_pid": 0
    },
    "targeted": {
      "thread_create": 0,
      "thread_set_state": 0,
      "task_for_pid": 0
    },
    "warnings": 0
  },
  "lastExceptionBacktrace": [
    {
      "imageOffset": 1069364,
      "symbol": "__exceptionPreprocess",
      "symbolLocation": 220,
      "imageIndex": 6
    },
    {
      "imageOffset": 101892,
      "symbol": "objc_exception_throw",
      "symbolLocation": 60,
      "imageIndex": 4
    },
    {
      "imageOffset": 1068948,
      "symbol": "+[NSException exceptionWithName:reason:userInfo:]",
      "symbolLocation": 0,
      "imageIndex": 6
    },
    {
      "imageOffset": 1211160,
      "symbol": "tr_assert_report(std::__1::basic_string_view<char, std::__1::char_traits<char> >, int, std::__1::basic_string_view<char, std::__1::char_traits<char> >)",
      "symbolLocation": 280,
      "imageIndex": 10
    },
    {
      "imageOffset": 1176572,
      "symbol": "BlocklistFile::assertValidRules(std::__1::vector<BlocklistFile::AddressRange, std::__1::allocator<BlocklistFile::AddressRange> > const&)",
      "symbolLocation": 572,
      "imageIndex": 10
    },
    {
      "imageOffset": 1171956,
      "symbol": "BlocklistFile::setContent(char const*)",
      "symbolLocation": 1760,
      "imageIndex": 10
    },
    {
      "imageOffset": 817696,
      "symbol": "tr_blocklistSetContent(tr_session*, char const*)",
      "symbolLocation": 604,
      "imageIndex": 10
    },
    {
      "imageOffset": 528708,
      "symbol": "__73-[BlocklistDownloader URLSession:downloadTask:didFinishDownloadingToURL:]_block_invoke.77",
      "symbolLocation": 108,
      "imageIndex": 10
    },
    {
      "imageOffset": 9712,
      "symbol": "_dispatch_call_block_and_release",
      "symbolLocation": 32,
      "imageIndex": 5
    },
    {
      "imageOffset": 16820,
      "symbol": "_dispatch_client_callout",
      "symbolLocation": 20,
      "imageIndex": 5
    },
    {
      "imageOffset": 75468,
      "symbol": "_dispatch_main_queue_drain",
      "symbolLocation": 928,
      "imageIndex": 5
    },
    {
      "imageOffset": 74524,
      "symbol": "_dispatch_main_queue_callback_4CF",
      "symbolLocation": 44,
      "imageIndex": 5
    },
    {
      "imageOffset": 813464,
      "symbol": "__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__",
      "symbolLocation": 16,
      "imageIndex": 6
    },
    {
      "imageOffset": 539656,
      "symbol": "__CFRunLoopRun",
      "symbolLocation": 2532,
      "imageIndex": 6
    },
    {
      "imageOffset": 535172,
      "symbol": "CFRunLoopRunSpecific",
      "symbolLocation": 600,
      "imageIndex": 6
    },
    {
      "imageOffset": 205624,
      "symbol": "RunCurrentEventLoopInMode",
      "symbolLocation": 292,
      "imageIndex": 7
    },
    {
      "imageOffset": 204980,
      "symbol": "ReceiveNextEventCommon",
      "symbolLocation": 564,
      "imageIndex": 7
    },
    {
      "imageOffset": 204392,
      "symbol": "_BlockUntilNextEventMatchingListInModeWithFilter",
      "symbolLocation": 72,
      "imageIndex": 7
    },
    {
      "imageOffset": 267548,
      "symbol": "_DPSNextEvent",
      "symbolLocation": 860,
      "imageIndex": 8
    },
    {
      "imageOffset": 261652,
      "symbol": "-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]",
      "symbolLocation": 1328,
      "imageIndex": 8
    },
    {
      "imageOffset": 204768,
      "symbol": "-[NSApplication run]",
      "symbolLocation": 596,
      "imageIndex": 8
    },
    {
      "imageOffset": 14076,
      "symbol": "NSApplicationMain",
      "symbolLocation": 1132,
      "imageIndex": 8
    },
    {
      "imageOffset": 20620,
      "symbol": "start",
      "symbolLocation": 520,
      "imageIndex": 9
    }
  ],
  "faultingThread": 0,
  "threads": [
    {
      "triggered": true,
      "id": 12003775,
      "threadState": {
        "x": [
          {
            "value": 0
          },
          {
            "value": 0
          },
          {
            "value": 0
          },
          {
            "value": 0
          },
          {
            "value": 6704652533
          },
          {
            "value": 6155590992
          },
          {
            "value": 110
          },
          {
            "value": 1
          },
          {
            "value": 4840635544636573901
          },
          {
            "value": 4840635540327009613
          },
          {
            "value": 512
          },
          {
            "value": 11
          },
          {
            "value": 11
          },
          {
            "value": 6710223597
          },
          {
            "value": 6704652571
          },
          {
            "value": 58044
          },
          {
            "value": 328
          },
          {
            "value": 8216065664
          },
          {
            "value": 0
          },
          {
            "value": 6
          },
          {
            "value": 4318283136,
            "symbolLocation": 0,
            "symbol": "_main_thread"
          },
          {
            "value": 259
          },
          {
            "value": 4318283360,
            "symbolLocation": 224,
            "symbol": "_main_thread"
          },
          {
            "value": 276
          },
          {
            "value": 0
          },
          {
            "value": 4318283360,
            "symbolLocation": 224,
            "symbol": "_main_thread"
          },
          {
            "value": 4345510208
          },
          {
            "value": 15
          },
          {
            "value": 50331647
          }
        ],
        "flavor": "ARM_THREAD_STATE64",
        "lr": {
          "value": 6704922336
        },
        "cpsr": {
          "value": 1073745920
        },
        "fp": {
          "value": 6155590848
        },
        "sp": {
          "value": 6155590816
        },
        "esr": {
          "value": 1442840704,
          "description": " Address size fault"
        },
        "pc": {
          "value": 6704704920,
          "matchesCrashFrame": 1
        },
        "far": {
          "value": 4863216136
        }
      },
      "queue": "com.apple.main-thread",
      "frames": [
        {
          "imageOffset": 40344,
          "symbol": "__pthread_kill",
          "symbolLocation": 8,
          "imageIndex": 0
        },
        {
          "imageOffset": 28384,
          "symbol": "pthread_kill",
          "symbolLocation": 288,
          "imageIndex": 1
        },
        {
          "imageOffset": 500544,
          "symbol": "abort",
          "symbolLocation": 168,
          "imageIndex": 2
        },
        {
          "imageOffset": 72456,
          "symbol": "abort_message",
          "symbolLocation": 132,
          "imageIndex": 3
        },
        {
          "imageOffset": 6480,
          "symbol": "demangling_terminate_handler()",
          "symbolLocation": 336,
          "imageIndex": 3
        },
        {
          "imageOffset": 135968,
          "symbol": "_objc_terminate()",
          "symbolLocation": 144,
          "imageIndex": 4
        },
        {
          "imageOffset": 69284,
          "symbol": "std::__terminate(void (*)())",
          "symbolLocation": 20,
          "imageIndex": 3
        },
        {
          "imageOffset": 69184,
          "symbol": "std::terminate()",
          "symbolLocation": 64,
          "imageIndex": 3
        },
        {
          "imageOffset": 16840,
          "symbol": "_dispatch_client_callout",
          "symbolLocation": 40,
          "imageIndex": 5
        },
        {
          "imageOffset": 75468,
          "symbol": "_dispatch_main_queue_drain",
          "symbolLocation": 928,
          "imageIndex": 5
        },
        {
          "imageOffset": 74524,
          "symbol": "_dispatch_main_queue_callback_4CF",
          "symbolLocation": 44,
          "imageIndex": 5
        },
        {
          "imageOffset": 813464,
          "symbol": "__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__",
          "symbolLocation": 16,
          "imageIndex": 6
        },
        {
          "imageOffset": 539656,
          "symbol": "__CFRunLoopRun",
          "symbolLocation": 2532,
          "imageIndex": 6
        },
        {
          "imageOffset": 535172,
          "symbol": "CFRunLoopRunSpecific",
          "symbolLocation": 600,
          "imageIndex": 6
        },
        {
          "imageOffset": 205624,
          "symbol": "RunCurrentEventLoopInMode",
          "symbolLocation": 292,
          "imageIndex": 7
        },
        {
          "imageOffset": 204980,
          "symbol": "ReceiveNextEventCommon",
          "symbolLocation": 564,
          "imageIndex": 7
        },
        {
          "imageOffset": 204392,
          "symbol": "_BlockUntilNextEventMatchingListInModeWithFilter",
          "symbolLocation": 72,
          "imageIndex": 7
        },
        {
          "imageOffset": 267548,
          "symbol": "_DPSNextEvent",
          "symbolLocation": 860,
          "imageIndex": 8
        },
        {
          "imageOffset": 261652,
          "symbol": "-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]",
          "symbolLocation": 1328,
          "imageIndex": 8
        },
        {
          "imageOffset": 204768,
          "symbol": "-[NSApplication run]",
          "symbolLocation": 596,
          "imageIndex": 8
        },
        {
          "imageOffset": 14076,
          "symbol": "NSApplicationMain",
          "symbolLocation": 1132,
          "imageIndex": 8
        },
        {
          "imageOffset": 20620,
          "symbol": "start",
          "symbolLocation": 520,
          "imageIndex": 9
        }
      ]
    },
    {
      "id": 12003820,
      "frames": [
        {
          "imageOffset": 1048108,
          "symbol": "tr_salt_shaker<unsigned char, 1024ul>::operator()()",
          "symbolLocation": 72,
          "imageIndex": 10
        },
        {
          "imageOffset": 1055340,
          "symbol": "tr_peerMgr::makeNewPeerConnections(unsigned long)",
          "symbolLocation": 660,
          "imageIndex": 10
        },
        {
          "imageOffset": 1057356,
          "symbol": "tr_peerMgr::bandwidthPulse()",
          "symbolLocation": 204,
          "imageIndex": 10
        },
        {
          "imageOffset": 1573172,
          "symbol": "event_process_active_single_queue",
          "symbolLocation": 1108,
          "imageIndex": 10
        },
        {
          "imageOffset": 1559092,
          "symbol": "event_base_loop",
          "symbolLocation": 980,
          "imageIndex": 10
        },
        {
          "imageOffset": 974732,
          "symbol": "libeventThreadFunc(tr_event_handle*)",
          "symbolLocation": 104,
          "imageIndex": 10
        },
        {
          "imageOffset": 977596,
          "symbol": "void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(tr_event_handle*), tr_event_handle*> >(void*)",
          "symbolLocation": 44,
          "imageIndex": 10
        },
        {
          "imageOffset": 29292,
          "symbol": "_pthread_start",
          "symbolLocation": 148,
          "imageIndex": 1
        },
        {
          "imageOffset": 8332,
          "symbol": "thread_start",
          "symbolLocation": 8,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12003822,
      "frames": [
        {
          "imageOffset": 20588,
          "symbol": "__semwait_signal",
          "symbolLocation": 8,
          "imageIndex": 0
        },
        {
          "imageOffset": 61384,
          "symbol": "nanosleep",
          "symbolLocation": 220,
          "imageIndex": 2
        },
        {
          "imageOffset": 688028,
          "symbol": "tr_wait_msec(long)",
          "symbolLocation": 76,
          "imageIndex": 10
        },
        {
          "imageOffset": 1198700,
          "symbol": "tr_web::Impl::curlThreadFunc(tr_web::Impl*)",
          "symbolLocation": 668,
          "imageIndex": 10
        },
        {
          "imageOffset": 1199648,
          "symbol": "void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(tr_web::Impl*), tr_web::Impl*> >(void*)",
          "symbolLocation": 44,
          "imageIndex": 10
        },
        {
          "imageOffset": 29292,
          "symbol": "_pthread_start",
          "symbolLocation": 148,
          "imageIndex": 1
        },
        {
          "imageOffset": 8332,
          "symbol": "thread_start",
          "symbolLocation": 8,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004081,
      "name": "com.apple.NSEventThread",
      "frames": [
        {
          "imageOffset": 6320,
          "symbol": "mach_msg_trap",
          "symbolLocation": 8,
          "imageIndex": 0
        },
        {
          "imageOffset": 7456,
          "symbol": "mach_msg",
          "symbolLocation": 76,
          "imageIndex": 0
        },
        {
          "imageOffset": 545296,
          "symbol": "__CFRunLoopServiceMachPort",
          "symbolLocation": 372,
          "imageIndex": 6
        },
        {
          "imageOffset": 538304,
          "symbol": "__CFRunLoopRun",
          "symbolLocation": 1180,
          "imageIndex": 6
        },
        {
          "imageOffset": 535172,
          "symbol": "CFRunLoopRunSpecific",
          "symbolLocation": 600,
          "imageIndex": 6
        },
        {
          "imageOffset": 1761536,
          "symbol": "_NSEventThread",
          "symbolLocation": 196,
          "imageIndex": 8
        },
        {
          "imageOffset": 29292,
          "symbol": "_pthread_start",
          "symbolLocation": 148,
          "imageIndex": 1
        },
        {
          "imageOffset": 8332,
          "symbol": "thread_start",
          "symbolLocation": 8,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004361,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004364,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004373,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004541,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004542,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004543,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004570,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004571,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004572,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004573,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004574,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004575,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004576,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004577,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004578,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004579,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004580,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004581,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004582,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004583,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004584,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004585,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    },
    {
      "id": 12004586,
      "frames": [
        {
          "imageOffset": 8312,
          "symbol": "start_wqthread",
          "symbolLocation": 0,
          "imageIndex": 1
        }
      ]
    }
  ],
  "usedImages": [
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6704664576,
      "size": 229376,
      "uuid": "a9d87740-9c1d-3468-bf60-720a8d713cba",
      "path": "\/usr\/lib\/system\/libsystem_kernel.dylib",
      "name": "libsystem_kernel.dylib"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6704893952,
      "size": 53248,
      "uuid": "63c4eef9-69a5-38b1-996e-8d31b66a051d",
      "path": "\/usr\/lib\/system\/libsystem_pthread.dylib",
      "name": "libsystem_pthread.dylib"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6703611904,
      "size": 532480,
      "uuid": "b25d2080-bb9e-38d6-8236-9cef4b2f11a3",
      "path": "\/usr\/lib\/system\/libsystem_c.dylib",
      "name": "libsystem_c.dylib"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6704566272,
      "size": 98304,
      "uuid": "4e8d8a11-4217-3d56-9d41-5426f7cf307c",
      "path": "\/usr\/lib\/libc++abi.dylib",
      "name": "libc++abi.dylib"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6703345664,
      "size": 253952,
      "uuid": "ec96f0fa-6341-3e1d-be54-49b544e17f7d",
      "path": "\/usr\/lib\/libobjc.A.dylib",
      "name": "libobjc.A.dylib"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6703054848,
      "size": 290816,
      "uuid": "b3c7a004-1069-3171-b630-2c386a8b399c",
      "path": "\/usr\/lib\/system\/libdispatch.dylib",
      "name": "libdispatch.dylib"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6705217536,
      "CFBundleShortVersionString": "6.9",
      "CFBundleIdentifier": "com.apple.CoreFoundation",
      "size": 5533696,
      "uuid": "fc3c193d-0cdb-3569-9f0e-bd2507ca1dbb",
      "path": "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
      "name": "CoreFoundation",
      "CFBundleVersion": "1866"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6852608000,
      "CFBundleShortVersionString": "2.1.1",
      "CFBundleIdentifier": "com.apple.HIToolbox",
      "size": 3358720,
      "uuid": "aaf900bd-bfb6-3af0-a8d3-e24bbe1d57f5",
      "path": "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
      "name": "HIToolbox"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 6750998528,
      "CFBundleShortVersionString": "6.9",
      "CFBundleIdentifier": "com.apple.AppKit",
      "size": 15437824,
      "uuid": "5e432f87-5b58-391a-a542-fa2d909dd210",
      "path": "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
      "name": "AppKit",
      "CFBundleVersion": "2113.60.148"
    },
    {
      "source": "P",
      "arch": "arm64e",
      "base": 4317790208,
      "size": 393216,
      "uuid": "38ee9fe9-b66d-3066-8c5c-6ddf0d6944c6",
      "path": "\/usr\/lib\/dyld",
      "name": "dyld"
    },
    {
      "source": "P",
      "arch": "arm64",
      "base": 4311285760,
      "CFBundleShortVersionString": "4.0.0-beta.1.dev",
      "CFBundleIdentifier": "org.m0k.transmission",
      "size": 2211840,
      "uuid": "90516f82-61d7-3d9b-b91b-a40b68e81b05",
      "path": "\/Applications\/Transmission.app\/Contents\/MacOS\/Transmission",
      "name": "Transmission",
      "CFBundleVersion": "14714.4.0.0"
    }
  ],
  "sharedCache": {
    "base": 6701596672,
    "size": 3144744960,
    "uuid": "049b583e-d4dc-3b2b-88da-e52d6e18313d"
  },
  "vmSummary": "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=1.1G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.1G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework              1152K        9 \nActivity Tracing                   256K        1 \nCG backing stores                 4544K        4 \nCG image                          16.6M       48 \nColorSync                          624K       27 \nCoreAnimation                     38.2M       84 \nCoreGraphics                        32K        2 \nCoreUI image data                 2960K       25 \nDispatch continuations           160.0M        2 \nFoundation                          48K        2 \nKernel Alloc Once                   32K        1 \nMALLOC                           745.6M      198 \nMALLOC guard page                  288K       15 \nMALLOC_MEDIUM (reserved)         104.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.4M       27 \nStack                             21.8M       27 \nVM_ALLOCATE                        400K       17 \nVM_ALLOCATE (reserved)             256K        1         reserved VM address space (unallocated)\n__AUTH                            2520K      295 \n__AUTH_CONST                      19.7M      486 \n__CTF                               756        1 \n__DATA                            14.9M      476 \n__DATA_CONST                      17.5M      493 \n__DATA_DIRTY                      1726K      206 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       579.6M        5 \n__OBJC_CONST                      3382K      265 \n__OBJC_RO                         83.0M        1 \n__OBJC_RW                         3168K        1 \n__TEXT                           478.8M      510 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nlibnetwork                        1664K       24 \nmapped file                      199.6M       33 \nshared memory                      864K       14 \n===========                     =======  ======= \nTOTAL                              2.5G     3304 \nTOTAL, minus reserved VM space     2.4G     3304 \n",
  "legacyInfo": {
    "threadTriggered": {
      "queue": "com.apple.main-thread"
    }
  },
  "trialInfo": {
    "rollouts": [
      {
        "rolloutId": "6112dda2fc54bc3389840642",
        "factorPackIds": {
          "SIRI_DICTATION_ASSETS": "631730a28520965d1cba0681"
        },
        "deploymentId": 240000143
      },
      {
        "rolloutId": "60356660bbe37970735c5624",
        "factorPackIds": {},
        "deploymentId": 240000027
      }
    ],
    "experiments": []
  }
}
```
</details>

Model: Mac13,2, BootROM 7459.141.1, proc 20:16:4 processors, 64 GB, SMC 
Graphics: Apple M1 Ultra, Apple M1 Ultra, Built-In
Display: Pro Display XDR, 6016 x 3384 Retina 6K, Main, MirrorOff, Online
Memory Module: LPDDR5
AirPort: Wi-Fi, wl0: Apr  6 2022 06:12:09 version 20.90.45.0.8.7.118 FWID 01-13a89935
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Thunderbolt Bridge, Ethernet, bridge0

_Originally posted in https://github.com/transmission/transmission/issues/3776#issuecomment-1279582060_

### PR DESCRIPTION
**Pull request by sweetppro**
fixes #3969

~this PR provides a quick fix, but perhaps is not the best fix... maybe someone with more c++ knowledge can fix the underlying issue with the assert
@ckerr any ideas~

### CODE REVIEW

File: libtransmission/blocklist.cc [hunk 1]
```diff
@@ -576,14 +576,21 @@ void BlocklistFile::assertValidRules(std::vector<AddressRange> const& ranges)
 
     for (size_t i = 1; i < std::size(ranges_ipv4); ++i)
     {
-        TR_ASSERT(ranges_ipv4[i - 1].end_ < ranges_ipv4[i].begin_);
+        if (ranges_ipv4[i - 1].end_ < ranges_ipv4[i].begin_)
+        {
+            TR_ASSERT(ranges_ipv4[i - 1].end_ < ranges_ipv4[i].begin_);
```
[the remark this answers is not in the document]
Comment (mikedld) [reply libtransmission/blocklist.cc:581]: The other possibility is that the ranges are just not sorted correctly at all when IPv4 and IPv6 addresses are mixed together, which seems even more probable given that `compareAddressRangesByFirstAddress()` is not stable when `a` is IPv4 and`b` is IPv6 (or vice versa); see [Compare](https://en.cppreference.com/w/cpp/named_req/Compare).

[the remark this answers is not in the document]
Comment (sweetppro) [reply libtransmission/blocklist.cc:581]: Interesting, I’ll have a look later today

[the remark this answers is not in the document]
Comment (sweetppro) [reply libtransmission/blocklist.cc:581]: @mikedld I'm trying to understand the code

* Is this assert even needed?
```
for (size_t i = 1; i < std::size(ranges_ipv4); ++i)
{
    TR_ASSERT(ranges_ipv4[i - 1].begin_ <= ranges_ipv4[i].end_);
}

for (size_t i = 1; i < std::size(ranges_ipv6); ++i)
{
    auto const& last_start_address = ranges_ipv6[i - 1].begin6_;
    auto const& start_address = ranges_ipv6[i].begin6_;
    TR_ASSERT(memcmp(&last_start_address, &start_address, sizeof(start_address)) < 0);
}
```
there are a bunch of overlaps in the following blocklist (https://github.com/Naunter/BT_BlockLists)
and the assert fails multiple times...

eg, the last 2 entries for example:
```
Ã…lands Landskapsregering Musikinstitutet:213.204.33.160-213.204.33.167
Ã…lands Landskapsregering Musikinstitutet:213.204.34.80-213.204.34.95
```

* Also what is the purpose of `compareAddressRangesByFirstAddress`. Do the ranges even need to be sorted, does it give faster lookup times? If so, are there any issues with doing this:
```
//seperate before sorting
auto ipv4_ranges = std::vector<AddressRange>{};
auto ipv6_ranges = std::vector<AddressRange>{};

for (auto const& range : ranges)
{
    if (range.begin_ == 0 && range.end_ == 0)
    {
        // IPv6
        ipv6_ranges.emplace_back(range);
    }
    else
    {
        ipv4_ranges.emplace_back(range);
    }
}

std::sort(std::begin(ipv4_ranges), std::end(ipv4_ranges), BlocklistFile::compareAddressRangesByFirstAddress);
std::sort(std::begin(ipv6_ranges), std::end(ipv6_ranges), BlocklistFile::compareAddressRangesByFirstAddress);

#ifdef TR_ENABLE_ASSERTS
    assertValidRules(ipv4_ranges);
    assertValidRules(ipv6_ranges);
#endif

// empty ranges and add sorted
ranges.clear();
ranges.insert( ranges.end(), ipv4_ranges.begin(), ipv4_ranges.end() );
ranges.insert( ranges.end(), ipv6_ranges.begin(), ipv6_ranges.end() );
```

**Comment by sweetppro** [comment]
Ah wait, I see.
I totally didn’t see your comment on the //merge code let me have a look through that

File: libtransmission/blocklist.cc [hunk 2]
```diff
@@ -576,14 +576,21 @@ void BlocklistFile::assertValidRules(std::vector<AddressRange> const& ranges)
 
     for (size_t i = 1; i < std::size(ranges_ipv4); ++i)
     {
-        TR_ASSERT(ranges_ipv4[i - 1].end_ < ranges_ipv4[i].begin_);
+        if (ranges_ipv4[i - 1].end_ < ranges_ipv4[i].begin_)
```
Comment (Coeur) [inline libtransmission/blocklist.cc:579]: This `if` is simply silencing the assertion below, since the condition is identical to the assertion. Your code is equivalent to `/* do nothing */`.

**Review by Coeur — CHANGES_REQUESTED** [review]
The present code change is only making the assertions unreachable.
The assertions should be removed or handled properly.
And a written unit test would be appreciated to acknowledge the resolution of a crash.

File: libtransmission/blocklist.cc [hunk 3]
```diff
@@ -445,9 +445,32 @@ size_t BlocklistFile::setContent(char const* filename)
...
+    }
+
+    std::sort(std::begin(ipv4_ranges), std::end(ipv4_ranges), BlocklistFile::compareAddressRangesByFirstAddress);
+    std::sort(std::begin(ipv6_ranges), std::end(ipv6_ranges), BlocklistFile::compareAddressRangesByFirstAddress);
 
-    std::sort(std::begin(ranges), std::end(ranges), BlocklistFile::compareAddressRangesByFirstAddress);
+    // combine sorted
+    ranges.clear();
+    ranges.insert(ranges.end(), ipv4_ranges.begin(), ipv4_ranges.end());
+    ranges.insert(ranges.end(), ipv6_ranges.begin(), ipv6_ranges.end());
```
Comment (mikedld) [inline libtransmission/blocklist.cc:471]: Subsequent lookups in `hasAddress()` happen depending on address type. I don't think the idea of holding both IPv4 and IPv6 addresses in the same vector was good to begin with, it just adds more complexity, higher memory use, and reduced performance.

I'd split `rules_` in two variables, i.e. `rules_ipv4_` and `rules_ipv6_`, which you have already started preparing here. This in turn means that each variable could use
* its own type-specific `AddressRange` structure to reduce memory use
* its own comparator: we already have `AddressRange::compareIPv4AddressToRange()` and `AddressRange::compareIPv6AddressToRange()`, each could go to its own structure (as `operator<()`), just need to make them proper C++ comparators by switching from `void*` to proper type, and using `std::binary_search()` (C++) instead of `std::bsearch()` (C); since C++ comparators require you to return `bool` and not `int`, this will also mean one less `memcmp()` in IPv6 comparison (although I'm not sure why there're two right now); no need in additional `compareAddressRangesByFirstAddress()`
* its own file to write to and load from, if it makes sense

If there's a way to make this generic (e.g. using templates), I'm all for it.

Comment (sweetppro) [reply libtransmission/blocklist.cc:471]: I agree with all this, it makes total sense to seperate ipv4 and ipv6 addresses.
but perhaps it would be better suited to a seperate PR after this fix is merged

Comment (mikedld) [reply libtransmission/blocklist.cc:471]: In its current form, this fix helps little because all these assertions on separated parts mean nothing when it comes to `hasAddress()` which searches in a merged vector. Even if unrelated structure parts are zeroed out, it still doesn't make the vector suitable for binary search; the final merge result contains IPv4 address ranges followed by IPv6 address ranges, which would mean that
* IPv6 part of IPv4 addresses is zeroed out; when IPV4 address ranges are treated as IPv6 address ranges (during IPv6 address lookup) they are less than any other [actual] IPv6 address range, making the vector sorted in the eyes of `std::bsearch()` (because IPv4 address ranges come first, and should be less than anything else following them)
* IPv4 part of IPv6 addresses is zeroed out; when IPv6 address ranges are treated as IPv4 address ranges (during IPv4 address lookup) they are less than any other [actual] IPv4 address range, making the vector unsorted in the eyes of `std::bsearch()` (because IPv6 address ranges come last, and should be greater than anything else preceding them)

Supplying unsorted sequences to `std::bsearch()` (and `std::binary_search()` for that matter) will yield unpredictable results. It may take time to find the search key or the blocklist for this to happen, but it will happen sooner or later.

Not to mention the merging issue at the position between the last IPv4 address range and the first IPv6 address range in the joined sequence: upon encountering its first IPv6 address range, the loop treats the last IPv4 address range as IPv6 address range, which may lead to them being (wrongfully) merged together.

File: libtransmission/blocklist.cc [hunk 4]
```diff
@@ -445,9 +445,32 @@ size_t BlocklistFile::setContent(char const* filename)
         return {};
     }
 
-    size_t keep = 0; // index in ranges
+    //seperate before sorting
```
Comment (Coeur) [inline libtransmission/blocklist.cc:448]: nit: seperate -> separate

File: libtransmission/blocklist.cc (hunk 3 above)
Comment (sweetppro) [reply libtransmission/blocklist.cc:471]: I’m looking into this, but work is calling right now. So time is limited

Comment (sweetppro) [reply libtransmission/blocklist.cc:471]: I’ve had a play around with this, but I can’t get my head around the syntax for templates. C++ is not a language I am familiar with in any depth.

perhaps someone else wants to finish the migration in a new PR

**Review by Coeur — APPROVED** [review]

**Review by ckerr — APPROVED** [review]

**Comment by ckerr** [comment]
Notes: Fixed 4.0.0-beta.1 crash that could occur when  mixing IPv4 and IPv6 addresses in an IP blocklist.
