### PR TITLE
fix: does not trash added torrent files when asked

### LINKED ISSUE #5290: Transmission leaves .added files
### What is the issue?

Windows 11 QT x64 4.0.0, 4.0.1, 4.0.2

After automatically adding .torrent files from my Downloads folder Transmission leaves .added files in there.

Move the .torrent file to the trash is checked.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

Transmission 4.0.2 (2a57b17031)

### PR DESCRIPTION
**Pull request by ckerr**
Fixes #5290.

### CODE REVIEW

**Comment by ckerr** [comment]
Notes: Fixed bug that broke the "Move torrent file to trash" setting.

File: qt/Session.cc [hunk 1]
```diff
@@ -1060,23 +1060,23 @@ void Session::addTorrent(AddData add_me, tr_variant* args_dict, bool trash_origi
...
+                auto file = QFile{ filename };
+
+                if (trash_original)
+                {
+                    file.setPermissions(QFile::ReadOwner | QFile::WriteOwner);
+                    file.remove();
+                }
+                else
+                {
+                    file.rename(QStringLiteral("%1.added").arg(filename));
```
Comment (sfan5) [inline qt/Session.cc:1075]: Question: why does it rename the file at all? This is not something I, as an user, expect or want. It looks like this can't be disabled either.
