### PR TITLE
Fix UDP can't connect warnings and add IP cache on the way

### LINKED ISSUE #86: Transmission tries to connect IPv6 instances even ipv6 addresses are disabled.
Transmission tries to connect IPv6 instances even ipv6 addresses are disabled.

sysctl.conf:
```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.br0.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.enp3s0.disable_ipv6 = 1
net.ipv6.conf.enp4s0.disable_ipv6 = 1
net.ipv6.conf.enp5s0.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```

systool:
```
Module = "ipv6"
  Parameters:
    autoconf            = "1"
    disable             = "0"
    disable_ipv6        = "1"
```

Note: I am not going to disable the whole IPv6 stack, because some apps have dependency on it. I'm only asking Transmission team to add an option to disable listening to IPv6.

My journal log is flooded with these (and more):

```
-- Logs begin at Wed 2016-11-16 08:25:35 CST, end at Thu 2016-11-17 05:59:39 CST. --
Nov 17 03:40:01 archnet transmission-daemon[313]: [2016-11-17 03:40:01.967] Couldn't connect socket 90 to 2a02:a445:49ed:0:f030:ce43:92b3:eef0, port 50321 (errno 99 - Cannot assign requested address)
Nov 17 03:40:01 archnet transmission-daemon[313]: [2016-11-17 03:40:01.967] Couldn't connect socket 90 to 2001:0:5ef5:79fb:3819:217e:920d:700e, port 37514 (errno 99 - Cannot assign requested address)
Nov 17 03:40:01 archnet transmission-daemon[313]: [2016-11-17 03:40:01.967] Couldn't connect socket 90 to 2001:0:9d38:6ab8:3c4b:1c82:a52d:66a2, port 64677 (errno 99 - Cannot assign requested address)
Nov 17 03:40:01 archnet transmission-daemon[313]: [2016-11-17 03:40:01.967] Couldn't connect socket 90 to 2001:0:9d38:6abd:85d:3dd7:cd55:9536, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:01 archnet transmission-daemon[313]: [2016-11-17 03:40:01.967] Couldn't connect socket 90 to 2001:0:9d38:6ab8:1c31:251b:d166:32cf, port 57438 (errno 99 - Cannot assign requested address)
Nov 17 03:40:03 archnet transmission-daemon[313]: [2016-11-17 03:40:03.967] Couldn't connect socket 45 to 2001:0:5ef5:79fb:3c58:1275:fa92:c6a8, port 59851 (errno 99 - Cannot assign requested address)
Nov 17 03:40:03 archnet transmission-daemon[313]: [2016-11-17 03:40:03.967] Couldn't connect socket 45 to 2001:0:5ef5:79fb:3c58:1275:fa92:c6a8, port 59851 (errno 99 - Cannot assign requested address)
Nov 17 03:40:04 archnet transmission-daemon[313]: [2016-11-17 03:40:04.967] Couldn't connect socket 45 to 2001:0:9d38:6ab8:3c86:1959:a13f:f5be, port 49450 (errno 99 - Cannot assign requested address)
Nov 17 03:40:04 archnet transmission-daemon[313]: [2016-11-17 03:40:04.967] Couldn't connect socket 45 to a7c2:0:5ef5:79fd:34bc:993:b3b8:ee95, port 56112 (errno 99 - Cannot assign requested address)
Nov 17 03:40:04 archnet transmission-daemon[313]: [2016-11-17 03:40:04.967] Couldn't connect socket 63 to 2a02:c7f:600:af00:b034:3267:417b:1d5f, port 51413 (errno 99 - Cannot assign requested address
Nov 17 03:40:04 archnet transmission-daemon[313]: [2016-11-17 03:40:04.967] Couldn't connect socket 63 to 2a02:c7f:600:af00:b034:3267:417b:1d5f, port 51413 (errno 99 - Cannot assign requested address
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:5ef5:79fb:189c:397d:ac02:4538, port 12346 (errno 99 - Cannot assign requested address)
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:5ef5:79fd:87d:1ba4:a152:dd82, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:5ef5:79fd:34bc:993:b3b8:ee95, port 42946 (errno 99 - Cannot assign requested address)
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:9d38:6abd:84:32e3:b218:5789, port 35576 (errno 99 - Cannot assign requested address) (
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:9d38:6abd:383f:2490:44c5:e4, port 45682 (errno 99 - Cannot assign requested address) (
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:9d38:90d7:2c36:36d9:a500:f02c, port 10603 (errno 99 - Cannot assign requested address)
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:5ef5:79fd:3ce2:278b:adb5:7944, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:5ef5:79fd:3ce2:278b:adb5:7944, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:9d38:6abd:30e3:ad0:e73d:2893, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:9d38:6abd:30e3:ad0:e73d:2893, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:08 archnet transmission-daemon[313]: [2016-11-17 03:40:08.967] Couldn't connect socket 38 to 2601:85:4501:61aa:e0f9:dd4c:d654:a3cd, port 30793 (errno 99 - Cannot assign requested address
Nov 17 03:40:08 archnet transmission-daemon[313]: [2016-11-17 03:40:08.967] Couldn't connect socket 38 to 2601:85:4501:61aa:e0f9:dd4c:d654:a3cd, port 30793 (errno 99 - Cannot assign requested address
Nov 17 03:40:09 archnet transmission-daemon[313]: [2016-11-17 03:40:09.968] Couldn't connect socket 48 to 2a02:1810:9d17:fc00:a558:e1f2:6c46:d63a, port 41897 (errno 99 - Cannot assign requested addre
Nov 17 03:40:09 archnet transmission-daemon[313]: [2016-11-17 03:40:09.968] Couldn't connect socket 48 to 2a02:1810:9d17:fc00:a558:e1f2:6c46:d63a, port 41897 (errno 99 - Cannot assign requested addre
Nov 17 03:40:11 archnet transmission-daemon[313]: [2016-11-17 03:40:11.967] Couldn't connect socket 48 to 2001:0:9d38:6ab8:24d7:368b:743d:bc26, port 14844 (errno 99 - Cannot assign requested address)
Nov 17 03:40:23 archnet transmission-daemon[313]: [2016-11-17 03:40:23.967] Couldn't connect socket 36 to 2001:0:9d38:90d7:2407:1849:a9ea:f5a9, port 40414 (errno 99 - Cannot assign requested address)
Nov 17 03:40:23 archnet transmission-daemon[313]: [2016-11-17 03:40:23.967] Couldn't connect socket 36 to 2001:0:9d38:90d7:2867:9a9b:b0be:8881, port 11337 (errno 99 - Cannot assign requested address)
Nov 17 03:40:28 archnet transmission-daemon[313]: [2016-11-17 03:40:28.967] Couldn't connect socket 51 to 2001:0:9d38:6abd:86b:211c:a128:34f1, port 40501 (errno 99 - Cannot assign requested address)
Nov 17 03:40:28 archnet transmission-daemon[313]: [2016-11-17 03:40:28.967] Couldn't connect socket 51 to 2001:0:9d38:6abd:88e:1654:d198:d941, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:28 archnet transmission-daemon[313]: [2016-11-17 03:40:28.967] Couldn't connect socket 51 to 2001:0:9d38:6ab8:34ad:eca:a1ba:d6af, port 40501 (errno 99 - Cannot assign requested address)
Nov 17 03:40:28 archnet transmission-daemon[313]: [2016-11-17 03:40:28.967] Couldn't connect socket 51 to 2001:0:5ef5:79fb:1c53:3643:4006:8239, port 8999 (errno 99 - Cannot assign requested address)
Nov 17 03:40:28 archnet transmission-daemon[313]: [2016-11-17 03:40:28.967] Couldn't connect socket 51 to 2001:0:5ef5:79fd:34c7:3068:2b8f:67af, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:28 archnet transmission-daemon[313]: [2016-11-17 03:40:28.967] Couldn't connect socket 51 to 2001:0:9d38:6abd:e0:2dd3:af2b:4755, port 40500 (errno 99 - Cannot assign requested address) (
Nov 17 03:40:29 archnet transmission-daemon[313]: [2016-11-17 03:40:29.967] Couldn't connect socket 51 to 2001:0:5ef5:79fd:2825:20cc:937c:cb3c, port 64232 (errno 99 - Cannot assign requested address)
Nov 17 03:40:29 archnet transmission-daemon[313]: [2016-11-17 03:40:29.967] Couldn't connect socket 51 to 2001:0:9d38:6abd:1c53:9e5e:4387:6b5a, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:29 archnet transmission-daemon[313]: [2016-11-17 03:40:29.967] Couldn't connect socket 51 to 2001:0:9d38:6abd:24d8:d7a:2d44:7c2, port 40500 (errno 99 - Cannot assign requested address) (
Nov 17 03:40:29 archnet transmission-daemon[313]: [2016-11-17 03:40:29.967] Couldn't connect socket 51 to 2001:0:9d38:90d7:1833:3fe6:bf90:d5b3, port 58908 (errno 99 - Cannot assign requested address)
Nov 17 03:40:29 archnet transmission-daemon[313]: [2016-11-17 03:40:29.967] Couldn't connect socket 51 to 2405:204:2087:67bc:fb08:e5cb:5ecc:ace, port 6881 (errno 99 - Cannot assign requested address)
Nov 17 03:40:31 archnet transmission-daemon[313]: [2016-11-17 03:40:31.967] Couldn't connect socket 48 to 2001:0:9d38:6ab8:108d:3fce:a0a2:5b88, port 6881 (errno 99 - Cannot assign requested address)
Nov 17 03:40:32 archnet transmission-daemon[313]: [2016-11-17 03:40:32.967] Couldn't connect socket 48 to 2001:0:5ef5:79fd:10a1:381e:a777:714c, port 63302 (errno 99 - Cannot assign requested address)
Nov 17 03:40:33 archnet transmission-daemon[313]: [2016-11-17 03:40:33.967] Couldn't connect socket 51 to 2602:306:3b37:6a70:ed51:80a0:8abd:cb96, port 50001 (errno 99 - Cannot assign requested addres
Nov 17 03:40:33 archnet transmission-daemon[313]: [2016-11-17 03:40:33.967] Couldn't connect socket 51 to 2602:306:3b37:6a70:ed51:80a0:8abd:cb96, port 50001 (errno 99 - Cannot assign requested addres
Nov 17 03:40:35 archnet transmission-daemon[313]: [2016-11-17 03:40:35.967] Couldn't connect socket 51 to 2602:306:8b10:33c0:d1d0:40e1:e538:9824, port 51930 (errno 99 - Cannot assign requested addres
Nov 17 03:40:35 archnet transmission-daemon[313]: [2016-11-17 03:40:35.967] Couldn't connect socket 51 to 2602:306:8b10:33c0:d1d0:40e1:e538:9824, port 51930 (errno 99 - Cannot assign requested addres
Nov 17 03:40:35 archnet transmission-daemon[313]: [2016-11-17 03:40:35.967] Couldn't connect socket 51 to 2601:601:8a02:dc0:2dca:d74a:f030:e279, port 40500 (errno 99 - Cannot assign requested address
Nov 17 03:40:35 archnet transmission-daemon[313]: [2016-11-17 03:40:35.967] Couldn't connect socket 51 to 2602:30a:2c65:c200:b1e3:470c:f6ae:ccaa, port 40500 (errno 99 - Cannot assign requested addres
Nov 17 03:40:35 archnet transmission-daemon[313]: [2016-11-17 03:40:35.967] Couldn't connect socket 51 to 2a02:2149:8237:a200:354a:8b7:d001:b20a, port 40500 (errno 99 - Cannot assign requested addres
Nov 17 03:40:39 archnet transmission-daemon[313]: [2016-11-17 03:40:39.967] Couldn't connect socket 51 to 2001:0:5ef5:79fd:381f:1e95:b85c:1fe9, port 25163 (errno 99 - Cannot assign requested address)
Nov 17 03:40:39 archnet transmission-daemon[313]: [2016-11-17 03:40:39.967] Couldn't connect socket 51 to 2001:0:5ef5:79fd:381f:1e95:b85c:1fe9, port 25163 (errno 99 - Cannot assign requested address)
Nov 17 03:40:44 archnet transmission-daemon[313]: [2016-11-17 03:40:44.967] Couldn't connect socket 51 to 2001:0:9d38:90d7:4f:3180:d8d1:1d3f, port 30238 (errno 99 - Cannot assign requested address) (
Nov 17 03:40:49 archnet transmission-daemon[313]: [2016-11-17 03:40:49.967] Couldn't connect socket 56 to 2001:0:5ef5:79fd:2047:d9fc:b69f:8ee2, port 53787 (errno 99 - Cannot assign requested address)
Nov 17 03:40:49 archnet transmission-daemon[313]: [2016-11-17 03:40:49.967] Couldn't connect socket 56 to 2a02:2149:8154:c00:f0f2:3b09:7bd8:a7a7, port 40500 (errno 99 - Cannot assign requested addres
Nov 17 03:40:49 archnet transmission-daemon[313]: [2016-11-17 03:40:49.967] Couldn't connect socket 56 to 2001:0:5ef5:79fd:24bc:38b2:203b:a5a6, port 64611 (errno 99 - Cannot assign requested address)
Nov 17 03:40:50 archnet transmission-daemon[313]: [2016-11-17 03:40:50.967] Couldn't connect socket 56 to 2001:0:9d38:6ab8:3cd6:6a6:fae1:ec0e, port 8999 (errno 99 - Cannot assign requested address) (
Nov 17 03:40:50 archnet transmission-daemon[313]: [2016-11-17 03:40:50.967] Couldn't connect socket 56 to 2001:0:9d38:6abd:2cef:3bca:b275:ce38, port 40507 (errno 99 - Cannot assign requested address)
```

### LINKED ISSUE #4517: tr-udp.cc: Couldn't send to [xxxx:xx:xxxx:xxxx::xxxx]:yyyyy: 101 (Network is unreachable)
### What is the issue?

My transmission-daemon's message log still gets flooded by the same warnings from tr-udp as reported in the closed issues #4406  and #4516 :

`[2023-01-02 15:18:33.522] WRN tr-udp.cc:258 Couldn't send to [2601:8b:8580:7c60::9a00]:18939: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:18:35.732] WRN tr-udp.cc:258 Couldn't send to [2601:8b:8402:ad00::ff85]:64329: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:18:35.732] WRN tr-udp.cc:258 Couldn't send to [2601:8b:8580:7c60::9a00]:18939: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:18:39.523] WRN tr-udp.cc:258 Couldn't send to [2601:8b:8402:ad00::ff85]:64329: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:18:42.522] WRN tr-udp.cc:258 Couldn't send to [2601:8b:8580:7c60::9a00]:18939: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:18:45.522] WRN tr-udp.cc:258 Couldn't send to [2601:8b:8402:ad00::ff85]:64329: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:19:06.522] WRN tr-udp.cc:258 Couldn't send to [2607:fa49:3c3e:a600::4246]:20431: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:19:09.522] WRN tr-udp.cc:258 Couldn't send to [2607:fa49:3c3e:a600::4246]:20431: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:19:15.523] WRN tr-udp.cc:258 Couldn't send to [2607:fa49:3c3e:a600::4246]:20431: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:20:13.523] WRN tr-udp.cc:258 Couldn't send to [2603:8000:5e00:2207::11d6]:60954: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:20:14.597] WRN tr-udp.cc:258 Couldn't send to [2001:0:284a:364:89a:17c6:a199:83db]:5034: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:20:16.523] WRN tr-udp.cc:258 Couldn't send to [2603:8000:5e00:2207::11d6]:60954: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:20:18.691] WRN tr-udp.cc:258 Couldn't send to [2001:0:284a:364:89a:17c6:a199:83db]:5034: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:20:22.523] WRN tr-udp.cc:258 Couldn't send to [2603:8000:5e00:2207::11d6]:60954: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:20:24.691] WRN tr-udp.cc:258 Couldn't send to [2001:0:284a:364:89a:17c6:a199:83db]:5034: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:21:24.523] WRN tr-udp.cc:258 Couldn't send to [fde6:7a:7d20:18f6::10b8]:26351: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:21:27.523] WRN tr-udp.cc:258 Couldn't send to [fde6:7a:7d20:18f6::10b8]:26351: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:21:32.523] WRN tr-udp.cc:258 Couldn't send to [2600:1009:a101:8d17:411d:164a:d30:5202]:10807: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:21:34.716] WRN tr-udp.cc:258 Couldn't send to [fde6:7a:7d20:18f6::10b8]:26351: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:21:35.601] WRN tr-udp.cc:258 Couldn't send to [2600:1009:a101:8d17:411d:164a:d30:5202]:10807: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:21:41.523] WRN tr-udp.cc:258 Couldn't send to [2600:1009:a101:8d17:411d:164a:d30:5202]:10807: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:23:11.522] WRN tr-udp.cc:258 Couldn't send to [2a02:587:5f09:4c00:452c:be8c:49ec:10c2]:19738: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:23:13.700] WRN tr-udp.cc:258 Couldn't send to [2a02:587:5f09:4c00:452c:be8c:49ec:10c2]:19738: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:23:20.522] WRN tr-udp.cc:258 Couldn't send to [2a02:587:5f09:4c00:452c:be8c:49ec:10c2]:19738: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:24:07.523] WRN tr-udp.cc:258 Couldn't send to [2a00:1851:17:1485:9098:3805:56ed:2]:26610: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:24:07.524] WRN tr-udp.cc:258 Couldn't send to [2601:246:8102:de00::e150]:19795: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:24:07.524] WRN tr-udp.cc:258 Couldn't send to [2a00:1851:18:7d97:246f:8c3d:47f1:4]:26610: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:24:07.524] WRN tr-udp.cc:258 Couldn't send to [2601:246:8102:de00::d4af]:19795: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:24:07.524] WRN tr-udp.cc:258 Couldn't send to [2a00:1851:17:f9d:246f:8c3d:47f1:3]:26610: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:24:08.588] WRN tr-udp.cc:258 Couldn't send to [2a00:1851:8017:e40c:9098:3805:56ed:2]:26610: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)`

`[2023-01-02 15:24:08.588] WRN tr-udp.cc:258 Too many messages like this! I won't log this message anymore this session. (/home/Transmission/libtransmission/tr-udp.cc:258)`

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

8064912

### PR DESCRIPTION
**Pull request by tearfur**
Fixed #4517, possibly fixes #86 too.

As far as I can tell, the reason this is happening is because `tr_net_hasIPv6()` will only disable UDP6 for Transmission (by not creating a UDP6 socket) when the IPv6 module is not loaded into the kernel (for Linux at least). It does not stop Transmission from trying to connect to IPv6 peers via UDP when the IPv6 module is loaded, but no global IPv6 connectivity is available. However, it needs to stay this way in case a peer is found by LPD.

https://github.com/transmission/transmission/blob/e68c72daa479f81d519fb83219aedc81d1516fb9/libtransmission/tr-udp.cc#L177-L180

The same can happen for IPv4 if the user only has IPv6 (I think).

So I figured the best way to fix this is to check if the system has a source address that can connect to the public internet in `tr_session::tr_udp_core::sendto()`, which is called for every buffer that needs to be sent over UDP.

Thus, this PR ballooned into adding a whole new infrastructural class, which is an IP cache that stores 3 pieces of info for each IP protocol:
1. Whether this system supports this IP protocol. `tr_session.has_ip_protocol()`
2. The source address used by Transmission that provides connectivity to the public internet. `tr_session.globalSourceIP()`
3. The global address that Transmission is being seen as by other peers. `tr_session.globalIP()`

If I did everything right, then:
- `tr_net_hasIPv6()` can be replaced by `tr_session.has_ip_protocol()` (This will be for a future PR)
- Apps using libtransmission can make use of the cache to tell users the global IP that they are being seen as, which is a function I wish I had at some point. (Not implemented)
- And of course, `tr_udp_core` knows not to bother sending stuff to global addresses when we have no public internet connectivity (i.e. no source address cached). (Already in this PR)

### CODE REVIEW

**Comment by tearfur** [comment]
> > I also don't know how to hide the changes already merged into `main`. 😨
> 
> Github correctly show only newly modified files. I think you can `git fetch origin main:main` and then `git rebase origin/main`. Of course then you have to `git push --force origin <branch-name>`.

I think it did not work in local because my local `main` branch is outdated. Anyway I fixed it now. Thanks!

**Comment by nevack** [comment]
> > > I also don't know how to hide the changes already merged into `main`. 😨
> > 
> > 
> > Github correctly show only newly modified files. I think you can `git fetch origin main:main` and then `git rebase origin/main`. Of course then you have to `git push --force origin <branch-name>`.
> 
> I think it did not work in local because my local `main` branch is outdated. Anyway I fixed it now. Thanks!

I guessed this too, that's why I suggested `fetch` first 😉

**Comment by tearfur** [comment]
@ckerr I think I am dealing with a race condition during `tr_session`'s initialisation after adding a new field to it. Would like some help identifying it.

By some magic, 58b1b20 -> f5c35c7 "fixed" some failed tests (They are all using `SessionTest` or its derived fixture class) that triggered a segmentation fault. I don't think it is a good sign.

Could you please let me know how do you decide if a member of `tr_session` would be initialised:
1. In the constructor's initialization list
2. By a default initializer provided in the field
3. Inside `tr_session.initImpl()`

File: libtransmission/session.h [hunk 1]
```diff
@@ -1072,6 +1076,9 @@ struct tr_session
     // depends-on: session_thread_, settings_.bind_address_ipv6, local_peer_port_
     std::optional<BoundSocket> bound_ipv6_;
 
+    // depends-on: timer_maker_
+    std::unique_ptr<tr_global_ip_cache> global_ip_cache_ = std::make_unique<tr_global_ip_cache>(this);
```
Comment (tearfur) [inline libtransmission/session.h:1080]: This actually also depends on `web_`, need to move it down.

Comment (tearfur) [reply libtransmission/session.h:1080]: `udp_core_` now depends on the new field `global_ip_cache_` as well.

https://github.com/transmission/transmission/blob/f5c35c7855d57339390ed5011cdfa603be88eb9c/libtransmission/session.h#L1083-L1085

File: libtransmission/net.cc [hunk 2]
```diff
@@ -417,56 +417,111 @@ void tr_net_close_socket(tr_socket_t sockfd)
...
-            }
+            return std::isspace(c);
+        };
+        ip.erase(ip.begin(), std::find_if_not(ip.begin(), ip.end(), Ws));
+        ip.erase(std::find_if_not(ip.rbegin(), ip.rend(), Ws).base(), ip.end());
+
+        // Update member
+        if (auto addr = tr_address::from_string(ip); addr && addr->is_global_unicast_address() && addr->is_ipv4())
+        {
+            ipv4_addr_ = addr;
```
Comment (tearfur) [inline libtransmission/net.cc:484]: Add write lock.

File: libtransmission/net.cc [hunk 3]
```diff
@@ -417,56 +417,111 @@ void tr_net_close_socket(tr_socket_t sockfd)
...
 
-    errno = save;
-    return {};
+    if (!success)
+    {
+        tr_logAddWarn(fmt::format(
+            _("Couldn't update global IPv4 address: {url} (HTTP {status})"),
+            fmt::arg("url", IPv4QueryServices[*d]),
+            fmt::arg("status", response.status)));
+        ipv4_addr_.reset();
```
Comment (tearfur) [inline libtransmission/net.cc:507]: Add write lock

File: libtransmission/net.cc [hunk 4]
```diff
@@ -417,56 +417,111 @@ void tr_net_close_socket(tr_socket_t sockfd)
...
+                                         d };
+    options.ip_proto = tr_web::FetchOptions::IPProtocol::V4;
+    options.sndbuf = 4096;
+    options.rcvbuf = 4096;
+    session_->fetch(std::move(options));
+}
+
+void tr_global_ip_cache::update_ipv6_addr() noexcept
 {
+    ipv6_addr_ = ipv6_global_address();
```
Comment (tearfur) [inline libtransmission/net.cc:451]: Add write lock

File: libtransmission/session.h [hunk 5]
```diff
@@ -783,6 +778,16 @@ struct tr_session
         bool is_any_addr;
     };
 
+    [[nodiscard]] auto globalIPv4() const noexcept
+    {
+        return global_ip_cache_->globalIPv4();
```
Comment (tearfur) [inline libtransmission/session.h:783]: Add read lock

File: libtransmission/session.h [hunk 6]
```diff
@@ -783,6 +778,16 @@ struct tr_session
...
+    }
+
+    [[nodiscard]] auto globalIPv6() const noexcept
+    {
+        return global_ip_cache_->globalIPv6();
```
Comment (tearfur) [inline libtransmission/session.h:788]: Add read lock

**Review by tearfur — COMMENTED** [review]
Add locking mechanisms in these places

File: libtransmission/net.h [hunk 7]
```diff
@@ -398,4 +404,44 @@ void tr_netSetTOS(tr_socket_t sock, int tos, tr_address_type type);
...
+    explicit tr_global_ip_cache(tr_session* session_in);
+    tr_global_ip_cache(tr_global_ip_cache const&) = delete;
+    tr_global_ip_cache(tr_global_ip_cache&&) = delete;
+    tr_global_ip_cache& operator=(tr_global_ip_cache const&) = delete;
+    tr_global_ip_cache& operator=(tr_global_ip_cache&&) = delete;
+    ~tr_global_ip_cache() = default;
+
+    [[nodiscard]] const std::optional<tr_address>& globalIPv4() const noexcept
+    {
+        return ipv4_addr_;
```
Comment (tearfur) [inline libtransmission/net.h:419]: Add read lock

File: libtransmission/net.h [hunk 8]
```diff
@@ -398,4 +404,44 @@ void tr_netSetTOS(tr_socket_t sock, int tos, tr_address_type type);
...
+    }
+
+    [[nodiscard]] const std::optional<tr_address>& globalIPv6() const noexcept
+    {
+        return ipv6_addr_;
```
Comment (tearfur) [inline libtransmission/net.h:424]: Add read lock

**Comment by tearfur** [comment]
@ckerr I think I eliminated the race conditional now. Thanks if you took the time to look ❤️

**Comment by tearfur** [comment]
Testing on a system that has IPv6 capability but no IPv6 global address.

### Before

image

### After

image

**Comment by ckerr** [comment]
@tearfur sorry about the radio silence; I've been traveling and have been pretty busy IRL.

Are there any remaining questions / issues?

**Comment by tearfur** [comment]
@ckerr I don't think so, I reckon I understand enough about libtransmission to do what I want to do for this PR.

Thanks for asking!

**Comment by ckerr** [comment]
@tearfur just a heads-up, Transmission 4.0.3 has been milestoned for April 13.

I see this is still a draft and TBH I have been preoccupied online so IDK if you want to have this in 4.0.3 or not; but if you do, there's the date :smile_cat:

**Comment by tearfur** [comment]
@ckerr I have it where I want to be now. It has ballooned to much more than just a fix though, I think it is more appropriate for a minor release. Will update the descriptions in a moment.

I just need someone to figure out where did the segfault happen on Mac. Is there anyone I can ask for help from?

**Comment by tearfur** [comment]
@Coeur Could you perhaps help run the Mac tests in a debugger to find the segmentation fault? I don't have a Mac myself.
Thanks.

**Comment by tearfur** [comment]
> @Coeur Could you perhaps help run the Mac tests in a debugger to find the segmentation fault? I don't have a Mac myself. Thanks.

I think I got it.

@ckerr Ready for review.

**Comment by ckerr** [comment]
> I think it is more appropriate for a minor release.

@tearfur OK, I've milestoned for 4.1.0. :heart: 

If you also want to make any semver-patch subset of this PR for a bugfix release, I'd be happy to review that for 4.0.x

**Comment by Coeur** [comment]
> @Coeur Could you perhaps help run the Mac tests in a debugger to find the segmentation fault? I don't have a Mac myself.
> Thanks.

Those are Google tests. I do not know how to run them with Apple's Xcode.

**Comment by Coeur** [comment]
> @Coeur Could you perhaps help run the Mac tests in a debugger to find the segmentation fault? I don't have a Mac myself.
> Thanks.

Those are Google tests. I do not know how to run them with Apple's Xcode.

File: libtransmission/net.h [hunk 9]
```diff
@@ -398,4 +408,87 @@ void tr_netSetTOS(tr_socket_t sock, int tos, tr_address_type type);
...
+    std::array<std::unique_ptr<libtransmission::Timer>, NUM_TR_AF_INET_TYPES> upkeep_timers_;
+
+    std::array<std::atomic_size_t, NUM_TR_AF_INET_TYPES> ix_service_ = { 0U };
+    static auto constexpr IPQueryServices = std::array{ "https://icanhazip.com"sv, "https://api64.ipify.org"sv };
+
+    friend struct tr_session;
+
+public:
+    static auto constexpr UpkeepInterval = 30min;
+    static auto constexpr RetryUpkeepInterval = 30s;
```
Comment (mikedld) [inline libtransmission/net.h:493]: Not that I mind but why are these constants public? They seem to only be used within the containing class.

File: libtransmission/net.h [hunk 10]
```diff
@@ -398,4 +408,87 @@ void tr_netSetTOS(tr_socket_t sock, int tos, tr_address_type type);
...
+ * you have connectivity to the public internet. And if the global address is
+ * the same with the source address, then you are not behind an NAT.
+ *
+ * Note: This class isn't meant to be accessed by anyone other than tr_session,
+ * so it has no public methods.
+ */
+class tr_global_ip_cache
+{
+public:
+    explicit tr_global_ip_cache(tr_session* session_in);
```
Comment (mikedld) [inline libtransmission/net.h:429]:
```suggestion
    explicit tr_global_ip_cache(tr_session& session_in);
```

File: libtransmission/net.cc [hunk 11]
```diff
@@ -849,3 +761,342 @@ int tr_address::compare(tr_address const& that) const noexcept // <=>
...
+// are modified from code by Juliusz Chroboczek and is covered under the same license as dht.cc.
+// Please feel free to copy them into your software if it can help
+// unbreaking the double-stack Internet.
+std::optional<tr_address> tr_global_ip_cache::get_global_source_address(int af, tr_address const& bind_addr)
+{
+    TR_ASSERT(af == AF_INET || af == AF_INET6);
+
+    // Pick some destination address to pretend to send a packet to
+    static auto constexpr DstIPv4 = "91.121.74.28"sv;
+    static auto constexpr DstIPv6 = "2001:1890:1112:1::20"sv;
```
[the remark this answers is not in the document]
Comment (tearfur) [reply libtransmission/net.cc:1045]: This is existing code from ab9e971903cd7944fcb46a954997fef627b87e86, originally in the function `global_ipv6_helpers::get_source_address`.

File: libtransmission/net.h [hunk 12]
```diff
@@ -398,4 +408,87 @@ void tr_netSetTOS(tr_socket_t sock, int tos, tr_address_type type);
...
+
+    // Keep the timer at the bottom of the class definition so that it will be destructed first
+    // We don't want it to trigger after the IP addresses have been destroyed
+    // (The destructor will acquire the IP address locks before proceeding, but still)
+    std::array<std::unique_ptr<libtransmission::Timer>, NUM_TR_AF_INET_TYPES> upkeep_timers_;
+
+    std::array<std::atomic_size_t, NUM_TR_AF_INET_TYPES> ix_service_ = { 0U };
+    static auto constexpr IPQueryServices = std::array{ "https://icanhazip.com"sv, "https://api64.ipify.org"sv };
+
+    friend struct tr_session;
```
[the remark this answers is not in the document]
Comment (tearfur) [reply libtransmission/net.h:489]: https://isocpp.org/wiki/faq/friends#friends-and-encap

IMO friend classes are a nice way to move a part of the class to a separate definition. What was private remains private, no clumsy getters/setters that makes an otherwise private field effectively public.

I did so because I remember seeing @ckerr remarking on multiple occasions that `tr_session` is already very long, and he hesitates on adding new methods or nested classes to it.

File: libtransmission/net.cc [hunk 13]
```diff
@@ -849,3 +761,342 @@ int tr_address::compare(tr_address const& that) const noexcept // <=>
...
+                        return addrport->first;
+                    }
+                }
+            }
+        }
+
+        tr_net_close_socket(sock);
+    }
+
+    return {};
```
[the remark this answers is not in the document]
Comment (tearfur) [reply libtransmission/net.cc:1101]: I do check for `EAFNOSUPPORT` 2 levels up the call stack.

I will address the effect of `tr_net_close_socket()` in my next commit.

File: libtransmission/net.h [hunk 14]
```diff
@@ -58,6 +63,11 @@ using tr_socket_t = int;
 #define sockerrno errno
 #endif
 
+#include "timer.h"
+#include "web.h"
+
+using namespace std::literals;
```
[the remark this answers is not in the document]
Comment (tearfur) [reply libtransmission/net.h]: Moved `tr_global_ip_cache` to a new unit.

File: libtransmission/net.cc (hunk 11 above)
[the remark this answers is not in the document]
Comment (ckerr) [reply libtransmission/net.cc]: @mikedld these are just arbitrary ipv4 / ipv6 destinations.  Nothing actually gets sent; this is just a dummy target to feed to `get_source_address()` to try and figure out our own address by making a socket & check its source address via `socket()` + `getsockname()`

File: libtransmission/net.h (hunk 12 above)
[the remark this answers is not in the document]
Comment (mikedld) [reply libtransmission/net.h]: I never said I was against putting this new logic into a separate class, on the contrary :) No matter what that article says, encalsulation is broken here IMHO and `tr_global_ip_cache` will now have to be refactored (which shouldn't happen) if `tr_session` changes the way it manages settings. And none of it cancels the fact that the new class can't be tested directly, you're forced to test it through session, and make real HTTP requests during the test.

Not going to insist though, not really my battle.

**Comment by nevack** [comment]
> Xcode build seems to be broken because I added new files. I have no way to fix that.

I can fix it locally and post patch as comment here, so you can apply it and push.
Are you good with this?

File: libtransmission/net.h (hunk 12 above)
[the remark this answers is not in the document]
Comment (tearfur) [reply libtransmission/net.h]: To be frank, I am completely new to writing tests, so I could very well be unfamiliar about the best practices. I'd like to hear what you have in mind.
For example, is it better if I write a test fixture class that simulates an HTTP response after calling `fetch()`?

For the encapsulation issue, I suppose it doesn't hurt to get rid of friend classes and add a public method to `tr_session` to expose `settings_.bind_address_ipv{4,6}` as long as it is not exposed in the C API. I will do that if it makes it easier for you to maintain in the future.

File: libtransmission/session.h [hunk 15]
```diff
@@ -1100,7 +1114,10 @@ struct tr_session
     // depends-on: open_files_
     tr_torrents torrents_;
 
-    // depends-on: settings_, session_thread_, torrents_
+    // depends-on: settings_, session_thread_, timer_maker_, web_
+    tr_global_ip_cache global_ip_cache_{ *this };
+
+    // depends-on: settings_, session_thread_, torrents_, global_ip_cache_
```
Comment (ckerr) [inline libtransmission/session.h:1120]: Is this comment change correct?  I don't see where WebMediator uses the ip cache..?

File: libtransmission/session.h [hunk 16]
```diff
@@ -1100,7 +1114,10 @@ struct tr_session
     // depends-on: open_files_
     tr_torrents torrents_;
 
-    // depends-on: settings_, session_thread_, torrents_
+    // depends-on: settings_, session_thread_, timer_maker_, web_
+    tr_global_ip_cache global_ip_cache_{ *this };
```
Comment (ckerr) [inline libtransmission/session.h:1118]: I don't love the idea of `tr_global_ip_cache` knowing about `tr_session`. It's been a lot of work to try & decouple some of these components, and once a class knows about `tr_session` basically no decoupling is possible. :disappointed: 

looks like the cache uses session for:

- its TimerMaker. This could accomplished passing a TimerMaker& into the constructor, instead
- `session_.fetch()`, in `update_global_addr()`. This could be accomplished by passing a tr_web& into that method instead.
- session_.settings_.bind_address_ipv4 and session_.settings_.bind_address_ipv6. This could be accomplished by passing them into the constructor and saving them as private member variables.
- having `TR_ASSERT(am_in_session_thread)` -- which, TBH, I'm not sure the cache code needs to know about the session thread, so maybe these can be removed?

File: libtransmission/global-ip-cache.h [hunk 17]
```diff
@@ -0,0 +1,115 @@
...
+    // We don't want it to trigger after the IP addresses have been destroyed
+    // (The destructor will acquire the IP address locks before proceeding, but still)
+    std::array<std::unique_ptr<libtransmission::Timer>, NUM_TR_AF_INET_TYPES> upkeep_timers_;
+
+    std::array<std::atomic_size_t, NUM_TR_AF_INET_TYPES> ix_service_ = {};
+    static auto constexpr IPQueryServices = std::array{ "https://icanhazip.com"sv, "https://api64.ipify.org"sv };
+    static auto constexpr UpkeepInterval = 30min;
+    static auto constexpr RetryUpkeepInterval = 30s;
+
+    friend struct tr_session;
```
Comment (ckerr) [inline libtransmission/global-ip-cache.h:114]: I'd prefer it if the class had no friends and instead had a public API that we could use both in tr_session and in the tests.

At a quick glance, it looks like tr_session is using:

- has_ip_protocol_[type]
- global_addr()
- global_source_addr()
- bind_addr()
- update_addr()
- try_shutdown()

If so, maybe those could be moved to the public section and 'friend' could be removed?

File: tests/libtransmission/net-test.cc [hunk 18]
```diff
@@ -180,8 +180,92 @@ TEST_F(NetTest, isGlobalUnicastAddress)
     }
 }
 
-TEST_F(NetTest, globalIPv6)
+namespace libtransmission::test
```
Comment (ckerr) [inline tests/libtransmission/net-test.cc:183]: the global ip cache tests should be moved into its own .cc file and added to the list of tests in CMakeLists.txt.

Happily, no xcode changes are necessary

File: tests/libtransmission/net-test.cc [hunk 19]
```diff
@@ -180,8 +180,92 @@ TEST_F(NetTest, isGlobalUnicastAddress)
...
 {
-    auto const addr = tr_globalIPv6();
-    EXPECT_TRUE(!addr || addr->is_global_unicast_address());
+
+using GlobalIPTest = SessionTest;
```
Comment (ckerr) [inline tests/libtransmission/net-test.cc:186]: If you agree with the idea of decoupling `tr_global_ip_cache` from `tr_session`, then this wouldn't need a session in order to be tested

File: libtransmission/tr-udp.cc [hunk 20]
```diff
@@ -246,13 +247,20 @@ void tr_session::tr_udp_core::sendto(void const* buf, size_t buflen, struct sock
         // don't warn on bad sockets; the system may not support IPv6
         return;
     }
+    else if (
```
[the remark this answers is not in the document]
Comment (tearfur) [reply libtransmission/tr-udp.cc:250]: I will happily comply. Just curious about the reasoning though.

File: libtransmission/session.h (hunk 15 above)
Comment (tearfur) [reply libtransmission/session.h:1120]: Oh that change is meant for `tr_web`. It uses `tr_global_ip_cache.global_source_addr()` indirectly by calling `tr_session.publicAddress()`.

What is the correct comment format here?

Comment (ckerr) [reply libtransmission/session.h:1122]: oh I see; yes you're right. Maybe a parenthetical `via tr_session.publicAddress()`?

File: libtransmission/global-ip-cache.h [hunk 21]
```diff
@@ -0,0 +1,123 @@
...
+    tr_global_ip_cache(tr_global_ip_cache&&) = delete;
+    tr_global_ip_cache& operator=(tr_global_ip_cache const&) = delete;
+    tr_global_ip_cache& operator=(tr_global_ip_cache&&) = delete;
+
+    bool try_shutdown() noexcept;
+
+    [[nodiscard]] std::optional<tr_address> global_addr(tr_address_type type) const noexcept;
+    [[nodiscard]] std::optional<tr_address> global_source_addr(tr_address_type type) const noexcept;
+
+    [[nodiscard]] tr_address bind_addr(tr_address_type type) const noexcept;
```
Comment (ckerr) [inline libtransmission/global-ip-cache.h:64]: This function makes sense here in the cache but it's slightly awkward that both this function and  tr_session::publicAddress() have to use tr_address::any_ipv4() and ::any_ipv6().

What if this function had the same return type as `tr_session::publicAddress()` and that function just acted as a pass-through to this one?

I haven't looked to see how many callers `bind_addr()` has, so weigh this suggestion against whether or not it makes other code more complicated by making use of this function a little more complex.

File: libtransmission/global-ip-cache.h [hunk 22]
```diff
@@ -0,0 +1,123 @@
...
+
+    void update_addr(tr_address_type type) noexcept;
+
+    // Whether this machine supports this IP protocol
+    array_ip_t<std::atomic_bool> has_ip_protocol_ = { true, true };
```
Comment (ckerr) [inline libtransmission/global-ip-cache.h:69]: Better to make this a constexpr getter so that `has_ip_protocol_` can be private and so that `array_ip_t` doesn't need to be public

```c++
[[nodiscard]] constexpr bool has_ip_protocol(tr_address_type type) const noexcept
{
    return af_data_[type].has_ip_protocol_;
}
```

File: libtransmission/global-ip-cache.h [hunk 23]
```diff
@@ -0,0 +1,123 @@
...
+#include <chrono> // operator ""min, operator ""s, std::chrono::milliseconds
+#include <memory> // std::unique_ptr
+#include <mutex>
+#include <optional>
+#include <shared_mutex>
+#include <string_view> // operator ""sv
+
+#include "net.h"
+#include "timer.h"
+#include "tr-assert.h"
```
Comment (ckerr) [inline libtransmission/global-ip-cache.h:18]: `tr-assert.h` not used in header; I think this line can be removed

File: libtransmission/global-ip-cache.h [hunk 24]
```diff
@@ -0,0 +1,123 @@
...
+#include "web.h"
+
+#pragma once
+
+#ifndef __TRANSMISSION__
+#error only libtransmission should #include this header.
+#endif
+
+using namespace std::literals;
```
Comment (ckerr) [inline libtransmission/global-ip-cache.h:27]: This `using` shouldn't be in a header.

File: libtransmission/global-ip-cache.h [hunk 25]
```diff
@@ -0,0 +1,123 @@
...
+    mutable array_ip_t<std::shared_mutex> source_addr_mutex_;
+    array_ip_t<std::optional<tr_address>> source_addr_;
+
+    // Keep the timer at the bottom of the class definition so that it will be destructed first
+    // We don't want it to trigger after the IP addresses have been destroyed
+    // (The destructor will acquire the IP address locks before proceeding, but still)
+    array_ip_t<std::unique_ptr<libtransmission::Timer>> upkeep_timers_;
+
+    array_ip_t<std::atomic_size_t> ix_service_ = {};
+    static auto constexpr IPQueryServices = std::array{ "https://icanhazip.com"sv, "https://api64.ipify.org"sv };
```
Comment (ckerr) [inline libtransmission/global-ip-cache.h:120]: This could be moved to an anonymous namespace in `global-ip-cache.cc`, which would let us remove `using namespace std::literals` from the header

**Review by ckerr — COMMENTED** [review]
Also, thanks for writing this and for addressing all the various review comments. This is looking pretty good.

File: libtransmission/session.h (hunk 16 above)
Comment (tearfur) [reply libtransmission/session.h:1120]: I will take my sweet time on this. When I think it through, it seems to me that `tr_global_ip_cache` will have to initialise in at least 3 separate stages after this change.

Fully expect to bump into obstacles on this one.

File: libtransmission/session.h (hunk 15 above)
Comment (tearfur) [reply libtransmission/session.h:1122]: Sure

File: libtransmission/global-ip-cache.h (hunk 22 above)
Comment (tearfur) [reply libtransmission/global-ip-cache.h:69]: It can't be constexpr since `std::atomic.load()` is not constexpr.

File: libtransmission/global-ip-cache.h (hunk 21 above)
Comment (tearfur) [reply libtransmission/global-ip-cache.h:64]: I think it is fine the way it is, these 2 functions use `any_ipv*()` in different ways, and their logic is also not exactly the same.

Actually, IMO the better way to fix this "awkwardness" is to add member functions to `tr_address` that tests if it is `INADDR_ANY`. Then we can also do away with `tr_session::PublicAddressResult`.

File: libtransmission/session.h (hunk 16 above)
Comment (ckerr) [reply libtransmission/session.h:1120]: You know this PR better than I do, but I'm not seeing the three stages -- could you walk me through them?

File: libtransmission/global-ip-cache.h (hunk 21 above)
Comment (ckerr) [reply libtransmission/global-ip-cache.h:64]: I like that idea a lot. :+1:

Comment (tearfur) [reply libtransmission/global-ip-cache.h:64]: Let's add the `tr_address` methods in another PR. I suppose we don't want too many items in a single PR as it will make changes harder to trace.

File: libtransmission/session.h (hunk 16 above)
Comment (tearfur) [reply libtransmission/session.h:1120]: Oh a second thought, do you know if anything will use `tr_session::publicAddress()` before `tr_session::setSettings()` is called in `tr_session::initImpl()`?

If there are none (and it makes sense that there are none), then I just need to construct `global_ip_cache_` inside `tr_session::initImpl()` with `tr_web&` and `TimerMaker&` as parameter, and then pass `settings_.bind_address_ipv*` inside `tr_session::setSettings()`.

File: libtransmission/net.h (hunk 12 above)
[the remark this answers is not in the document]
Comment (ckerr) [reply libtransmission/net.h]: marking as resolved since they are no longer friends of each other :+1:

File: libtransmission/global-ip-cache.h (hunk 21 above)
Comment (ckerr) [reply libtransmission/global-ip-cache.h:64]: https://github.com/transmission/transmission/pull/5398

File: libtransmission/global-ip-cache.h (hunk 22 above)
Comment (ckerr) [reply libtransmission/global-ip-cache.h]: adopted in 780d466d1cf91ad62b92e7411bae36a4b5044a93

File: libtransmission/global-ip-cache.h (hunk 25 above)
Comment (ckerr) [reply libtransmission/global-ip-cache.h]: adopted in dec109f22f7bfb3c4fd323136cf9d33100a0d424

File: libtransmission/global-ip-cache.h (hunk 24 above)
Comment (ckerr) [reply libtransmission/global-ip-cache.h]: fixed in  dec109f22f7bfb3c4fd323136cf9d33100a0d424

File: libtransmission/global-ip-cache.h (hunk 23 above)
Comment (ckerr) [reply libtransmission/global-ip-cache.h]: removed in 297b35dfc5c8e57a0fab641b8998283d36cd4e3b

File: libtransmission/net.h [hunk 26]
```diff
@@ -398,4 +408,87 @@ void tr_netSetTOS(tr_socket_t sock, int tos, tr_address_type type);
...
+    std::array<std::shared_mutex, NUM_TR_AF_INET_TYPES> global_addr_mutex_, source_addr_mutex_;
+    std::array<std::optional<tr_address>, NUM_TR_AF_INET_TYPES> global_addr_, source_addr_;
+
+    // Keep the timer at the bottom of the class definition so that it will be destructed first
+    // We don't want it to trigger after the IP addresses have been destroyed
+    // (The destructor will acquire the IP address locks before proceeding, but still)
+    std::array<std::unique_ptr<libtransmission::Timer>, NUM_TR_AF_INET_TYPES> upkeep_timers_;
+
+    std::array<std::atomic_size_t, NUM_TR_AF_INET_TYPES> ix_service_ = { 0U };
+    static auto constexpr IPQueryServices = std::array{ "https://icanhazip.com"sv, "https://api64.ipify.org"sv };
```
[the remark this answers is not in the document]
Comment (ckerr) [reply libtransmission/net.h]: This is a potential problem.

Transmission generally tries to not use any 3rd party services because we want to respect the privacy of our userbase.

I've pinged @titer, who maintains portcheck.transmissionbt.com, to see if we can do something under the transmissionbt.com domain. Otherwise, plan B would be to use https://www.bittorrent.org/beps/bep_0024.html.

**Comment by tearfur** [comment]
@ckerr Ah am I getting in the way of your merging spree? 🤡 

I actually have commits that addressed the resolved conversations, but I am away for the weekend so I haven't been able to push them.

I think I'll be able to work on decoupling `tr_session` from `tr_global_ip_cache` tomorrow.

File: libtransmission/net.h (hunk 26 above)
[the remark this answers is not in the document]
Comment (tearfur) [reply libtransmission/net.h]: Sure, I will use plan B while you try to figure out transmissionbt.com

**Comment by ckerr** [comment]
> @ckerr Ah am I getting in the way of your merging spree?

Nope! No hurry. I was just rereading the PR and it looked like low-hanging fruit, so I thought I'd go ahead and push it.

> I actually have commits that addressed the resolved conversations, but I am away for the weekend so I haven't been able to push them.

Ah, nice! I'll hold off and leave you to it.
 
> I think I'll be able to work on decoupling `tr_session` from `tr_global_ip_cache` tomorrow.

Sounds great.

**Comment by tearfur** [comment]
Looking for test ideas

**Comment by tearfur** [comment]
@ckerr Ready for review again. Addressed all review comments.

File: libtransmission/global-ip-cache.cc [hunk 27]
```diff
@@ -0,0 +1,375 @@
...
+    {
+        // Stop the update process since we have no public internet connectivity
+        unset_addr(type);
+        upkeep_timers_[type]->setInterval(RetryUpkeepInterval);
+        tr_logAddDebug(fmt::format(_("Couldn't obtain source {protocol} address"), fmt::arg("protocol", protocol)));
+        if (err == EAFNOSUPPORT)
+        {
+            stop_timer(type); // No point in retrying
+            has_ip_protocol_[type] = false;
+            tr_logAddWarn(fmt::format(_("Your machine does not support {protocol}"), fmt::arg("protocol", protocol)));
```
Comment (ckerr) [inline libtransmission/global-ip-cache.cc:258]: _(nit)_

Should be an `Info` instead of a `Warn`; it's reasonable to have an IPv4-only setup

File: libtransmission/session.cc [hunk 28]
```diff
@@ -697,6 +699,15 @@ void tr_session::setSettings(tr_session_settings&& settings_in, bool force)
...
     }
 
+    if (auto const& val = new_settings.bind_address_ipv4; force || val != old_settings.bind_address_ipv4)
+    {
+        global_ip_cache_->set_settings_bind_addr(TR_AF_INET, new_settings.bind_address_ipv4);
+    }
+    if (auto const& val = new_settings.bind_address_ipv6; force || val != old_settings.bind_address_ipv6)
+    {
+        global_ip_cache_->set_settings_bind_addr(TR_AF_INET6, new_settings.bind_address_ipv6);
+    }
```
Comment (ckerr) [inline libtransmission/session.cc:709]: There's another `bind_address_ipv4` / `bind_address_ipv6` block a couple of paragraphs further down (around line 735) and it looks like these two calls could be merged into that pre-existing code? Unless there's something in [710..735] that needs these lines to be called first?

File: libtransmission/global-ip-cache.cc [hunk 29]
```diff
@@ -0,0 +1,375 @@
...
+        tr_logAddInfo(fmt::format(
+            _("Successfully updated source {protocol} address to {ip}"),
+            fmt::arg("protocol", protocol),
+            fmt::arg("ip", source_addr->display_name())));
+    }
+    else
+    {
+        // Stop the update process since we have no public internet connectivity
+        unset_addr(type);
+        upkeep_timers_[type]->setInterval(RetryUpkeepInterval);
```
[the remark this answers is not in the document]
Comment (tearfur) [reply libtransmission/global-ip-cache.cc:252]: If I didn't miss anything, then this code will always be reached while the timer is running. In that case, `libtransmission::EvTimer::applyChanges()` will start the timer for me.

File: libtransmission/session.h [hunk 30]
```diff
@@ -777,8 +777,31 @@ struct tr_session
...
+
     [[nodiscard]] tr_address publicAddress(tr_address_type type) const noexcept;
 
+    [[nodiscard]] std::optional<tr_address> globalIP(tr_address_type type) const noexcept
+    {
+        TR_ASSERT(type == TR_AF_INET || type == TR_AF_INET6);
+        return global_ip_cache_->global_addr(type);
+    }
+
+    bool globalIP(tr_address const& addr) noexcept
```
[the remark this answers is not in the document]
Comment (tearfur) [reply libtransmission/session.h:794]: I used `external_address` instead of `external_ip` to be consistent with the naming with the rest of the code.

[the remark this answers is not in the document]
Comment (tearfur) [reply libtransmission/session.h:794]: I think the term "global" came from the definitions of the IP protocols. IMO it'd be more universal to follow that instead of BEP. Just use "external" when the BEP is involved in the code.

File: libtransmission/session.h [hunk 31]
```diff
@@ -777,8 +777,31 @@ struct tr_session
 
     [[nodiscard]] bool addressIsBlocked(tr_address const& addr) const noexcept;
 
+    [[nodiscard]] bool has_ip_protocol(tr_address_type type) const noexcept
+    {
+        TR_ASSERT(type == TR_AF_INET || type == TR_AF_INET6);
+        return global_ip_cache_->has_ip_protocol(type);
+    }
```
[the remark this answers is not in the document]
Comment (tearfur) [reply libtransmission/session.h:784]: It is for a follow up PR, just a handful of lines to change.

I want to keep them separate just so that the scope of the PRs are well-contained.

File: libtransmission/session.cc (hunk 28 above)
Comment (tearfur) [reply libtransmission/session.cc:709]: The `bind_address_ipv4` / `bind_address_ipv6` block below is enclosed within an `if (new_settings.tcp_enabled)`. We want `tr_global_ip_cache::set_settings_bind_addr()` to be called regardless of `tcp_enabled`.

File: libtransmission/global-ip-cache.h [hunk 32]
```diff
@@ -0,0 +1,124 @@
...
+ *
+ * The idea is, if this class successfully cached a source address, that means
+ * you have connectivity to the public internet. And if the global address is
+ * the same with the source address, then you are not behind an NAT.
+ *
+ */
+class tr_global_ip_cache
+{
+public:
+    explicit tr_global_ip_cache(tr_web& web_in, libtransmission::TimerMaker& timer_maker_in);
```
[the remark this answers is not in the document]
Comment (tearfur) [reply libtransmission/global-ip-cache.h:42]: Removed.

**Review by ckerr — APPROVED** [review]

File: libtransmission/global-ip-cache.cc [hunk 33]
```diff
@@ -0,0 +1,363 @@
...
+#include "libtransmission/global-ip-cache.h"
+#include "libtransmission/tr-assert.h"
+#include "libtransmission/utils.h"
+
+namespace
+{
+
+using namespace std::literals;
+
+auto constexpr IPQueryServices = std::array{ "https://icanhazip.com"sv, "https://api64.ipify.org"sv };
```
Comment (mikedld) [inline libtransmission/global-ip-cache.cc:31]: Didn't we set up a couple of own hosts for this?..

Comment (tearfur) [reply libtransmission/global-ip-cache.cc:31]: It will be a few minutes work for me to change the code to use your IP query endpoints if you do have them.

Comment (titer) [reply libtransmission/global-ip-cache.cc:31]: We have these endpoints set up
* https://ip4.transmissionbt.com/
* https://ip6.transmissionbt.com/

Though we could also expose a dual-stack hostname if that is prefered

Comment (tearfur) [reply libtransmission/global-ip-cache.cc:31]: @titer A dual-stack hostname would be most convenient.

Does that take a lot more work for you?

Comment (tearfur) [reply libtransmission/global-ip-cache.cc:31]: On a second thought, the current endpoints are fine. It does not take a lot of code change on my part to use them.

Please keep them as they are.

**Comment by ckerr** [comment]
@tearfur what is a good way to summarize 5329 / 5498 / 5510 for the 4.1.0 release notes?

**Comment by tearfur** [comment]
@ckerr It for sure is hard to boil it down to 1 sentence. 😛 

> Added ability to cache IP addresses used in global communications, and use it to fix UDP6 warning log spam.

What do you think? I am wondering if I should directly describe the underlying cause of the UDP6 log spam, or if this is fine.
