### PR TITLE
[Web] Magnet link, Main window toolbar accessibility, ARM build fix, Dependencies update

### LINKED ISSUE #817: [feature-request] Add magnet URL to web interface info panel
I would find it very useful if the web interface could provide the magnet URL of a torrent that is added to transmission. It is retrievable using `transmission-remote` but I do not always have console access and the web interface is very convenient. Just a line in the Details section with selectable (copy-paste) text would suffice.

### LINKED ISSUE #1346: [Accessibility] "Open Torrent" button is difficult to operate with the keyboard
The "Open Torrent" button in the toolbar has the following problems:
1. The keyboard cannot navigate and focus.
2. For screen reading software, the lack of a "button" prompt for the control role prevents visually impaired people using the screen reading software from learning the control role.
3. The button cannot be activated using the keyboard space bar.

### LINKED ISSUE #2583: img-optimize-loader fails the build on native ARM
It crashes the build due to gifsicle-bin's incompatibility with ARM - https://github.com/imagemin/gifsicle-bin/issues/124 :
```
#18 119.0 [4/4] Building fresh packages...
#18 130.5 warning Error running install script for optional dependency: "/opt/transmission/build/web/node_modules/optipng-bin: Command failed.
#18 130.5 Exit code: 1
#18 130.5 Command: node lib/install.js
#18 130.5 Arguments: 
#18 130.5 Directory: /opt/transmission/build/web/node_modules/optipng-bin
#18 130.5 Output:
#18 130.5 ⚠ Command failed: /opt/transmission/build/web/node_modules/optipng-bin/vendor/optipng --version
#18 130.5 /opt/transmission/build/web/node_modules/optipng-bin/vendor/optipng: 1: @@8�\u0001@8\b@\u001d\u001c\u0006\u0005@@@@@�\u0001�\u0001\b\u0003\u0004\u0002\u0002@\u0002@\u001c\u001c\u0001\u0001\u0005@@��\u0001��\u0001: not found
#18 130.5 /opt/transmission/build/web/node_modules/optipng-bin/vendor/optipng: 2: d: not found
#18 130.5 /opt/transmission/build/web/node_modules/optipng-bin/vendor/optipng: 1: Syntax error: \";\" unexpected
#18 130.5 /opt/transmission/build/web/node_modules/optipng-bin/vendor/optipng: 1: ELF\u0002\u0001\u0001\u0002: not found
#18 130.5 
#18 130.5 
#18 130.5   ⚠ optipng pre-build test failed
#18 130.5   ℹ compiling from source
#18 130.5   ✖ Error: Command failed: /bin/sh -c make install
#18 130.5 pngrtran.c:99:1: warning: 'png_rtran_ok' defined but not used [-Wunused-function]
#18 130.5    99 | png_rtran_ok(png_structrp png_ptr, int need_IHDR)
#18 130.5       | ^~~~~~~~~~~~
#18 130.5 ar: `u' modifier ignored since `D' is the default (see `U')
#18 130.5 ar: `u' modifier ignored since `D' is the default (see `U')
#18 130.5 ar: `u' modifier ignored since `D' is the default (see `U')
#18 130.5 ar: `u' modifier ignored since `D' is the default (see `U')
#18 130.5 pngxmem.c: In function 'pngx_malloc_rows_extended':
#18 130.5 pngxmem.c:38:34: warning: comparison is always false due to limited range of data type [-Wtype-limits]
#18 130.5    38 |        (pngx_alloc_size_t)height > (pngx_alloc_size_t)(-1) / sizeof(png_bytep))
#18 130.5       |                                  ^
#18 130.5 ar: `u' modifier ignored since `D' is the default (see `U')
#18 130.5 /usr/bin/ld: ../libpng/libpng.a(pngrutil.o): in function `png_read_filter_row':
#18 130.5 pngrutil.c:(.text+0x22f0): undefined reference to `png_init_filter_functions_neon'
#18 130.5 collect2: error: ld returned 1 exit status
#18 130.5 make[4]: *** [Makefile:100: optipng] Error 1
#18 130.5 make[3]: *** [Makefile:14: install] Error 2
#18 130.5 
#18 130.5 
#18 130.5     at /opt/transmission/build/web/node_modules/bin-build/node_modules/execa/index.js:231:11
#18 130.5     at runMicrotasks (<anonymous>)
#18 130.5     at processTicksAndRejections (node:internal/process/task_queues:96:5)
#18 130.5     at async /opt/transmission/build/web/node_modules/optipng-bin/lib/install.js:18:4"
#18 130.5 info This module is OPTIONAL, you can safely ignore this error
#18 270.5 error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/opt/transmission/build/web/node_modules/gifsicle/\u0001\f3@@@�'".
#18 270.5 info If you think this is a bug, please open a bug report with the information provided in "/opt/transmission/build/web/yarn-error.log".
#18 270.5 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#18 270.5 make[2]: *** [web/CMakeFiles/trweb.dir/build.make:106: web/CMakeFiles/trweb] Error 1
#18 270.5 make[1]: *** [CMakeFiles/Makefile2:593: web/CMakeFiles/trweb.dir/all] Error 2
#18 270.5 make: *** [Makefile:156: all] Error 2
```

Is it needed and used? It is not set up in webpack.config.js.

### PR DESCRIPTION
**Pull request by FluxState**
Closes #817 -  [feature-request] Add magnet URL to web interface info panel
Closes #1346 - [Accessibility] "Open Torrent" button is difficult to operate with the keyboard
Closes #2583 - img-optimize-loader fails the build on native ARM
Updates dependencies' minor versions.

### CODE REVIEW

File: web/src/inspector.js [hunk 1]
```diff
@@ -528,6 +529,23 @@ export class Inspector extends EventTarget {
...
+      string = torrents.every((t) => get(t) === first) ? first : mixed;
+    }
+    if (none !== string) {
+      Utils.setInnerHTML(
+        e.info.magnetLink,
+        `<a class="inspector-info-magnet" href="${string}"><button></button></a>`
+      );
+    } else {
+      setTextContent(e.info.magnetLink, string);
+    }
```
Comment (ckerr) [inline web/src/inspector.js:548]: Since magnet links include an escaped version of the torrent's info-hash, we know that `torrents.every()` will always fail unless length ==== 1

```suggestion
    // magnetLink
    if (torrents.length === 0) {
      setTextContent(e.info.magnetLink, none);
    } else if (torrents.length > 1) {
      setTextContent(e.info.magnetLink, mixed);
    } else {
      const link = torrents[0].getMagnetLink();
      Utils.setInnerHTML(
        e.info.magnetLink,
        `<a class="inspector-info-magnet" href="${link}"><button></button></a>`
      );
  }
```

File: web/yarn.lock [hunk 2]
```diff
@@ -8581,9 +6772,9 @@ yargs-parser@^13.1.2:
     decamelize "^1.2.0"
 
 yargs-parser@^20.2.2, yargs-parser@^20.2.3:
-  version "20.2.7"
-  resolved "https://registry.yarnpkg.com/yargs-parser/-/yargs-parser-20.2.7.tgz#61df85c113edfb5a7a4e36eb8aa60ef423cbc90a"
-  integrity sha512-FiNkvbeHzB/syOjIUxFDCnhSfzAL8R5vs40MgLFBorXACCOAEaWu0gRZl14vG8MR9AOJIZbmkjhusqBYZ3HTHw==
+  version "20.2.9"
+  resolved "https://registry.yarnpkg.com/yargs-parser/-/yargs-parser-20.2.9.tgz#2eb7dc3b0289718fc295f362753845c41a0c94ee"
+  integrity sha512-y11nGElTIV+CT3Zv9t7VKl+Q3hTQoT9a1Qzezhhl6Rp21gJ/IVTW7Z3y9EWXhuUBC2Shnf+DX0antecpAwSP8w==
```
Comment (ckerr) [inline web/yarn.lock]: Kind of incredible that the lockfile's shrunk by about 2K lines from those package changes. Looks like it comes mostly from removing img-optimize-loader? :exploding_head:

Comment (FluxState) [reply web/yarn.lock]: It carries multiple dependencies - including optionalDependencies and their dependencies. You get the... picture 😄 
```
  dependencies:
    imagemin "^7.0.1"
    loader-utils "^2.0.0"
    mime-types "^2.1.27"
    schema-utils "^2.7.0"
  optionalDependencies:
    imagemin-gifsicle "^6.0.1"
    imagemin-mozjpeg "^8.0.0"
    imagemin-optipng "^7.1.0"
    imagemin-pngquant "^8.0.0"
    imagemin-svgo "^7.0.0"
    imagemin-webp "^5.1.0"
```

Also, the newest lockfile is built against LTS Node v16.

**Review by ckerr — APPROVED** [review]
