### PR TITLE
fix: return error when renaming into existing file

### LINKED ISSUE #5555: Transmission lets you rename one of a torrent's files to match another of the torrent's files
### What is the issue?

I have encountered a bug. If you rename a file to have exact same filename as another file in the same torrent it will let you. And if you then close and reopen properties, it will contain only one file with that name.

I believe this bug to be in libtorrent itself. [This issue](https://github.com/transmission/transmission/issues/909#issue-444983198) clearly references the same bug in Qt version of the application.

When I look at the documentation, tr_torrentRenamePath function is supposed to return EINVAL when attempting to rename to existing filename, but it doesn't do that, and there are no tests checking that.

I can try to fix this bug myself, if needed.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.1.0-dev (87472672a6)

### PR DESCRIPTION
**Pull request by basilefff**
My attempt at resolving [this issue](https://github.com/transmission/transmission/issues/5555#issue-1723972944).

 *edit by @ckerr:* @basilefff use the phrase "Fixes #DDDD" so GitHub will understand and link the issue and PR together :tada:

Fixes #5555.

### CODE REVIEW

File: libtransmission/torrent.cc [hunk 1]
```diff
@@ -2453,6 +2453,37 @@ bool renameArgsAreValid(std::string_view oldpath, std::string_view newname)
         !tr_strvContains(newname, TR_PATH_DELIMITER);
 }
 
+bool renameNoCollision(tr_torrent const* tor, std::string_view oldpath, std::string_view newname)
```
Comment (ckerr) [inline libtransmission/torrent.cc:2456]: _(nit)_

- maybe a different function name to clarify this function makes no changes
- also, please avoid negative logic ("NoCollision") in function names because they're confusing.

Maybe inverti the return values and rename the function as `renameWouldCauseCollision()`?

File: libtransmission/torrent.cc [hunk 2]
```diff
@@ -2453,6 +2453,37 @@ bool renameArgsAreValid(std::string_view oldpath, std::string_view newname)
...
+{
+    std::string newpath{};
+    if (tr_strvContains(oldpath, TR_PATH_DELIMITER))
+    {
+        newpath = fmt::format(FMT_STRING("{:s}/{:s}"sv), tr_sys_path_dirname(oldpath), newname);
+    }
+    else
+    {
+        newpath = newname;
+    }
```
Comment (ckerr) [inline libtransmission/torrent.cc:2466]: _(nit)_ `newpath` can const. Also it can be a `tr_pathbuf` to avoid heap allocations

```suggestion
    auto const newpath = tr_strvContains(oldpath, TR_PATH_DELIMITER) ?
        tr_pathbuf{ tr_sys_path_dirname(oldpath), '/', newname } :
        newname;
```

**Review by ckerr — CHANGES_REQUESTED** [review]
Thanks for this PR! I had minor change requests but overall the idea LGTM

File: libtransmission/torrent.cc (hunk 1 above)
Comment (ckerr) [inline libtransmission/torrent.cc:2456]: I think I would fold this into `renameArgsAreValid()` instead of making it a separate function.

File: libtransmission/torrent.cc [hunk 3]
```diff
@@ -2453,6 +2453,37 @@ bool renameArgsAreValid(std::string_view oldpath, std::string_view newname)
...
+    if (newpath == oldpath)
```
Comment (ckerr) [inline libtransmission/torrent.cc:2467]: This can be made `const` and can also be a `tr_pathbuf` to avoid heap allocs

```suggestion
    auto const newpath = tr_strvContains(oldpath, TR_PATH_DELIMITER) ?
        tr_pathbuf{ tr_sys_path_dirname(oldpath), '/', newname } :
        tr_pathbuf{ newname };
```

File: libtransmission/torrent.cc [hunk 4]
```diff
@@ -2453,6 +2453,37 @@ bool renameArgsAreValid(std::string_view oldpath, std::string_view newname)
...
+        return true;
+    }
+
+    auto const newpath_as_dir = tr_pathbuf{ newpath, '/' };
+    auto const n_files = tor->file_count();
+
+    for (tr_file_index_t i = 0; i < n_files; ++i)
+    {
+        auto const& name = tor->file_subpath(i);
+        if (name == newpath || tr_strvStartsWith(name, newpath_as_dir))
```
Comment (ckerr) [inline libtransmission/torrent.cc:2478]: If `newpath` is a `tr_pathbuf` as per the previous comment, I think the `==` will need to be reversed to make the compiler happy, e.g.

```suggestion
        if (newpath == name || tr_strvStartsWith(name, newpath_as_dir))
```

**Review by ckerr — CHANGES_REQUESTED** [review]

**Comment by basilefff** [comment]
@ckerr I added requested fixes, can you review them?

**Review by ckerr — APPROVED** [review]
Thanks!

**Comment by ckerr** [comment]
Notes: Fixed filename collision edge case when renaming files.
