### PR TITLE
fix(qt): opening a torrent file on Windows launches a new instance

### LINKED ISSUE #7629: New app instance for each new torrent opening on Windows
### What is the issue?

Latest public Win 11

4.1 beta introduced a regression: every time you open a torrent file from disk new app instance is created.

So if you open 5 *.torrent files from downloads, you’l get 5 separate transmission apps and 5 icons in tray.

With 4.0 torrents are opened in already existing app (if present).

### Which application of Transmission?

None

### Which version of Transmission?

4.1.0-beta.2 (ac5c9e082d)

### PR DESCRIPTION
**Pull request by sanapci**
Fixes #7629 

As a side note, maybe it would be also a good idea to add a [vcpkg.json file](https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-json) instead of command line command execution.

Explanation:
If CMake will not find Qt's AX Client and Server modules and manages to find the DBus module, there will be no thrown error.

Since DBus is not really available on Windows and AX related preprocessor variable (_ENABLE_COM_INTEROP_) is false and the `tryDelegate()` and `InteropHelper::isConnected()` functions will return false, like no other instance is running.

Because of this, when the transmission-qt opens new torrent file, it will not be able to connect to the other instance via IPC and starts a new instance,

Notes: Fixed build script bug that could cause extra instances of Transmission to launch on Windows.

### CODE REVIEW

**Comment by ckerr** [comment]
> As a side note, maybe it would be also a good idea to add a vcpkg.json file instead of command line command execution.

@sanapci if you'd like to update the build-on-Windows steps including a vcpkg.json file I would LOOOVE a PR on that. I spent a significant amount of time building on Windows last weekend and this weekend & hit several snags with the translation module, with an install issue in qtbase 6.9.x, with trying to switch between static and dynamic builds -- and finally with icons not loading properly (so I suspect I still wasn't installing everything correctly).

If you (or anyone!) wants to make it easier to make a dev build of Transmission on windows either via the command line or Visual Studio via vcpkg.json, please do.

File: qt/TorrentModel.cc [hunk 1]
```diff
@@ -328,7 +328,13 @@ void TorrentModel::updateTorrents(tr_variant* torrent_list, bool is_complete_lis
...
         torrents_t removed;
         removed.reserve(old.size());
-        std::set_difference(old.begin(), old.end(), processed.begin(), processed.end(), std::back_inserter(removed));
+        std::set_difference(
+            old.begin(),
+            old.end(),
+            processed.begin(),
+            processed.end(),
+            std::back_inserter(removed),
+            TorrentIdLessThan());
```
Comment (ckerr) [inline qt/TorrentModel.cc]: This change looks OK, but is it related to the topic of this PR? It seems like it's a separate fix.

Comment (sanapci) [reply qt/TorrentModel.cc]: You are right, it is a bit different topic (https://github.com/transmission/transmission/issues/7182), it just came across when I took a look on the original error.

**Comment by sanapci** [comment]
> If you (or anyone!) wants to make it easier to make a dev build of Transmission on windows either via the command line or Visual Studio via vcpkg.json, please do.

Well, maybe I could try to setup that, but I might need some time for that. (I am not really using Windows, only for one dedicated software that is not running under Linux and I am really out of space on that machine. This small PR also took a week to create, because I was quite busy this week and the building failed usually by running out of space. 🤣 )

File: qt/TorrentModel.cc (hunk 1 above)
Comment (ckerr) [reply qt/TorrentModel.cc]: Please make a separate PR for it and remove it from this one so that there is one topic per PR :+1:
