### PR TITLE
magnet links on restart seeding fix macOS

### LINKED ISSUE #2727: nightly assertion failed: bit_count_:53, n:139, std::size(flags_):21 (bitfield.cc:226
Crash during verification of a file. 

[3.00+ (a009a7f930)Crash.txt](https://github.com/transmission/transmission/files/8177871/3.00%2B.a009a7f930.Crash.txt)

### LINKED ISSUE #2787: Non-downloaded magnet links show as seeding
I updated nightly today and non-downloaded magnet links (ie: where the torrent file hasn't been grabbed yet) now show as seeding even though the torrent is at the very beginning of its journey.

### LINKED ISSUE #2842: [f1a028bb84] Crash on launch: "tr_file_piece_map::fileOffset(unsigned long long) const"
It was running fine for a few hours, and now it crashes on launch.

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Thread 6 Crashed:
0   org.m0k.transmission          	0x0000000103158e7a tr_file_piece_map::fileOffset(unsigned long long) const + 96
1   org.m0k.transmission          	0x000000010311b17d (anonymous namespace)::readOrWritePiece(tr_torrent*, (anonymous namespace)::IoMode, tr_block_info::Location, unsigned char*, unsigned long) + 105
2   org.m0k.transmission          	0x000000010311c0cb tr_ioTestPiece(tr_torrent*, unsigned int) + 155
3   org.m0k.transmission          	0x0000000103109e4c tr_torrent::checkPiece(unsigned int) + 44
4   org.m0k.transmission          	0x000000010310da9a tr_torrent::ensurePieceIsChecked(unsigned int) + 68
5   org.m0k.transmission          	0x0000000103106b7e tr_torrentNew(tr_ctor*, tr_torrent**) + 2809
6   org.m0k.transmission          	0x00000001030fd1f2 sessionLoadTorrents(sessionLoadTorrentsData*) + 843
7   org.m0k.transmission          	0x00000001031263da onWorkAvailable(int, short, void*) + 127
8   org.m0k.transmission          	0x000000010319e9aa event_process_active_single_queue + 502
9   org.m0k.transmission          	0x000000010319ba99 event_base_loop + 1130
10  org.m0k.transmission          	0x0000000103125fd9 libeventThreadFunc(tr_event_handle*) + 253
11  org.m0k.transmission          	0x0000000103126af3 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(tr_event_handle*), tr_event_handle*> >(void*) + 40
12  libsystem_pthread.dylib       	0x00007fff60a522eb _pthread_body + 126
13  libsystem_pthread.dylib       	0x00007fff60a55249 _pthread_start + 66
14  libsystem_pthread.dylib       	0x00007fff60a5140d thread_start + 13

Capture d’écran 2022-03-31 à 01 05 12

### PR DESCRIPTION
**Pull request by sweetppro**
fix for when magnet links when reloaded on restart showing as seeding.

Fixes #2787

Fixes #2842

Fixes #2727

### CODE REVIEW

File: libtransmission/completion.cc [hunk 1]
```diff
@@ -119,7 +119,7 @@ tr_completeness tr_completion::status() const
         return TR_SEED;
     }
 
-    if (size_now_ == sizeWhenDone())
+    if (size_now_ == sizeWhenDone() && sizeWhenDone() != 0)
```
Comment (ckerr) [inline libtransmission/completion.cc:122]:
```suggestion
    if (hasMetainfo() && size_now_ == sizeWhenDone())
```

Comment (sweetppro) [reply libtransmission/completion.cc:122]: `size_now_ == sizeWhenDone()` both are 0 for a magnet link

Comment (sweetppro) [reply libtransmission/completion.cc:122]: also `hasMetainfo()` is returning true for the magnet links

Comment (sweetppro) [reply libtransmission/completion.cc:122]: @ckerr
```
if (!hasNone() && size_now_ == sizeWhenDone())
```

works in this situation

Comment (ckerr) [reply libtransmission/completion.cc]: `hasMetainfo()` returns true iff we have any piece data for that torrent (tested by checking `!std::empty(blocks_)`. Sounds like either a bug in `hasMetainfo()` or a mistake in testing it here?

Comment (sweetppro) [reply libtransmission/completion.cc]: yup,
for newly added magnet links `hasMetainfo()` returns `true` - at least on macOS
`hasMetadata()` on the other hand returns false, but this is not available in `completion.cc`

Comment (sweetppro) [reply libtransmission/completion.cc]: how about something like this for `hasMetainfo()`:
```
[[nodiscard]] constexpr bool hasMetainfo() const
    {
        // magnet links
        if (size_when_done_ == 0) {
            return false;
        }
        return !std::empty(blocks_);
    }
```

Comment (ckerr) [reply libtransmission/completion.cc]: ...I am not sure how that could be happening. There are no blocks for it to have, and it doesn't know what the block size of the torrent is, so at this point the count should always be zero. I hear what you're saying about the workaround but it smells like there's a bug here and I'd like to figure out if there's something else that needs to be fixed, too.

I added this test patch locally:

```diff
diff --git a/libtransmission/completion.h b/libtransmission/completion.h
index 522163be0..81f68b253 100644
--- a/libtransmission/completion.h
+++ b/libtransmission/completion.h
@@ -15,6 +15,8 @@
 #include <optional>
 #include <vector>
 
+#include <iostream> // nocommit
+
 #include "transmission.h"
 
 #include "block-info.h"
@@ -130,9 +132,11 @@ struct tr_completion
     [[nodiscard]] uint64_t countHasBytesInSpan(tr_byte_span_t) const;
 
 private:
-    [[nodiscard]] constexpr bool hasMetainfo() const
+    [[nodiscard]] bool hasMetainfo() const
     {
-        return !std::empty(blocks_);
+        auto const ret = !std::empty(blocks_);
+        std::cerr << __FILE__ << ':' << __LINE__ << ' ' << ret << std::endl;
+        return ret;
     }
 
     [[nodiscard]] uint64_t computeHasValid() const;
```

and then fired up an empty (no torrents) session and added a magnet link. What I got was:

```sh
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
/tmp/foo/transmission/libtransmission/completion.h:138 0
```

Could you describe the steps I should follow to try and test this to get this to return 1 instead of 0?

Comment (sweetppro) [reply libtransmission/completion.cc]: strange,
I emptied my session, and started with new magnet links... and now I get the expected results...

Im not sure what's going on...
possibly cruft from an earlier build?

**Review by ckerr — COMMENTED** [review]
I think maybe we need to go back and try and reproduce the problem again to investigate the cause --

I'm happy that `hasMetainfo()` is doing the right thing now, but look 8 lines up from this one-liner: we already are checking for `hasMetainfo()` and returning `TR_LEECH`  if we don't have metainfo:

```cpp
tr_completeness tr_completion::status() const
{
    if (!hasMetainfo())
    {
        return TR_LEECH;
    }

    if (hasAll())
    {
        return TR_SEED;
    }

    if (hasMetainfo() && size_now_ == sizeWhenDone())
    {
        return TR_PARTIAL_SEED;
    }

    return TR_LEECH;
```

...in the line being changed, can `hasMetainfo()` ever be false?

**Comment by sweetppro** [comment]
There’s definitely something fishy going on….
I don’t know how the magnet links get into that state… but my original PR where we check for  `sizeWhenDone() == 0` catches the magnet links when they’re like that.

**Comment by sweetppro** [comment]
> I think maybe we need to go back and try and reproduce the problem again to investigate the cause --
Ill play around more and try to reproduce the issue

**Review by ckerr — CHANGES_REQUESTED** [review]
We need to understand the problem better before merging anything. I'm happy to help any way I can but haven't been able to reproduce the issue yet.

**Comment by sweetppro** [comment]
I thought perhaps it occurred when Transmission was quit with partially downloaded magnet link meta data… but nope. So I don’t know…

**Comment by sweetppro** [comment]
Could we also add a check for sizewhendone being 0 in hasmetainfo(). That would catch the issue when a magnet link ends up in this state.

**Comment by sweetppro** [comment]
it just happened, but I don't know what caused it....

**Comment by ckerr** [comment]
> the following seems to catch it, do you see any issues with this?
> 
> ```
> tr_completeness tr_completion::status() const
> {
>     if (hasNone())
>     {
>         return TR_LEECH;
> ```

The only issue I see here might not be worth worrying about -- it will show a torrent as downloading even if the user has flagged that they don't want _any_ of the files

**Comment by sweetppro** [comment]
then how about:
```
tr_completeness tr_completion::status() const
{
    if (!hasMetainfo() || hasNone())
    {
        return TR_LEECH;
```

**Comment by ckerr** [comment]
OK so you're suggesting

```c++
tr_completeness tr_completion::status() const
{
    if (!hasMetainfo() || hasNone())
    {
        return TR_LEECH;
    }

    if (hasAll())
    {
        return TR_SEED;
    }

    if (size_now_ == sizeWhenDone())
    {
        return TR_PARTIAL_SEED;
    }

    return TR_LEECH;
} 
```

is that correct?

**Comment by sweetppro** [comment]
> is that correct?

yes, this fixes the issue as far as I can see

**Comment by ckerr** [comment]
:confused: 

The current code is

```c++
tr_completeness tr_completion::status() const
{
    if (!hasMetainfo())
    {
        return TR_LEECH;
    }

    if (hasAll())
    {
        return TR_SEED;
    }

    if (size_now_ == sizeWhenDone())
    {
        return TR_PARTIAL_SEED;
    }

    return TR_LEECH;
}
```

which is _really_ similar.

I feel uncomfortable merging a fix without understanding the bug, but I'm still not able to reproduce this and your version looks fine, so :man_shrugging: 

If that revision works but `main` is broken, it makes me think that maybe somehow hasAll() is returning true when it shouldn't.

**Comment by sweetppro** [comment]
@ckerr the bug is in `hasMetainfo()`
for some reason when there is a .torrent file which is loaded before a .magnet file then `hasMetainfo()` also returns as true for the magnet link.

**Comment by sweetppro** [comment]
I've don't some more digging, and it looks as though the issue stems from `tr_ctorSetMetainfoFromMagnetLink` it seems that `metainfo` is being loaded from any previous loaded torrents. Clearing the meta info on creation with `ctor->metainfo = {};` fixes this. Is there a better way, or is this adequate
```
bool tr_ctorSetMetainfoFromMagnetLink(tr_ctor* ctor, char const* magnet_link, tr_error** error)
{
    ctor->torrent_filename.clear();
    ctor->metainfo = {};
    return ctor->metainfo.parseMagnet(magnet_link != nullptr ? magnet_link : "", error);
}
```

**Comment by sweetppro** [comment]
This PR also fixes the crash introduced in https://github.com/transmission/transmission/commit/4177e286a1fc20a48c1eb26ca5e7cf5d5713b7ff
on macOS

**Comment by sweetppro** [comment]
This build also fixes a crash at startup in build https://github.com/transmission/transmission/commit/f1a028bb84b20924e19d634198d2dc7bab317834
[f1a028bb84b20924e19d634198d2dc7bab317834.txt](https://github.com/transmission/transmission/files/8373867/f1a028bb84b20924e19d634198d2dc7bab317834.txt)

**Comment by GScottElshaw** [comment]
> This build also fixes a crash at startup in build [f1a028b](https://github.com/transmission/transmission/commit/f1a028bb84b20924e19d634198d2dc7bab317834) [f1a028bb84b20924e19d634198d2dc7bab317834.txt](https://github.com/transmission/transmission/files/8373867/f1a028bb84b20924e19d634198d2dc7bab317834.txt)

@ckerr Charles, can someone in the maintainer team please set aside some time to review and commit a bunch of PR's? I know you're busy and hard at work every day on this project, work, and life; can someone else who has the time be given the authority to merge with the correct skills if they have the requisite platform skills? @DevilDimon comes to mind, but there are others.

**Comment by Coeur** [comment]
Whoah, just tested this fix, it works fabulous!
I had tons of magnets stuck for days, and with this change they all got metadata within a minute.
Please merge it.

**Review by Coeur — APPROVED** [review]

**Comment by ckerr** [comment]
> I've don't some more digging, and it looks as though the issue stems from `tr_ctorSetMetainfoFromMagnetLink` it seems that `metainfo` is being loaded from any previous loaded torrents. Clearing the meta info on creation with `ctor->metainfo = {};` fixes this. Is there a better way, or is this adequate
> 
> ```
> bool tr_ctorSetMetainfoFromMagnetLink(tr_ctor* ctor, char const* magnet_link, tr_error** error)
> {
>     ctor->torrent_filename.clear();
>     ctor->metainfo = {};
>     return ctor->metainfo.parseMagnet(magnet_link != nullptr ? magnet_link : "", error);
> }
> ```

Ahhhhh now _this_ makes sense! This is the root cause. Thank  you @sweetppro for finding this :heart: and I'm sorry I didn't notice this update sooner so also thanks to @Coeur and @GScottElshaw for the prompt

**Review by ckerr — APPROVED** [review]

**Comment by GScottElshaw** [comment]
Thanks for your work on this @sweetppro.
